-- Function: cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION"(integer, integer, integer)

-- DROP FUNCTION cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION"(integer, integer, integer);

CREATE OR REPLACE FUNCTION cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION"(
    IN months integer,
    IN initial_month integer,
    IN final_month integer)
  RETURNS TABLE("LLAVE_UNIVERSAL" character varying, "FECHA" integer, "SALDO" double precision, "CARTERA_VENCIDA" double precision, "RANGO_DA" character varying, "EMPRESARIAL_NEXT" INTEGER) AS
$BODY$
DECLARE
BEGIN

RETURN QUERY SELECT
	T1."LLAVE_UNIVERSAL",
	T1."FECHA",
	T1."SALDO",
	T1."CARTERA_VENCIDA",
	-- (FLOOR(T2."FECHA"/100) - FLOOR(T1."FECHA"/100))*12 + MOD(T2."FECHA",100) - MOD(T1."FECHA",100) = MONTHS AS NEXT_MONTHS,
	CASE
		WHEN (FLOOR(T2."FECHA"/100) - FLOOR(T1."FECHA"/100))*12 + MOD(T2."FECHA",100) - MOD(T1."FECHA",100) <> MONTHS THEN NULL::VARCHAR
		WHEN T2."DIAS_ATRASO" IS NULL OR T2."DIAS_ATRASO" = 0 THEN '00: CERO DÍAS'::VARCHAR
		WHEN T2."DIAS_ATRASO" BETWEEN 1 AND 29 THEN '01: 001 A 029 DÍAS'::VARCHAR
		WHEN T2."DIAS_ATRASO" BETWEEN 30 AND 179 THEN CONCAT(LPAD((FLOOR(T2."DIAS_ATRASO"/30)+1)::VARCHAR,2,'0'),': ',LPAD((FLOOR(T2."DIAS_ATRASO"/30)*30)::VARCHAR,3,'0'),' - ',LPAD(((FLOOR(T2."DIAS_ATRASO"/30)+1)*30-1)::VARCHAR,3,'0'),' DÍAS')::VARCHAR
		ELSE '07: 180+ DÍAS'
	END::VARCHAR AS "RANGO_DA",
	CASE
		WHEN T2."CLASS15"='Negocios' THEN 0
		WHEN T2."CLASS15"='Empresarial' THEN 1
		ELSE NULL::INTEGER
	END::INTEGER AS "EMPRESARIAL_NEXT"
FROM
	cartera."Tbl_CarteraCrediticia" T1
JOIN 
	cartera."Tbl_CarteraCrediticia" T2
ON
	T2."LLAVE_UNIVERSAL" = T1."LLAVE_UNIVERSAL"	
WHERE
	T1."FECHA" BETWEEN initial_month AND final_month
	AND T2."FECHA_DATE" BETWEEN TO_DATE(initial_month::VARCHAR, 'YYYYMM') AND TO_DATE(final_month::VARCHAR, 'YYYYMM') + INTERVAL'1 MONTH'*MONTHS
	AND T1."CLASS15" = 'Negocios'
	AND (FLOOR(T2."FECHA"/100) - FLOOR(T1."FECHA"/100))*12 + MOD(T2."FECHA",100) - MOD(T1."FECHA",100) BETWEEN 0 AND months	
	-- AND T1.MIS NOT IN ('AutoSummit','Master Lease', 'Agave')
	AND T1."LINEA" NOT IN ('191001680030') -- PRESENTA ERROR DE DUPLICIDAD EN FEB2014
	AND T2."CLASS15" IN ('Negocios','Empresarial');
	
	
END;$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100
  ROWS 1000;
ALTER FUNCTION cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION"(integer, integer, integer)
  OWNER TO postgres;







CREATE OR REPLACE FUNCTION cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION_"( MONTHS INTEGER, initial_month INTEGER, final_month INTEGER )
RETURNS TABLE("LLAVE_UNIVERSAL" CHARACTER VARYING, "FECHA" INTEGER, "SALDO" DOUBLE PRECISION, "CARTERA_VENCIDA" DOUBLE PRECISION, "RANGO_DA" CHARACTER VARYING, "EMPRESARIAL_NEXT" INTEGER) AS
$BODY$
DECLARE
BEGIN

RETURN QUERY SELECT
	T."LLAVE_UNIVERSAL",
	T."FECHA",
	T."SALDO",
	T."CARTERA_VENCIDA",
	MAX(T."RANGO_DA")::VARCHAR AS "RANGO_DA",
	MAX(T."EMPRESARIAL_NEXT") AS "EMPRESARIAL_NEXT"
FROM
	cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION"( MONTHS, initial_month, final_month ) T
GROUP BY T."LLAVE_UNIVERSAL", T."FECHA", T."SALDO", T."CARTERA_VENCIDA";
	
END;$BODY$
LANGUAGE plpgsql


update cartera."Tbl_CarteraCrediticia" 
set "FECHA_DATE" = TO_DATE(CONCAT("FECHA"::VARCHAR,'01'),'YYYYMMDD') 
where "FECHA_DATE" IS NULL AND "FECHA" IS NOT NULL; 


--  
SELECT
	T0."LLAVE_UNIVERSAL",
	T0."FECHA",
	T0."SALDO",
	T0."CARTERA_VENCIDA",
	T0."RANGO_DA" AS "RANGO_DA00",
	T1."RANGO_DA" AS "RANGO_DA01",
	T2."RANGO_DA" AS "RANGO_DA02",
	T3."RANGO_DA" AS "RANGO_DA03",
	T4."RANGO_DA" AS "RANGO_DA04",
	T5."RANGO_DA" AS "RANGO_DA05",
	T6."RANGO_DA" AS "RANGO_DA06",
	T6."EMPRESARIAL_NEXT" AS "EMP_6MESES"
INTO 
	cartera."Tbl_Transition"
FROM 
	cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION_"(0, 201611, 201705) T0
JOIN
	cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION_"(1, 201611, 201705) T1
ON 
	T0."LLAVE_UNIVERSAL" = T1."LLAVE_UNIVERSAL" AND T0."FECHA" = T1."FECHA"  
JOIN
	cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION_"(2, 201611, 201705) T2
ON 
	T0."LLAVE_UNIVERSAL" = T2."LLAVE_UNIVERSAL" AND T0."FECHA" = T2."FECHA"
JOIN
	cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION_"(3, 201611, 201705) T3
ON 
	T0."LLAVE_UNIVERSAL" = T3."LLAVE_UNIVERSAL" AND T0."FECHA" = T3."FECHA"
JOIN
	cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION_"(4, 201611, 201705) T4
ON 
	T0."LLAVE_UNIVERSAL" = T4."LLAVE_UNIVERSAL" AND T0."FECHA" = T4."FECHA"
JOIN
	cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION_"(5, 201611, 201705) T5
ON 
	T0."LLAVE_UNIVERSAL" = T5."LLAVE_UNIVERSAL" AND T0."FECHA" = T5."FECHA"
JOIN
	cartera."JAE_FUNCTION_MCV_ROLL_RATE_CLASIFICACION_"(6, 201611, 201705) T6
ON 
	T0."LLAVE_UNIVERSAL" = T6."LLAVE_UNIVERSAL" AND T0."FECHA" = T6."FECHA"
-- WHERE
--	T0."LLAVE_UNIVERSAL" = '0000000000008104185002701'
-- ORDER BY "FECHA"






-- NEGOCIOS -> EMPRESARIAL -> NEGOCIOS
-- (6, 201312, 201405)
-- WHERE "LLAVE_UNIVERSAL" = '0000000000000000003944701'


------------
SELECT
T3.RANGO_DA00,
	
	CASE
		WHEN T3.RANGO_DA01 IS NULL THEN
			CASE
				-- AND T2."FECHA_DATE" BETWEEN TO_DATE(initial_month::VARCHAR, 'YYYYMM') AND TO_DATE(final_month::VARCHAR, 'YYYYMM') + INTERVAL'1 MONTH'*MONTHS
				-- TO_DATE(final_month::VARCHAR, 'YYYYMM') + INTERVAL'1 MONTH'*MONTHS
				-- WHEN TIMESTAMPADD(MONTH,1,STR_TO_DATE(CONCAT(T3.FECHA,'01'),'%Y%m%d')) > STR_TO_DATE(CONCAT(@FECHA_MAX,'01'),'%Y%m%d') THEN NULL
				WHEN (FLOOR(T4.FECHA_CASTIGO/100) - FLOOR(T3.FECHA/100))*12 + MOD(T4.FECHA_CASTIGO, 100) - MOD(T3.FECHA, 100) <= 1 THEN '99: CASTIGO'
				ELSE '98: LIQUIDA'
			END
		ELSE RANGO_DA01
	END AS RANGO_DA01,
		
	CASE
		WHEN T3.RANGO_DA02 IS NULL THEN
			CASE
				WHEN TIMESTAMPADD(MONTH,2,STR_TO_DATE(CONCAT(T3.FECHA,'01'),'%Y%m%d')) > STR_TO_DATE(CONCAT(@FECHA_MAX,'01'),'%Y%m%d') THEN NULL
				WHEN (FLOOR(T4.FECHA_CASTIGO/100) - FLOOR(T3.FECHA/100))*12 + MOD(T4.FECHA_CASTIGO, 100) - MOD(T3.FECHA, 100) <= 2 THEN '99: CASTIGO'
				ELSE '98: LIQUIDA'
			END
		ELSE RANGO_DA02
	END AS RANGO_DA02,
	COUNT(*) AS REGISTROS,
	ROUND(SUM(SALDO),2) AS SALDO,
	ROUND(SUM(CARTERA_VENCIDA),2) AS CARTERA_VENCIDA
FROM
	cartera.""
JOIN
	cartera."JAE_VIEW_MCV_CASTIGOS"



UPDATE cartera."Tbl_CarteraCrediticia"
SET "MESESDC" = (2014)*12 + 1
-- SET "MESESDC" = (FLOOR("FECHA"/100)*12 + MOD("FECHA", 100))
WHERE "FECHA" = 201401



