--  Lorena García González
--  Agosto 08, 2018
--  MCV: Creación de Variables - Saldo .

USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_BAL ;

CREATE TABLE IF NOT EXISTS LGG_MCV_BAL AS 
SELECT 
	LLAVE_UNIVERSAL_20,RFC, CLIENTE, LINEA,FECHA AS FECHACARTERA,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))) AS FECHA_TOPE_03M, 
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))) AS FECHA_TOPE_06M,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))) AS FECHA_TOPE_12M
	
FROM 
	DBMYMWORK.JEA_MCV_UNIVERSO
;

ALTER TABLE LGG_MCV_BAL ADD INDEX LLAVE(LLAVE_UNIVERSAL_20);
ALTER TABLE LGG_MCV_BAL ADD INDEX LLAVE1(CLIENTE);
ALTER TABLE LGG_MCV_BAL ADD INDEX LLAVE2(LINEA);
ALTER TABLE LGG_MCV_BAL ADD INDEX LLAVE3(RFC);

--  PERIODO 3 MESES
ALTER TABLE LGG_MCV_BAL 
	ADD COLUMN CUR_BAL               DOUBLE NULL,
	ADD COLUMN MAX_BAL_03M           DOUBLE NULL ,
    ADD COLUMN MIN_BAL_03M           DOUBLE NULL ,
    ADD COLUMN AVG_PND_MENOS_BAL_03M DOUBLE NULL ,
    ADD COLUMN AVG_PND_MAS_BAL_03M   DOUBLE NULL ,
    ADD COLUMN AVG_BAL_03M           DOUBLE NULL ;
	
UPDATE 	
	LGG_MCV_BAL T1 
SET T1.CUR_BAL= (SELECT T2.SALDO
					FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
					WHERE T2.FECHA = T1.FECHACARTERA
					AND T1.RFC = T2.RFC), 
	T1.MAX_BAL_03M = (SELECT MAX(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.MIN_BAL_03M = (SELECT MIN(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),       
    T1.AVG_BAL_03M = (SELECT AVG(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_BAL_03M = (SELECT SUM(SALDO * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_BAL_03M = (SELECT SUM(SALDO * (4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC);      


									
--  PERIODO 6 MESES
ALTER TABLE LGG_MCV_BAL 
	ADD COLUMN MAX_BAL_06M           DOUBLE NULL ,
    ADD COLUMN MIN_BAL_06M           DOUBLE NULL ,
    ADD COLUMN AVG_PND_MENOS_BAL_06M DOUBLE NULL ,
    ADD COLUMN AVG_PND_MAS_BAL_06M   DOUBLE NULL ,
    ADD COLUMN AVG_BAL_06M           DOUBLE NULL ;
	
UPDATE 	
	LGG_MCV_BAL T1 
SET 	T1.MAX_BAL_06M = (SELECT MAX(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.MIN_BAL_06M = (SELECT MIN(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),       
    T1.AVG_BAL_06M = (SELECT AVG(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_BAL_06M = (SELECT SUM(SALDO * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_BAL_06M = (SELECT SUM(SALDO * (7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC);  
									
--  PERIODO 12 MESES
ALTER TABLE LGG_MCV_BAL 
	ADD COLUMN MAX_BAL_12M           DOUBLE NULL ,
    ADD COLUMN MIN_BAL_12M           DOUBLE NULL ,
    ADD COLUMN AVG_PND_MENOS_BAL_12M DOUBLE NULL ,
    ADD COLUMN AVG_PND_MAS_BAL_12M   DOUBLE NULL ,
    ADD COLUMN AVG_BAL_12M           DOUBLE NULL ;
	
UPDATE 	
	LGG_MCV_BAL T1 
SET T1.MAX_BAL_12M = (SELECT MAX(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.MIN_BAL_12M = (SELECT MIN(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),       
    T1.AVG_BAL_12M = (SELECT AVG(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_BAL_12M = (SELECT SUM(SALDO * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_BAL_12M = (SELECT SUM(SALDO * (13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC);  									