--  Lorena García González
--  Agosto 09, 2018
--  MCV: Creación de Variables - Edad de la linea meses 


USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_MOV_LIN;
CREATE TABLE IF NOT EXISTS LGG_MCV_MOV_LIN AS 
SELECT 
	LLAVE_UNIVERSAL_20,RFC, CLIENTE, LINEA,FECHA AS FECHACARTERA,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))) AS FECHA_TOPE_03M, 
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))) AS FECHA_TOPE_06M,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))) AS FECHA_TOPE_12M
FROM 
	DBMYMWORK.JEA_MCV_UNIVERSO;
	
ALTER TABLE LGG_MCV_MOV_LIN ADD INDEX LLAVE(RFC);
ALTER TABLE LGG_MCV_MOV_LIN ADD INDEX LLAVE1(CLIENTE);
ALTER TABLE LGG_MCV_MOV_LIN ADD INDEX LLAVE2(LINEA);
ALTER TABLE LGG_MCV_MOV_LIN ADD INDEX LLAVE3(LLAVE_UNIVERSAL_20);	

--  CREAMOS LA COLUMNA DE MESES DESDE LA APERTURA
ALTER TABLE LGG_MCV_MOV_LIN 
	ADD COLUMN MS_OP INT;

--  ACTUALIZAMOS LA COLUMNA				
UPDATE LGG_MCV_MOV_LIN T1
INNER JOIN 	(SELECT LINEAORIGINAL, CONCAT(YEAR(FECHACAMBIO)*100+MONTH(FECHACAMBIO)) AS FECHAAPERTURA
						FROM  DBMYMWORK.JEA_MCV_MOVIMIENTO_LINEAS 
							WHERE TIPOMOVIMIENTO = 'Apertura') T2			
ON T1.LINEA = T2.LINEAORIGINAL
SET T1.MS_OP = (FLOOR(T1.FECHACARTERA/100) - FLOOR(T2.FECHAAPERTURA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHAAPERTURA,100);

--  ACTUALIZAMOS LOS NULOS QUE NOS QUEDAN  Y LA INFORMACION LA OBTENEMOS DE LA TABLA DE MOVIMIENTOS DE LINEA DE DATAMART.
			
UPDATE LGG_MCV_MOV_LIN T1
INNER JOIN 	(SELECT LINEAORIGINAL, CONCAT(YEAR(FECHACAMBIO)*100+MONTH(FECHACAMBIO)) AS FECHAAPERTURA
						FROM  DBRSKDATAMART.Tbl_MovimientoLineas 
							WHERE TIPOMOVIMIENTO = 'Apertura') T2						
ON T1.LINEA = T2.LINEAORIGINAL
SET T1.MS_OP = (FLOOR(T1.FECHACARTERA/100) - FLOOR(T2.FECHAAPERTURA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHAAPERTURA,100)
 WHERE MS_OP IS NULL;	

--  AGREGAMOS EL DIA DE LA SEMANA QUE CORRESPONDE A ESA FECHA
ALTER TABLE LGG_MCV_MOV_LIN	
	ADD COLUMN DIACARTERA VARCHAR(2),
	ADD COLUMN FECHA_LASTCARTERA DATE ;

ALTER TABLE LGG_MCV_MOV_LIN ADD INDEX LLAVE5(FECHA_LASTCARTERA);	

UPDATE LGG_MCV_MOV_LIN T1	
	SET DIACARTERA =  WEEKDAY(DATE_ADD(DATE_ADD(STR_TO_DATE(CONCAT(T1.FECHACARTERA,'01'),'%Y%m%d'),INTERVAL 1 MONTH),INTERVAL -1 DAY)),
		FECHA_LASTCARTERA = DATE_ADD(DATE_ADD(STR_TO_DATE(CONCAT(T1.FECHACARTERA,'01'),'%Y%m%d'),INTERVAL 1 MONTH),INTERVAL -1 DAY);
	
UPDATE 	LGG_MCV_MOV_LIN T1 
SET T1.DIACARTERA = CASE 
					WHEN DIACARTERA = 0 THEN 'L'
					WHEN DIACARTERA = 1 THEN 'MA'
                    WHEN DIACARTERA = 2 THEN 'MI'
                    WHEN DIACARTERA = 3 THEN 'J'
                    WHEN DIACARTERA = 4 THEN 'V'
                    WHEN DIACARTERA = 5 THEN 'S'
				    WHEN DIACARTERA = 6 THEN 'D'
					END;

--  AGREGAMOS LA FECHA VENCIMIENTO GENERAL
ALTER TABLE LGG_MCV_MOV_LIN ADD COLUMN FECHAVENCIMIENTOACTUAL_GNRL DATE;

UPDATE 	LGG_MCV_MOV_LIN T6
INNER JOIN (SELECT  LINEA, FECHACARTERA,FECHA_LASTCARTERA,
			 (SELECT FECHAVENCIMIENTODESPUES FROM JEA_MCV_MOVIMIENTO_LINEAS WHERE
			 ID_MOVIMIENTOLIN = (SELECT MAX(ID_MOVIMIENTOLIN) FROM JEA_MCV_MOVIMIENTO_LINEAS T2 WHERE T1.LINEA = T2.LINEAORIGINAL AND FECHACAMBIO <= FECHA_LASTCARTERA)) AS FECHAVENCIMIENTOACTUAL_GNRL
			 FROM 	LGG_MCV_MOV_LIN	T1)	T7
	ON T6.LINEA = T7.LINEA AND T6.FECHA_LASTCARTERA = T7.FECHA_LASTCARTERA
	SET T6.FECHAVENCIMIENTOACTUAL_GNRL = T7.FECHAVENCIMIENTOACTUAL_GNRL;

	UPDATE 	LGG_MCV_MOV_LIN T6
INNER JOIN (SELECT  LINEA, FECHACARTERA,FECHA_LASTCARTERA,
			 (SELECT FECHAVENCIMIENTODESPUES FROM DBRSKDATAMART.Tbl_MovimientoLineas WHERE
			 ID_MOVIMIENTOLIN = (SELECT MAX(ID_MOVIMIENTOLIN) FROM DBRSKDATAMART.Tbl_MovimientoLineas T2 WHERE T1.LINEA = T2.LINEAORIGINAL AND FECHACAMBIO <= FECHA_LASTCARTERA)) AS FECHAVENCIMIENTOACTUAL_GNRL
			 FROM 	LGG_MCV_MOV_LIN	T1)	T7
	ON T6.LINEA = T7.LINEA AND T6.FECHA_LASTCARTERA = T7.FECHA_LASTCARTERA
	SET T6.FECHAVENCIMIENTOACTUAL_GNRL = T7.FECHAVENCIMIENTOACTUAL_GNRL
	WHERE T6.FECHAVENCIMIENTOACTUAL_GNRL IS NULL;
	

--  VARIABLE : DS_CL
ALTER TABLE LGG_MCV_MOV_LIN	ADD COLUMN DS_CL DOUBLE;

UPDATE 	LGG_MCV_MOV_LIN T1 
SET T1.DS_CL = (SELECT   TIMESTAMPDIFF(DAY,T1.FECHA_LASTCARTERA,T1.FECHAVENCIMIENTOACTUAL_GNRL)+ IF (T1.DIACARTERA = 'S',1 , IF(T1.DIACARTERA = 'D',2 ,0))
					FROM(SELECT T3.LINEAORIGINAL,CONCAT(YEAR(T3.FECHACAMBIO)*100+MONTH(T3.FECHACAMBIO)) AS FECHACAMBIO, T4.ID_MOVIMIENTOLIN
							FROM JEA_MCV_MOVIMIENTO_LINEAS T3
								INNER JOIN (SELECT LINEAORIGINAL,MAX(ID_MOVIMIENTOLIN) AS ID_MOVIMIENTOLIN FROM JEA_MCV_MOVIMIENTO_LINEAS GROUP BY 1) T4
									ON T4.ID_MOVIMIENTOLIN = T3.ID_MOVIMIENTOLIN) T2
				WHERE T1.LINEA = T2.LINEAORIGINAL );

--  ACTUALIZAMOS
UPDATE 	LGG_MCV_MOV_LIN T1 
SET T1.DS_CL = (SELECT   TIMESTAMPDIFF(DAY,T1.FECHA_LASTCARTERA,T1.FECHAVENCIMIENTOACTUAL_GNRL)+ IF (T1.DIACARTERA = 'S',1 , IF(T1.DIACARTERA = 'D',2 ,0))
					FROM(SELECT T3.LINEAORIGINAL,CONCAT(YEAR(T3.FECHACAMBIO)*100+MONTH(T3.FECHACAMBIO)) AS FECHACAMBIO, T4.ID_MOVIMIENTOLIN
							FROM DBRSKDATAMART.Tbl_MovimientoLineas T3
								INNER JOIN (SELECT LINEAORIGINAL,MAX(ID_MOVIMIENTOLIN) AS ID_MOVIMIENTOLIN FROM  DBRSKDATAMART.Tbl_MovimientoLineas GROUP BY 1) T4
									ON T4.ID_MOVIMIENTOLIN = T3.ID_MOVIMIENTOLIN) T2
				WHERE T1.LINEA = T2.LINEAORIGINAL )
	WHERE DS_CL IS NULL ;




				
--  AGREGAMOS LA FECHA VENCIMIENTO ORIGINACION (APERTURA)				
ALTER TABLE LGG_MCV_MOV_LIN 
ADD COLUMN FECHAVENCIMIENTOACTUAL_OR DATE,
ADD COLUMN FECHAAPERTURA DATE;

UPDATE LGG_MCV_MOV_LIN T1 
INNER JOIN (SELECT LINEAORIGINAL, FECHACAMBIO FROM JEA_MCV_MOVIMIENTO_LINEAS WHERE TIPOMOVIMIENTO = 'Apertura' )T2 
ON T1.LINEA =  T2.LINEAORIGINAL 
SET T1.FECHAAPERTURA = T2.FECHACAMBIO;

UPDATE LGG_MCV_MOV_LIN T1 
INNER JOIN (SELECT LINEAORIGINAL, FECHACAMBIO FROM DBRSKDATAMART.Tbl_MovimientoLineas WHERE TIPOMOVIMIENTO = 'Apertura' )T2 
ON T1.LINEA =  T2.LINEAORIGINAL 
SET T1.FECHAAPERTURA = T2.FECHACAMBIO
WHERE T1.FECHAAPERTURA IS NULL ;
							

UPDATE 	LGG_MCV_MOV_LIN T6
INNER JOIN (SELECT  LINEA, FECHACARTERA,FECHA_LASTCARTERA,
			 (SELECT FECHAVENCIMIENTODESPUES FROM JEA_MCV_MOVIMIENTO_LINEAS WHERE TIPOMOVIMIENTO = 'Apertura' AND 
			 ID_MOVIMIENTOLIN = (SELECT MAX(ID_MOVIMIENTOLIN) FROM JEA_MCV_MOVIMIENTO_LINEAS T2 WHERE T1.LINEA = T2.LINEAORIGINAL AND FECHACAMBIO <= FECHA_LASTCARTERA AND TIPOMOVIMIENTO = 'Apertura')) AS FECHAVENCIMIENTOACTUAL_OR
			 FROM 	LGG_MCV_MOV_LIN	T1)	T7
	ON T6.LINEA = T7.LINEA AND T6.FECHA_LASTCARTERA = T7.FECHA_LASTCARTERA
	SET T6.FECHAVENCIMIENTOACTUAL_OR = T7.FECHAVENCIMIENTOACTUAL_OR;

UPDATE 	LGG_MCV_MOV_LIN T6
INNER JOIN (SELECT  LINEA, FECHACARTERA,FECHA_LASTCARTERA,
			 (SELECT FECHAVENCIMIENTODESPUES FROM  DBRSKDATAMART.Tbl_MovimientoLineas WHERE TIPOMOVIMIENTO = 'Apertura' AND 
			 ID_MOVIMIENTOLIN = (SELECT MAX(ID_MOVIMIENTOLIN) FROM  DBRSKDATAMART.Tbl_MovimientoLineas T2 WHERE T1.LINEA = T2.LINEAORIGINAL AND FECHACAMBIO <= FECHA_LASTCARTERA AND TIPOMOVIMIENTO = 'Apertura')) AS FECHAVENCIMIENTOACTUAL_OR
			 FROM 	LGG_MCV_MOV_LIN	T1)	T7
	ON T6.LINEA = T7.LINEA AND T6.FECHA_LASTCARTERA = T7.FECHA_LASTCARTERA
	SET T6.FECHAVENCIMIENTOACTUAL_OR = T7.FECHAVENCIMIENTOACTUAL_OR
	WHERE T6.FECHAVENCIMIENTOACTUAL_OR IS NULL;	
	
ALTER TABLE LGG_MCV_MOV_LIN ADD COLUMN FECHAVENCIMIENTOACTUAL_OR DATE;	

--  VARIABLE : DS_OL_CL
ALTER TABLE LGG_MCV_MOV_LIN	ADD COLUMN DS_OL_CL DOUBLE;

UPDATE 	LGG_MCV_MOV_LIN T1 
SET T1.DS_OL_CL = (SELECT   TIMESTAMPDIFF(DAY,T1.FECHAAPERTURA,T1.FECHAVENCIMIENTOACTUAL_OR)+ IF (T1.DIACARTERA = 'S',1 , IF(T1.DIACARTERA = 'D',2 ,0))
					FROM(SELECT T3.LINEAORIGINAL,CONCAT(YEAR(T3.FECHACAMBIO)*100+MONTH(T3.FECHACAMBIO)) AS FECHACAMBIO, T4.ID_MOVIMIENTOLIN
							FROM JEA_MCV_MOVIMIENTO_LINEAS T3
								INNER JOIN (SELECT LINEAORIGINAL,MAX(ID_MOVIMIENTOLIN) AS ID_MOVIMIENTOLIN FROM JEA_MCV_MOVIMIENTO_LINEAS GROUP BY 1) T4
									ON T4.ID_MOVIMIENTOLIN = T3.ID_MOVIMIENTOLIN) T2
				WHERE T1.LINEA = T2.LINEAORIGINAL );			
				
UPDATE 	LGG_MCV_MOV_LIN T1 
SET T1.DS_OL_CL = (SELECT   TIMESTAMPDIFF(DAY,T1.FECHAAPERTURA,T1.FECHAVENCIMIENTOACTUAL_OR)+ IF (T1.DIACARTERA = 'S',1 , IF(T1.DIACARTERA = 'D',2 ,0))
					FROM(SELECT T3.LINEAORIGINAL,CONCAT(YEAR(T3.FECHACAMBIO)*100+MONTH(T3.FECHACAMBIO)) AS FECHACAMBIO, T4.ID_MOVIMIENTOLIN
							FROM DBRSKDATAMART.Tbl_MovimientoLineas T3
								INNER JOIN (SELECT LINEAORIGINAL,MAX(ID_MOVIMIENTOLIN) AS ID_MOVIMIENTOLIN FROM DBRSKDATAMART.Tbl_MovimientoLineas GROUP BY 1) T4
									ON T4.ID_MOVIMIENTOLIN = T3.ID_MOVIMIENTOLIN) T2
				WHERE T1.LINEA = T2.LINEAORIGINAL )
	WHERE  DS_OL_CL IS NULL ;					

-- LAS FECHAS DE VENCIMIENTO QUE SON IGUALES A 	1900-01-01 SE PONEN NULO EN DS_CL Y DS_OL_CL

UPDATE LGG_MCV_MOV_LIN T1
SET DS_CL = NULL,
    DS_OL_CL = NULL
WHERE FECHAVENCIMIENTOACTUAL_OR = 	'1900-01-01';



