--  Lorena García González
--  Agosto 09, 2018
--  MCV: Creación de Variables - Razón entre saldo actual y máximo de los últimos N meses 

USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_R_BAL_BY_MAX_BAL;

CREATE TABLE IF NOT EXISTS LGG_MCV_R_BAL_BY_MAX_BAL AS 
SELECT 
	LLAVE_UNIVERSAL_20,RFC, CLIENTE, LINEA,FECHA AS FECHACARTERA,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))) AS FECHA_TOPE_03M, 
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))) AS FECHA_TOPE_06M,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))) AS FECHA_TOPE_12M
FROM 
	DBMYMWORK.JEA_MCV_UNIVERSO;

ALTER TABLE LGG_MCV_R_BAL_BY_MAX_BAL ADD INDEX LLAVE(RFC);
ALTER TABLE LGG_MCV_R_BAL_BY_MAX_BAL ADD INDEX LLAVE1(CLIENTE);
ALTER TABLE LGG_MCV_R_BAL_BY_MAX_BAL ADD INDEX LLAVE2(LINEA);
ALTER TABLE LGG_MCV_R_BAL_BY_MAX_BAL ADD INDEX LLAVE3(LLAVE_UNIVERSAL_20);	

	
--  PERIODO 3 MESES
ALTER TABLE LGG_MCV_R_BAL_BY_MAX_BAL
	ADD COLUMN R_BAL_BY_MAX_BAL                   DOUBLE, 
	ADD COLUMN MAX_R_BAL_BY_MAX_BAL_03M           DOUBLE,
	ADD COLUMN MIN_R_BAL_BY_MAX_BAL_03M           DOUBLE,
	ADD COLUMN AVG_PND_MENOS_R_BAL_BY_MAX_BAL_03M DOUBLE,
	ADD COLUMN AVG_PND_MAS_R_BAL_BY_MAX_BAL_03M   DOUBLE,
	ADD COLUMN AVG_R_BAL_BY_MAX_BAL_03M           DOUBLE;
	
UPDATE LGG_MCV_R_BAL_BY_MAX_BAL T1 
SET T1.R_BAL_BY_MAX_BAL = (SELECT R_BAL_BY_MAX_BAL
								FROM (SELECT LLAVE_UNIVERSAL_20,FECHACARTERA,IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL ) AS T2
									WHERE T2.LLAVE_UNIVERSAL_20 = T1.LLAVE_UNIVERSAL_20 AND T1.FECHACARTERA = T2.FECHACARTERA),
	T1.MAX_R_BAL_BY_MAX_BAL_03M = (SELECT MAX(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE  T2.FECHACARTERA >= T1.FECHA_TOPE_03M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20) ,        	
    T1.MIN_R_BAL_BY_MAX_BAL_03M = (SELECT MIN(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_03M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),       
    T1.AVG_R_BAL_BY_MAX_BAL_03M = (SELECT AVG(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M))AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_03M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),
    T1.AVG_PND_MENOS_R_BAL_BY_MAX_BAL_03M = (SELECT SUM(R_BAL_BY_MAX_BAL * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100)+1))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_03M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100)+1)
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M))AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_03M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.AVG_PND_MAS_R_BAL_BY_MAX_BAL_03M = (SELECT SUM(R_BAL_BY_MAX_BAL * (4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100))))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_03M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
											(SELECT SUM((4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100))))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_03M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20);      									
--  PERIODO 6 MESES
ALTER TABLE LGG_MCV_R_BAL_BY_MAX_BAL
	ADD COLUMN MAX_R_BAL_BY_MAX_BAL_06M           DOUBLE,
	ADD COLUMN MIN_R_BAL_BY_MAX_BAL_06M           DOUBLE,
	ADD COLUMN AVG_PND_MENOS_R_BAL_BY_MAX_BAL_06M DOUBLE,
	ADD COLUMN AVG_PND_MAS_R_BAL_BY_MAX_BAL_06M   DOUBLE,
	ADD COLUMN AVG_R_BAL_BY_MAX_BAL_06M           DOUBLE;
	
UPDATE LGG_MCV_R_BAL_BY_MAX_BAL T1 
SET T1.MAX_R_BAL_BY_MAX_BAL_06M = (SELECT MAX(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_06M = 0 ,0,(CUR_BAL / MAX_BAL_06M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE  T2.FECHACARTERA >= T1.FECHA_TOPE_06M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20) ,        	
    T1.MIN_R_BAL_BY_MAX_BAL_06M = (SELECT MIN(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_06M = 0 ,0,(CUR_BAL / MAX_BAL_06M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_06M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),       
    T1.AVG_R_BAL_BY_MAX_BAL_06M = (SELECT AVG(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_06M = 0 ,0,(CUR_BAL / MAX_BAL_06M))AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_06M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),
    T1.AVG_PND_MENOS_R_BAL_BY_MAX_BAL_06M = (SELECT SUM(R_BAL_BY_MAX_BAL * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100)+1))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_06M = 0 ,0,(CUR_BAL / MAX_BAL_06M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_06M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100)+1)
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_06M = 0 ,0,(CUR_BAL / MAX_BAL_06M))AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_06M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.AVG_PND_MAS_R_BAL_BY_MAX_BAL_06M = (SELECT SUM(R_BAL_BY_MAX_BAL * (7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100))))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_06M = 0 ,0,(CUR_BAL / MAX_BAL_06M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_06M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
											(SELECT SUM((7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100))))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_06M = 0 ,0,(CUR_BAL / MAX_BAL_06M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_06M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20);      									
		
	
--  PERIODO 12 MESES
ALTER TABLE LGG_MCV_R_BAL_BY_MAX_BAL
	ADD COLUMN MAX_R_BAL_BY_MAX_BAL_12M           DOUBLE,
	ADD COLUMN MIN_R_BAL_BY_MAX_BAL_12M           DOUBLE,
	ADD COLUMN AVG_PND_MENOS_R_BAL_BY_MAX_BAL_12M DOUBLE,
	ADD COLUMN AVG_PND_MAS_R_BAL_BY_MAX_BAL_12M   DOUBLE,
	ADD COLUMN AVG_R_BAL_BY_MAX_BAL_12M           DOUBLE;
	
UPDATE LGG_MCV_R_BAL_BY_MAX_BAL T1 
SET T1.MAX_R_BAL_BY_MAX_BAL_12M = (SELECT MAX(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE  T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20) ,        	
    T1.MIN_R_BAL_BY_MAX_BAL_12M = (SELECT MIN(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),       
    T1.AVG_R_BAL_BY_MAX_BAL_12M = (SELECT AVG(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M))AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),
    T1.AVG_PND_MENOS_R_BAL_BY_MAX_BAL_12M = (SELECT SUM(R_BAL_BY_MAX_BAL * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100)+1))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100)+1)
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M))AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.AVG_PND_MAS_R_BAL_BY_MAX_BAL_12M = (SELECT SUM(R_BAL_BY_MAX_BAL * (13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100))))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
											(SELECT SUM((13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100))))
												FROM (SELECT  LLAVE_UNIVERSAL_20,FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20);      									
		
	
	
	
