--  Lorena García González
--  Agosto 08, 2018
--  MCV: Creación de Variables - Razón entre el saldo y el monto de la linea 

USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_R_BAL_BY_CRED_LIM ; 

CREATE TABLE IF NOT EXISTS LGG_MCV_R_BAL_BY_CRED_LIM AS 
SELECT 
	LLAVE_UNIVERSAL_20,RFC, CLIENTE, LINEA,FECHA AS FECHACARTERA,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))) AS FECHA_TOPE_03M, 
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))) AS FECHA_TOPE_06M,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))) AS FECHA_TOPE_12M
FROM 
	DBMYMWORK.JEA_MCV_UNIVERSO
;

ALTER TABLE LGG_MCV_R_BAL_BY_CRED_LIM ADD INDEX LLAVE(RFC);
ALTER TABLE LGG_MCV_R_BAL_BY_CRED_LIM ADD INDEX LLAVE1(CLIENTE);
ALTER TABLE LGG_MCV_R_BAL_BY_CRED_LIM ADD INDEX LLAVE2(LINEA);
ALTER TABLE LGG_MCV_R_BAL_BY_CRED_LIM ADD INDEX LLAVE3(LLAVE_UNIVERSAL_20);

--  PERIODO 3 MESES
ALTER TABLE LGG_MCV_R_BAL_BY_CRED_LIM 
	ADD COLUMN R_BAL_BY_CRED_LIM                  DOUBLE NULL,
	ADD COLUMN MAX_R_BAL_BY_CRED_LIM_03M           DOUBLE NULL ,
    ADD COLUMN MIN_R_BAL_BY_CRED_LIM_03M           DOUBLE NULL ,
    ADD COLUMN AVG_PND_MENOS_R_BAL_BY_CRED_LIM_03M DOUBLE NULL ,
    ADD COLUMN AVG_PND_MAS_R_BAL_BY_CRED_LIM_03M   DOUBLE NULL ,
    ADD COLUMN AVG_R_BAL_BY_CRED_LIM_03M           DOUBLE NULL ;
	
UPDATE 	
	LGG_MCV_R_BAL_BY_CRED_LIM T1 
SET T1.R_BAL_BY_CRED_LIM = (SELECT MAX(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA = T1.FECHACARTERA
									AND T1.RFC = T2.RFC) , 
	T1.MAX_R_BAL_BY_CRED_LIM_03M = (SELECT MAX(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.MIN_R_BAL_BY_CRED_LIM_03M = (SELECT MIN(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),       
    T1.AVG_R_BAL_BY_CRED_LIM_03M = (SELECT AVG(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_R_BAL_BY_CRED_LIM_03M = (SELECT SUM((SALDO/MONTO_LINEA) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_R_BAL_BY_CRED_LIM_03M = (SELECT SUM((SALDO/MONTO_LINEA) * (4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM(SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)  AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC);      

--  PERIODO 6 MESES
ALTER TABLE LGG_MCV_R_BAL_BY_CRED_LIM 
	ADD COLUMN MAX_R_BAL_BY_CRED_LIM_06M           DOUBLE NULL ,
    ADD COLUMN MIN_R_BAL_BY_CRED_LIM_06M           DOUBLE NULL ,
    ADD COLUMN AVG_PND_MENOS_R_BAL_BY_CRED_LIM_06M DOUBLE NULL ,
    ADD COLUMN AVG_PND_MAS_R_BAL_BY_CRED_LIM_06M   DOUBLE NULL ,
    ADD COLUMN AVG_R_BAL_BY_CRED_LIM_06M           DOUBLE NULL ;
	
UPDATE 	
	LGG_MCV_R_BAL_BY_CRED_LIM T1 
SET T1.MAX_R_BAL_BY_CRED_LIM_06M = (SELECT MAX(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.MIN_R_BAL_BY_CRED_LIM_06M = (SELECT MIN(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),       
    T1.AVG_R_BAL_BY_CRED_LIM_06M = (SELECT AVG(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_R_BAL_BY_CRED_LIM_06M = (SELECT SUM((SALDO/MONTO_LINEA) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_R_BAL_BY_CRED_LIM_06M = (SELECT SUM((SALDO/MONTO_LINEA) * (7 -((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM(SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)  AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((7 -((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC);      

--  PERIODO 12 MESES
ALTER TABLE LGG_MCV_R_BAL_BY_CRED_LIM 
	ADD COLUMN MAX_R_BAL_BY_CRED_LIM_12M           DOUBLE NULL ,
    ADD COLUMN MIN_R_BAL_BY_CRED_LIM_12M           DOUBLE NULL ,
    ADD COLUMN AVG_PND_MENOS_R_BAL_BY_CRED_LIM_12M DOUBLE NULL ,
    ADD COLUMN AVG_PND_MAS_R_BAL_BY_CRED_LIM_12M   DOUBLE NULL ,
    ADD COLUMN AVG_R_BAL_BY_CRED_LIM_12M           DOUBLE NULL ;
	
UPDATE 	
	LGG_MCV_R_BAL_BY_CRED_LIM T1 
SET T1.MAX_R_BAL_BY_CRED_LIM_12M = (SELECT MAX(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.MIN_R_BAL_BY_CRED_LIM_12M = (SELECT MIN(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),       
    T1.AVG_R_BAL_BY_CRED_LIM_12M = (SELECT AVG(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_R_BAL_BY_CRED_LIM_12M = (SELECT SUM((SALDO/MONTO_LINEA) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_R_BAL_BY_CRED_LIM_12M = (SELECT SUM((SALDO/MONTO_LINEA) * (13 -((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM(SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2)  AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((13 -((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC);      
									