--  Lorena García González
--  Agosto 09, 2018
--  MCV: Creación de Variables - Monto Disponible (Monto de Linea - Saldo de Linea)

USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_D_CRED_LIM_TO_BAL;

CREATE TABLE IF NOT EXISTS LGG_MCV_D_CRED_LIM_TO_BAL AS 
SELECT 
	LLAVE_UNIVERSAL_20,RFC, CLIENTE, LINEA,FECHA AS FECHACARTERA,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))) AS FECHA_TOPE_03M, 
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))) AS FECHA_TOPE_06M,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))) AS FECHA_TOPE_12M
FROM 
	DBMYMWORK.JEA_MCV_UNIVERSO;
	
ALTER TABLE LGG_MCV_D_CRED_LIM_TO_BAL ADD INDEX LLAVE(RFC);
ALTER TABLE LGG_MCV_D_CRED_LIM_TO_BAL ADD INDEX LLAVE1(CLIENTE);
ALTER TABLE LGG_MCV_D_CRED_LIM_TO_BAL ADD INDEX LLAVE2(LINEA);
ALTER TABLE LGG_MCV_D_CRED_LIM_TO_BAL ADD INDEX LLAVE3(LLAVE_UNIVERSAL_20);	

--  PERIODO 3 MESES
ALTER TABLE LGG_MCV_D_CRED_LIM_TO_BAL 
	ADD COLUMN D_CRED_LIM_TO_BAL                   DOUBLE, 
	ADD COLUMN MAX_D_CRED_LIM_TO_BAL_03M           DOUBLE,
	ADD COLUMN MIN_D_CRED_LIM_TO_BAL_03M           DOUBLE,
	ADD COLUMN AVG_PND_MENOS_D_CRED_LIM_TO_BAL_03M DOUBLE,
	ADD COLUMN AVG_PND_MAS_D_CRED_LIM_TO_BAL_03M   DOUBLE,
	ADD COLUMN AVG_D_CRED_LIM_TO_BAL_03M           DOUBLE;

UPDATE 	
	LGG_MCV_D_CRED_LIM_TO_BAL T1 
SET T1.D_CRED_LIM_TO_BAL = (SELECT MONTO_LINEA - SALDO
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA = T1.FECHACARTERA
										AND T1.RFC = T2.RFC),
	T1.MAX_D_CRED_LIM_TO_BAL_03M = (SELECT MAX(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE  T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC) ,        	
    T1.MIN_D_CRED_LIM_TO_BAL_03M = (SELECT MIN(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),       
    T1.AVG_D_CRED_LIM_TO_BAL_03M = (SELECT AVG(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_D_CRED_LIM_TO_BAL_03M = (SELECT SUM((MONTO_LINEA - SALDO) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_D_CRED_LIM_TO_BAL_03M = (SELECT SUM((MONTO_LINEA - SALDO) * (4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC);      


--  PERIODO 6 MESES
ALTER TABLE LGG_MCV_D_CRED_LIM_TO_BAL 
	ADD COLUMN MAX_D_CRED_LIM_TO_BAL_06M           DOUBLE,
	ADD COLUMN MIN_D_CRED_LIM_TO_BAL_06M           DOUBLE,
	ADD COLUMN AVG_PND_MENOS_D_CRED_LIM_TO_BAL_06M DOUBLE,
	ADD COLUMN AVG_PND_MAS_D_CRED_LIM_TO_BAL_06M   DOUBLE,
	ADD COLUMN AVG_D_CRED_LIM_TO_BAL_06M           DOUBLE;

UPDATE 	
	LGG_MCV_D_CRED_LIM_TO_BAL T1 
SET	T1.MAX_D_CRED_LIM_TO_BAL_06M = (SELECT MAX(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA = T1.FECHACARTERA
										AND T1.RFC = T2.RFC) ,        	
    T1.MIN_D_CRED_LIM_TO_BAL_06M = (SELECT MIN(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),       
    T1.AVG_D_CRED_LIM_TO_BAL_06M = (SELECT AVG(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_D_CRED_LIM_TO_BAL_06M = (SELECT SUM((MONTO_LINEA - SALDO) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_D_CRED_LIM_TO_BAL_06M = (SELECT SUM((MONTO_LINEA - SALDO) * (7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC);      

--  PERIODO 12 MESES
ALTER TABLE LGG_MCV_D_CRED_LIM_TO_BAL 
	ADD COLUMN MAX_D_CRED_LIM_TO_BAL_12M           DOUBLE,
	ADD COLUMN MIN_D_CRED_LIM_TO_BAL_12M           DOUBLE,
	ADD COLUMN AVG_PND_MENOS_D_CRED_LIM_TO_BAL_12M DOUBLE,
	ADD COLUMN AVG_PND_MAS_D_CRED_LIM_TO_BAL_12M   DOUBLE,
	ADD COLUMN AVG_D_CRED_LIM_TO_BAL_12M           DOUBLE;

UPDATE 	
	LGG_MCV_D_CRED_LIM_TO_BAL T1 
SET	T1.MAX_D_CRED_LIM_TO_BAL_12M = (SELECT MAX(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA = T1.FECHACARTERA
										AND T1.RFC = T2.RFC) ,        	
    T1.MIN_D_CRED_LIM_TO_BAL_12M = (SELECT MIN(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),       
    T1.AVG_D_CRED_LIM_TO_BAL_12M = (SELECT AVG(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),
    T1.AVG_PND_MENOS_D_CRED_LIM_TO_BAL_12M = (SELECT SUM((MONTO_LINEA - SALDO) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC),         	
    T1.AVG_PND_MAS_D_CRED_LIM_TO_BAL_12M = (SELECT SUM((MONTO_LINEA - SALDO) * (13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC);      










	