--  Lorena García González
--  Agosto 08, 2018
--  MCV: Creación de Variables - Monto de Crédtio de la linea.

USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_CRED_LIM ; -- CURRENT LINE AMOUNT

CREATE TABLE IF NOT EXISTS LGG_MCV_CRED_LIM AS 
SELECT 
	LLAVE_UNIVERSAL_20,RFC, CLIENTE, LINEA,FECHA AS FECHACARTERA,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))) AS FECHA_TOPE_03M, 
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))) AS FECHA_TOPE_06M,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))) AS FECHA_TOPE_12M,
	MONTO_LINEA AS CUR_CRED_LIM
FROM 
	DBMYMWORK.JEA_MCV_UNIVERSO
;

ALTER TABLE LGG_MCV_CRED_LIM ADD INDEX LLAVE(RFC);
ALTER TABLE LGG_MCV_CRED_LIM ADD INDEX LLAVE1(CLIENTE);
ALTER TABLE LGG_MCV_CRED_LIM ADD INDEX LLAVE2(LINEA);
ALTER TABLE LGG_MCV_CRED_LIM ADD INDEX LLAVE3(LLAVE_UNIVERSAL_20);

--  PERIODO 3 MESES
ALTER TABLE LGG_MCV_CRED_LIM 
	ADD COLUMN MAX_CRED_LIM_03M           DOUBLE NULL ,
    ADD COLUMN MIN_CRED_LIM_03M           DOUBLE NULL ,
    ADD COLUMN AVG_PND_MENOS_CRED_LIM_03M DOUBLE NULL ,
    ADD COLUMN AVG_PND_MAS_CRED_LIM_03M   DOUBLE NULL ,
    ADD COLUMN AVG_CRED_LIM_03M           DOUBLE NULL ;
	
UPDATE 	
	LGG_MCV_CRED_LIM T1 
SET T1.MAX_CRED_LIM_03M = (SELECT MAX(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.MIN_CRED_LIM_03M = (SELECT MIN(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),       
    T1.AVG_CRED_LIM_03M = (SELECT AVG(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),
    T1.AVG_PND_MENOS_CRED_LIM_03M = (SELECT SUM(MONTO_LINEA * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.AVG_PND_MAS_CRED_LIM_03M = (SELECT SUM(MONTO_LINEA * (4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
									(SELECT SUM((4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20);      


									
--  PERIODO 6 MESES
ALTER TABLE LGG_MCV_CRED_LIM 
	ADD COLUMN MAX_CRED_LIM_06M           DOUBLE ,
    ADD COLUMN MIN_CRED_LIM_06M           DOUBLE ,
    ADD COLUMN AVG_PND_MENOS_CRED_LIM_06M DOUBLE ,
    ADD COLUMN AVG_PND_MAS_CRED_LIM_06M   DOUBLE ,
    ADD COLUMN AVG_CRED_LIM_06M           DOUBLE ;
	
UPDATE 	
	LGG_MCV_CRED_LIM T1 
SET T1.MAX_CRED_LIM_06M = (SELECT MAX(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.MIN_CRED_LIM_06M = (SELECT MIN(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),       
    T1.AVG_CRED_LIM_06M = (SELECT AVG(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),
    T1.AVG_PND_MENOS_CRED_LIM_06M = (SELECT SUM(MONTO_LINEA * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.AVG_PND_MAS_CRED_LIM_06M = (SELECT SUM(MONTO_LINEA * (7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
									(SELECT SUM((7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20);      
 
	 
--  PERIODO 12 MESES
ALTER TABLE LGG_MCV_CRED_LIM 
	ADD COLUMN MAX_CRED_LIM_12M           DOUBLE ,
    ADD COLUMN MIN_CRED_LIM_12M           DOUBLE ,
    ADD COLUMN AVG_PND_MENOS_CRED_LIM_12M DOUBLE ,
    ADD COLUMN AVG_PND_MAS_CRED_LIM_12M   DOUBLE ,
    ADD COLUMN AVG_CRED_LIM_12M           DOUBLE ;
	
UPDATE 	
	LGG_MCV_CRED_LIM T1 
SET T1.MAX_CRED_LIM_12M = (SELECT MAX(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.MIN_CRED_LIM_12M = (SELECT MIN(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),       
    T1.AVG_CRED_LIM_12M = (SELECT AVG(MONTO_LINEA)
								FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),
    T1.AVG_PND_MENOS_CRED_LIM_12M = (SELECT SUM(MONTO_LINEA * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20),         	
    T1.AVG_PND_MAS_CRED_LIM_12M = (SELECT SUM(MONTO_LINEA * (13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20)/
									(SELECT SUM((13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20);    

									
