--  Lorena García González
--  Agosto 08, 2018
--  MCV: Creación de Variables - Saldo .

--  SET DE PRUEBA
DROP TABLE IF EXISTS LGG_MCV_SET_PRUEBA;
CREATE TABLE IF NOT EXISTS LGG_MCV_SET_PRUEBA AS
 SELECT RFC,FOLIO_BC AS FOLIO , FECHA, CLIENTE,LINEA FROM JAT_MCV_UNIVERSO_MODELADO2 WHERE  FECHA = '201805' LIMIT 500;



USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_PRUEBA_VARIABLES ;

CREATE TABLE IF NOT EXISTS LGG_MCV_PRUEBA_VARIABLES (
RFC                                    VARCHAR(15),
FOLIO                                  VARCHAR(10),
CLIENTE                                VARCHAR(15),
LINEA                                  VARCHAR(15),
FECHACARTERA                           VARCHAR(6) ,	
FECHA_TOPE_03M                         VARCHAR(6) ,
FECHA_TOPE_06M                         VARCHAR(6) ,
FECHA_TOPE_12M                         VARCHAR(6) ,
MONTHS_ON_FILE_BANKING                  DOUBLE,
DS_OL_CL                                DOUBLE,
MIN_R_BAL_BY_CRED_LIM_12M               DOUBLE,
SUM_AMORTIZACIONEXIGIBLE                DOUBLE,
AVG_MS_CL_CL_ACC                        DOUBLE,
MIN_R_BAL_BY_MAX_BAL_12M                DOUBLE,
MIN_R_BAL_BY_MAX_BAL_06M                DOUBLE,
DS_CL                                   DOUBLE,
AVG_MS_OP_OP_ACC                        DOUBLE,
SUM_PAGOREALIZADO_MES                   DOUBLE,
MAX_MS_OP_OP_ACC                        DOUBLE,
AVG1_VP_MES                             DOUBLE,
AVG_SALINI_CL_ACC                       DOUBLE,
MAX_R_BAL_BY_CRED_LIM_12M               DOUBLE,
R_BAL_BY_CRED_LIM                       DOUBLE,
MIN_MS_OP_BRG_OP_ACC                    DOUBLE,
MIN_SALINI_CL_ACC                       DOUBLE,
MAX_SALINI_CL_ACC                       DOUBLE,
BK_DEUDA_CP                             DOUBLE,
MS_OP                                   DOUBLE,
MIN_MS_OP_OP_ACC                        DOUBLE,
MIN_R_BAL_BY_CRED_LIM_06M               DOUBLE,
MAX_AVG1_VP_MES_U06M                    DOUBLE,
AVG_PND_MENOS_R_BAL_BY_CRED_LIM_12M     DOUBLE,
DIAS_ATRASO                             DOUBLE,
PCT_CL_ACC                              DOUBLE,
AVG_AVG1_VP_MES_U03M                    DOUBLE,
MIN_R_BAL_BY_MAX_BAL_03M                DOUBLE,
AVG_AVG1_VP_PER_U12M                    DOUBLE,
MAX_AVG1_VP_MES_U03M                    DOUBLE,
MAX_R_BAL_BY_CRED_LIM_06M               DOUBLE,
SUM_PAGOREALIZADO_PERIODO               DOUBLE,
MIN_MS_CL_CL_ACC                        DOUBLE,
DEUDA_TOT_CP                            DOUBLE,
D_CRED_LIM_TO_BAL                       DOUBLE,
MAX_MS_CL_CL_ACC                        DOUBLE,
PCT_BRG_R_OP_ACC                        DOUBLE,
AVG_PND_MENOS_D_CRED_LIM_TO_BAL_12M     DOUBLE,
AVG_AVG1_VP_MES_U06M                    DOUBLE,
PCT_BK_R_OP_ACC                         DOUBLE,
BK12_NUM_EXP_PAIDONTIME                 DOUBLE,
MIN_SALINI_OP_ACC                       DOUBLE,
PCT_BRG_OP_ACC                          DOUBLE,
MIN_D_CRED_LIM_TO_BAL_12M               DOUBLE,
DPCV_CAP                                DOUBLE,
MAX_AVG1_VP_MES_U12M                    DOUBLE,
MIN_BAL_12M                             DOUBLE,
AVG_MAX_DIAS_PARA_PAGO_U03M             DOUBLE,
AVG_AVG1_VP_MES_U12M                    DOUBLE,
AVG_MAX_DIAS_PARA_PAGO_U12M             DOUBLE,
AVG_MS_OP_BRG_OP_ACC                    DOUBLE,
MIN_MS_OP_BRG_R_OP_ACC                  DOUBLE,
AVG_D_CRED_LIM_TO_BAL_12M               DOUBLE,
MIN_SALINI_OP_ACC_03M                   DOUBLE,
AVG_R_BAL_BY_CRED_LIM_12M               DOUBLE,
MIN_VIGENTEH_12M                        DOUBLE,
MAX_R_BAL_BY_CRED_LIM_03M               DOUBLE,
MIN_R_BAL_BY_CRED_LIM_03M               DOUBLE,
AVG_MAX_DIAS_PARA_PAGO_U06M             DOUBLE,
AVG_VIGENTEC_OP_ACC                     DOUBLE,
DPCV_INT                                DOUBLE,
AVG_PND_MENOS_R_BAL_BY_CRED_LIM_06M     DOUBLE,
PCT_BK_OP_ACC                           DOUBLE,
MIN_D_CRED_LIM_TO_BAL_03M               DOUBLE,
MAX_AVG1_VP_PER_U06M                    DOUBLE,
MAX_D_CRED_LIM_TO_BAL_03M               DOUBLE,
MIN_AVG1_VP_MES_U03M                    DOUBLE,
PCT_BK_CL_ACC                           DOUBLE,
PCT_BK_R_CL_ACC                         DOUBLE,
MAX_AVG1_VP_PER_U12M                    DOUBLE,
SUM_AMORTIZACIONNOEXIGIBLE              DOUBLE,
CUR_BAL                                 DOUBLE,
PCT_BK_CS_OP_ACC                        DOUBLE,
AVG_AVG1_VP_PER_U03M                    DOUBLE,
MAX_DIAS_PARA_PAGO                      DOUBLE,
MAX_AVG1_VP_PER_U03M                    DOUBLE,
MIN_D_CRED_LIM_TO_BAL_06M               DOUBLE,
AVG_AVG1_VP_PER_U06M                    DOUBLE,
MIN_VIGENTEH_03M                        DOUBLE,
MAX_MS_OP_BRG_R_OP_ACC                  DOUBLE,
SUM_VIGENTEH_12M                        DOUBLE,
AVG_PND_MENOS_PCT_VENC29_12M            DOUBLE,
DEUDA_TOT                               DOUBLE,
AVG_PND_MAS_R_BAL_BY_CRED_LIM_12M       DOUBLE,
AVG_SALINI_OP_ACC_03M                   DOUBLE,
AVG_PND_MENOS_AVG_HI_CALCAR_L_12M       DOUBLE,
MAX_MS_OP_BRG_OP_ACC                    DOUBLE,
AVG_MS_OP_BRG_R_OP_ACC                  DOUBLE,
BK_DEUDA_TOT                            DOUBLE,
AVG_PND_MENOS_D_CRED_LIM_TO_BAL_06M     DOUBLE,
PCT_BK_CS_CL_ACC                        DOUBLE,
AVG1_VP_PER                             DOUBLE,
AVG_VIGENTEC_OP_ACC_12M                 DOUBLE,
BK12_MAX_CREDIT_AMT                     DOUBLE,
PCT_OTHER_FIN_OP_ACC                    DOUBLE,
AVG_SALINI_OP_ACC                       DOUBLE,
AVG_PND_MENOS_R_BAL_BY_CRED_LIM_03M     DOUBLE,
PCT_BRG_CL_ACC                          DOUBLE,
AVG_PND_MENOS_BAL_12M                   DOUBLE,
MIN_VIGENTEH_06M                        DOUBLE,
AVG_PND_MAS_R_BAL_BY_CRED_LIM_03M       DOUBLE,
MAX_BAL_12M                             DOUBLE,
PCT_BRG_R_CL_ACC                        DOUBLE,
AVG_PND_MAS_D_CRED_LIM_TO_BAL_12M       DOUBLE,
PCT_OTHER_FIN_CL_ACC                    DOUBLE,
AVG_VIGENTEC_OP_ACC_03M                 DOUBLE,
AVG_PND_MENOS_MAX_HI_CALCAR_L_12M       DOUBLE,
NBK_DEUDA_TOT                           DOUBLE,
AVG_PND_MENOS_PCT_VENC29_03M            DOUBLE,
BK12_DPD_PROM                           DOUBLE,
BK_IND_PMOR                             DOUBLE,
AVG_PND_MAS_AVG_HI_CALCAR_L_03M         DOUBLE,
AVG_PND_MENOS_AVG_HI_CALCAR_CEIL_12M    DOUBLE,
AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_12M   DOUBLE,
MIN_SALINI_BRG_OP_ACC_03M               DOUBLE,
MAX_BAL_06M                             DOUBLE,
AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_12M    DOUBLE,
MIN_CRED_LIM_12M                        DOUBLE,
AVG_R_BAL_BY_CRED_LIM_06M               DOUBLE,
SUM_VIGENTEH_03M                        DOUBLE,
MIN_AVG1_VP_MES_U12M                    DOUBLE,
MAX_VIGENTEC_OP_ACC                     DOUBLE,
MAX_VIGENTEC_BRG_OP_ACC                 DOUBLE,
SUM_VIGENTEH_06M                        DOUBLE,
MIN_SALINI_BRG_R_OP_ACC_03M             DOUBLE,
AVG_PND_MENOS_PCT_VENC29_06M            DOUBLE,
12_INST                                 DOUBLE,
PCT_OTHER_FIN_LSG_OP_ACC                DOUBLE,
AVG_R_BAL_BY_CRED_LIM_03M               DOUBLE,
AVG_VIGENTEC_BRG_OP_ACC                 DOUBLE,
MAX_AVG1_VP_PER_U12M_2                  DOUBLE,
AVG_AVG1_VP_MES_U06M_2                  DOUBLE,
AVG_SALINI_BRG_R_OP_ACC_03M             DOUBLE,
MIN_BAL_06M                             DOUBLE,
AVG_PND_MENOS_AVG_HI_CALCAR_L_06M       DOUBLE,
MIN_SALINI_BRG_OP_ACC                   DOUBLE,
MAX_AVG1_VP_MES_U03M_2                  DOUBLE,
AVG_PND_MENOS_PCT_VENC59_12M            DOUBLE,
MAX_AVG1_VP_MES_U06M_2                  DOUBLE,
AVG_PND_MAS_MAX_HI_CALCAR_L_03M         DOUBLE,
AVG_AVG1_VP_MES_U12M_2                  DOUBLE,
MIN_AVG1_VP_PER_U03M                    DOUBLE,
AVG_VIGENTEC_BRG_R_OP_ACC               DOUBLE,
AVG_PND_MAS_D_CRED_LIM_TO_BAL_06M       DOUBLE,
AVG_PND_MAS_D_CRED_LIM_TO_BAL_03M       DOUBLE,
AVG_SALINI_BRG_R_OP_ACC                 DOUBLE,
PCT_BRG_CS_OP_ACC                       DOUBLE,
AVG_PND_MENOS_AVG_HI_CALCAR_FLOOR_12M   DOUBLE,
MIN_BAL_03M                             DOUBLE,
AVG_PND_MAS_R_BAL_BY_MAX_BAL_12M        DOUBLE,
AVG_PND_MENOS_AVG_HI_CALCAR_L_03M       DOUBLE,
NUM_VIGENTEH_12M                        DOUBLE,
MIN_SALINI_BRG_R_OP_ACC                 DOUBLE,
AVG_PND_MENOS_VENC29_12M                DOUBLE,
AVG_PCT_VENC29_06M                      DOUBLE,
AVG_PND_MAS_PCT_VENC29_03M              DOUBLE,
AVG_PND_MENOS_AVG_HI_CALCAR_CEIL_06M    DOUBLE,
AVG_PND_MENOS_MAX_HI_CALCAR_L_06M       DOUBLE,
MAX_AVG1_VP_MES_U12M_2                  DOUBLE,
AVG_PND_MENOS_D_CRED_LIM_TO_BAL_03M     DOUBLE,
AVG_FD_CALCAR_CEIL                      DOUBLE,
AVG_PND_MAS_R_BAL_BY_CRED_LIM_06M       DOUBLE,
AVG_AVG1_VP_MES_U03M_2                  DOUBLE,
AVG_VIGENTEC_OP_ACC_06M                 DOUBLE,
AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_06M     DOUBLE,
MAX_SALINI_OP_ACC                       DOUBLE,
AVG_AVG1_VP_PER_U12M_2                  DOUBLE,
AVG_PCT_VIGENTEC_OP_ACC                 DOUBLE,
PCT_LSE_OP_ACC                          DOUBLE,
NUM_MAX_HI_CALCAR_FLOOR_12M             DOUBLE,
PCT_BRG_CS_CL_ACC                       DOUBLE,
MAX_VIGENTEC_BRG_R_OP_ACC               DOUBLE,
AVG_VENC29_BRG_OP_ACC_03M               DOUBLE,
AVG_PND_MAS_AVG_HI_CALCAR_L_12M         DOUBLE,
AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_03M   DOUBLE,
MAX_VENC29_03M                          DOUBLE,
PCT_GBN_CF_CL_ACC                       DOUBLE,
AVG_PND_MAS_MAX_HI_CALCAR_L_12M         DOUBLE,
AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_06M    DOUBLE,
MAX_MAX_DIAS_PARA_PAGO_U03M             DOUBLE,
AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_03M     DOUBLE,
AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_12M     DOUBLE,
MAX_CRED_LIM_12M                        DOUBLE,
AVG_PND_MAS_AVG_HI_CALCAR_CEIL_03M      DOUBLE,
AVG_PCT_VENC29_12M                      DOUBLE,
AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_03M    DOUBLE,
AVG_MIN_VP_MES_U12M                     DOUBLE,
AVG_VIGENTEC_BRG_R_OP_ACC_03M           DOUBLE,
AVG_PND_MENOS_R_BAL_BY_MAX_BAL_12M      DOUBLE,
AVG_PND_MENOS_PCT_VENC1M_12M            DOUBLE,
AVG_PCT_VENC1M_BRG_OP_ACC               DOUBLE,
PCT_LSE_LSG_OP_ACC                      DOUBLE,
AVG_PND_MAS_AVG_HI_CALCAR_CEIL_12M      DOUBLE,
AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_06M   DOUBLE,
MIN_SALINI_OP_ACC_06M                   DOUBLE,
AVG_VENC1M_OP_ACC                       DOUBLE,
MAX_BAL_03M                             DOUBLE,
MAX_VIGENTEC_BRG_OP_ACC_03M             DOUBLE,
AVG_PND_MAS_AVG_HI_CALCAR_L_06M         DOUBLE,
MIN_AVG1_VP_MES_U06M                    DOUBLE
);

ALTER TABLE LGG_MCV_PRUEBA_VARIABLES ADD INDEX LLAVE(RFC);             
ALTER TABLE LGG_MCV_PRUEBA_VARIABLES ADD INDEX LLAVE2(CLIENTE);          
ALTER TABLE LGG_MCV_PRUEBA_VARIABLES ADD INDEX LLAVE3(LINEA);            
ALTER TABLE LGG_MCV_PRUEBA_VARIABLES ADD INDEX LLAVE4(FECHACARTERA);     
	
INSERT INTO LGG_MCV_PRUEBA_VARIABLES (RFC,FOLIO,CLIENTE,LINEA,FECHACARTERA,FECHA_TOPE_03M,FECHA_TOPE_06M,FECHA_TOPE_12M)
	(SELECT 
	RFC,FOLIO, CLIENTE, LINEA,FECHA,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -3 MONTH))), 
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -6 MONTH))),
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(FECHA,'01'),'%Y%m%d'),INTERVAL -12 MONTH)))
	
FROM 
	LGG_MCV_SET_PRUEBA);

	USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_MDN_PRUEBA_BAL ;

CREATE TABLE IF NOT EXISTS LGG_MCV_MDN_PRUEBA_BAL AS 
SELECT 
	RFC, CUENTA, FOLIO,ANIOMES AS FECHACARTERA,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(ANIOMES,'01'),'%Y%m%d'),INTERVAL -3 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(ANIOMES,'01'),'%Y%m%d'),INTERVAL -3 MONTH))) AS FECHA_TOPE_03M, 
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(ANIOMES,'01'),'%Y%m%d'),INTERVAL -6 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(ANIOMES,'01'),'%Y%m%d'),INTERVAL -6 MONTH))) AS FECHA_TOPE_06M,
	CONCAT(YEAR(DATE_ADD(STR_TO_DATE(CONCAT(ANIOMES,'01'),'%Y%m%d'),INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(STR_TO_DATE(CONCAT(ANIOMES,'01'),'%Y%m%d'),INTERVAL -12 MONTH))) AS FECHA_TOPE_12M
	
FROM 
	DBMYMWORK.JAT_MCV_LLAVES_MODELO_PEDRO_V3
;

ALTER TABLE LGG_MCV_MDN_PRUEBA_BAL ADD INDEX LLAVE(RFC);
ALTER TABLE LGG_MCV_MDN_PRUEBA_BAL ADD INDEX LLAVE1(CUENTA);
ALTER TABLE LGG_MCV_MDN_PRUEBA_BAL ADD INDEX LLAVE2(FOLIO);
ALTER TABLE LGG_MCV_MDN_PRUEBA_BAL ADD INDEX LLAVE3(FECHACARTERA);

--  PERIODO 3 MESES
ALTER TABLE LGG_MCV_MDN_PRUEBA_BAL 
	ADD COLUMN CUR_BAL      DOUBLE NULL ,
	ADD COLUMN MAX_BAL_06M  DOUBLE NULL ,
	ADD COLUMN MAX_BAL_12M  DOUBLE NULL ;
	
UPDATE 	
	LGG_MCV_MDN_PRUEBA_BAL T1 
SET T1.CUR_BAL= (SELECT T2.SALDO
					FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia WHERE MIS <> '0' GROUP BY 1,2) AS T2
					WHERE T2.FECHA = T1.FECHACARTERA
					AND T1.RFC = T2.RFC),
	T1.MAX_BAL_06M = (SELECT MAX(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia WHERE MIS <> '0' GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),  					
	T1.MAX_BAL_12M = (SELECT MAX(SALDO)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia WHERE MIS <> '0' GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC);

--  Variables Internas	
UPDATE 	
	LGG_MCV_PRUEBA_VARIABLES T1 
SET 	
	T1.MIN_BAL_12M = (SELECT MIN(SALDO)
						FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2)AS T2
							WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
							AND T1.RFC = T2.RFC),
    T1.CUR_BAL= (SELECT T2.SALDO
					FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
					WHERE T2.FECHA = T1.FECHACARTERA
					AND T1.RFC = T2.RFC), 
    T1.AVG_PND_MENOS_BAL_12M = (SELECT SUM(SALDO * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
						FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
					WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
					AND T1.RFC = T2.RFC)/
					(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
						FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
					WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
					AND T1.RFC = T2.RFC), 		
	T1.MAX_BAL_12M = (SELECT MAX(SALDO)
			        	FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
			        		WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
			        		AND T1.RFC = T2.RFC), 	
	T1.MAX_BAL_06M = (SELECT MAX(SALDO)
						FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
							WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
							AND T1.RFC = T2.RFC),  
	T1.MIN_BAL_06M = (SELECT MIN(SALDO)
						FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2)AS T2
							WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
							AND T1.RFC = T2.RFC),      									
	T1.MIN_BAL_03M = (SELECT MIN(SALDO)
						FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2)AS T2
							WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
							AND T1.RFC = T2.RFC), 		
	T1.MAX_BAL_03M = (SELECT MAX(SALDO)
						FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO FROM DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
							WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
							AND T1.RFC = T2.RFC),  
    T1.MIN_CRED_LIM_12M = (SELECT MIN(MONTO_LINEA)
							FROM DBRSKDATAMART.Tbl_CarteraCrediticia AS T2
								WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
								AND T1.LINEA= T2.LINEA),  
	T1.MAX_CRED_LIM_12M = (SELECT MAX(MONTO_LINEA)
							FROM DBRSKDATAMART.Tbl_CarteraCrediticia AS T2
								WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
								AND T1.LINEA= T2.LINEA),         	
	T1.D_CRED_LIM_TO_BAL = (SELECT MONTO_LINEA - SALDO
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
										WHERE T2.FECHA = T1.FECHACARTERA
										AND T1.RFC = T2.RFC),
 T1.AVG_PND_MENOS_D_CRED_LIM_TO_BAL_12M = (SELECT SUM((MONTO_LINEA - SALDO) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC),    
	T1.MIN_D_CRED_LIM_TO_BAL_12M = (SELECT MIN(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),  
T1.AVG_D_CRED_LIM_TO_BAL_12M = (SELECT AVG(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),
	T1.MIN_D_CRED_LIM_TO_BAL_03M = (SELECT MIN(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC),									
T1.MAX_D_CRED_LIM_TO_BAL_03M = (SELECT MAX(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
										WHERE  T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC) ,   
 T1.MIN_D_CRED_LIM_TO_BAL_06M = (SELECT MIN(MONTO_LINEA - SALDO)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
										WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
										AND T1.RFC = T2.RFC), 
 T1.AVG_PND_MENOS_D_CRED_LIM_TO_BAL_06M = (SELECT SUM((MONTO_LINEA - SALDO) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC),  
												T1.AVG_PND_MAS_D_CRED_LIM_TO_BAL_12M = (SELECT SUM((MONTO_LINEA - SALDO) * (13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC),
	T1.AVG_PND_MAS_D_CRED_LIM_TO_BAL_06M = (SELECT SUM((MONTO_LINEA - SALDO) * (7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((7-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC),
	   T1.AVG_PND_MAS_D_CRED_LIM_TO_BAL_03M = (SELECT SUM((MONTO_LINEA - SALDO) * (4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC),											
		T1.AVG_PND_MENOS_D_CRED_LIM_TO_BAL_03M = (SELECT SUM((MONTO_LINEA - SALDO) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
												FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
												WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
												AND T1.RFC = T2.RFC), 
		T1.MIN_R_BAL_BY_CRED_LIM_12M = (SELECT MIN(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC), 
T1.MAX_R_BAL_BY_CRED_LIM_12M = (SELECT MAX(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),  
T1.R_BAL_BY_CRED_LIM = (SELECT MAX(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA = T1.FECHACARTERA
									AND T1.RFC = T2.RFC) , 
T1.MIN_R_BAL_BY_CRED_LIM_06M = (SELECT MIN(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
T1.AVG_PND_MENOS_R_BAL_BY_CRED_LIM_12M = (SELECT SUM((SALDO/MONTO_LINEA) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
T1.MAX_R_BAL_BY_CRED_LIM_06M = (SELECT MAX(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC), 
T1.AVG_R_BAL_BY_CRED_LIM_12M = (SELECT AVG(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),	
T1.MAX_R_BAL_BY_CRED_LIM_03M = (SELECT MAX(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC), 	
T1.MIN_R_BAL_BY_CRED_LIM_03M = (SELECT MIN(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC), 
   T1.AVG_PND_MENOS_R_BAL_BY_CRED_LIM_06M = (SELECT SUM((SALDO/MONTO_LINEA) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC), 	
T1.AVG_PND_MAS_R_BAL_BY_CRED_LIM_12M = (SELECT SUM((SALDO/MONTO_LINEA) * (13 -((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM(SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2)  AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((13 -((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_12M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
  T1.AVG_PND_MENOS_R_BAL_BY_CRED_LIM_03M = (SELECT SUM((SALDO/MONTO_LINEA) * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100)+1)
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),  									
T1.AVG_PND_MAS_R_BAL_BY_CRED_LIM_03M = (SELECT SUM((SALDO/MONTO_LINEA) * (4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM(SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2)  AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((4-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
	T1.AVG_R_BAL_BY_CRED_LIM_06M = (SELECT AVG(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
	T1.AVG_R_BAL_BY_CRED_LIM_03M = (SELECT AVG(SALDO/MONTO_LINEA)
								FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_03M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC),
									    T1.AVG_PND_MAS_R_BAL_BY_CRED_LIM_06M = (SELECT SUM((SALDO/MONTO_LINEA) * (7 -((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM(SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2)  AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC)/
									(SELECT SUM((7 -((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHA,100))))
										FROM (SELECT RFC,FECHA,SUM(SALDO) AS SALDO, MAX(MONTO_LINEA) AS MONTO_LINEA FROM  DBRSKDATAMART.Tbl_CarteraCrediticia GROUP BY 1,2) AS T2
									WHERE T2.FECHA >= T1.FECHA_TOPE_06M AND T2.FECHA <= T1.FECHACARTERA
									AND T1.RFC = T2.RFC);
UPDATE 	
	LGG_MCV_PRUEBA_VARIABLES T1 
SET 									
	T1.MIN_R_BAL_BY_MAX_BAL_12M = (SELECT MIN(R_BAL_BY_MAX_BAL)
										FROM (SELECT  LINEA,FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_PRUEBA_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LINEA = T2.LINEA),        
	T1.MIN_R_BAL_BY_MAX_BAL_06M = (SELECT MIN(R_BAL_BY_MAX_BAL)
										FROM (SELECT  RFC, LINEA, FECHACARTERA, IF(MAX_BAL_06M = 0 ,0,(CUR_BAL / MAX_BAL_06M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_PRUEBA_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_06M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND T1.LINEA = T2.LINEA), 
	T1.MIN_R_BAL_BY_MAX_BAL_03M = (SELECT MIN(R_BAL_BY_MAX_BAL)
										FROM (SELECT  RFC, LINEA, FECHACARTERA, IF(MAX_BAL_03M = 0 ,0,(CUR_BAL / MAX_BAL_03M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_PRUEBA_BAL  ) AS T2
										WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_03M AND T2.FECHACARTERA <= T1.FECHACARTERA
										AND  T1.LINEA = T2.LINEA); 
UPDATE										
	LGG_MCV_PRUEBA_VARIABLES T1 
SET  
	T1.AVG_PND_MAS_R_BAL_BY_MAX_BAL_12M = (SELECT SUM(R_BAL_BY_MAX_BAL * (13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100))))
												FROM (SELECT  RFC, LINEA, FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_PRUEBA_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LINEA = T2.LINEA)/
											(SELECT SUM((13-((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100))))
												FROM (SELECT  RFC, LINEA, FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_PRUEBA_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LINEA = T2.LINEA),
    T1.AVG_PND_MENOS_R_BAL_BY_MAX_BAL_12M = (SELECT SUM(R_BAL_BY_MAX_BAL * ((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100)+1))
												FROM (SELECT  RFC, LINEA, FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M)) AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_PRUEBA_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LINEA = T2.LINEA)/
											(SELECT SUM((FLOOR(T1.FECHACARTERA/100)-FLOOR(T2.FECHACARTERA/100))*12+MOD(T1.FECHACARTERA,100)-MOD(T2.FECHACARTERA,100)+1)
												FROM (SELECT  RFC, LINEA, FECHACARTERA, IF(MAX_BAL_12M = 0 ,0,(CUR_BAL / MAX_BAL_12M))AS R_BAL_BY_MAX_BAL FROM  DBMYMWORK.LGG_MCV_PRUEBA_BAL  ) AS T2
												WHERE T2.FECHACARTERA >= T1.FECHA_TOPE_12M AND T2.FECHACARTERA <= T1.FECHACARTERA
												AND T1.LINEA = T2.LINEA);	
												
--  CREDITOS LIQUIDADOS												
UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET
	AVG_SALINI_CL_ACC = (SELECT AVG(SaldoInicialLiq) FROM LGG_MCV_PRUEBAS_CREDITOS_LIQUIDADOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_SALINI_CL_ACC = (SELECT MIN(SaldoInicialLiq) FROM LGG_MCV_PRUEBAS_CREDITOS_LIQUIDADOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_SALINI_CL_ACC = (SELECT MAX(SaldoInicialLiq) FROM LGG_MCV_PRUEBAS_CREDITOS_LIQUIDADOS T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_MS_CL_CL_ACC  = (SELECT AVG(CR_MS_CL) FROM LGG_MCV_PRUEBAS_CREDITOS_LIQUIDADOS T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_MS_CL_CL_ACC  = (SELECT MIN(CR_MS_CL) FROM LGG_MCV_PRUEBAS_CREDITOS_LIQUIDADOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_MS_CL_CL_ACC  = (SELECT MAX(CR_MS_CL) FROM LGG_MCV_PRUEBAS_CREDITOS_LIQUIDADOS T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
											
--  CREDITOS ACTIVOS												
UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET		
	AVG_VENC29_BRG_OP_ACC_03M      = (SELECT AVG(DIAS29)       FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND BRG_OP_ACC             = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_VIGENTEC_OP_ACC            = (SELECT AVG(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_VIGENTEC_OP_ACC            = (SELECT MAX(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_VIGENTEC_BRG_OP_ACC        = (SELECT MAX(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_OP_ACC   = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_VIGENTEC_BRG_R_OP_ACC      = (SELECT AVG(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_R_OP_ACC  = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_VIGENTEC_BRG_R_OP_ACC      = (SELECT MAX(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_R_OP_ACC = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_VENC1M_OP_ACC              = (SELECT AVG(VENC1MAS)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_PCT_VIGENTEC_OP_ACC        = (SELECT AVG(PCTVIG)       FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_PCT_VENC1M_BRG_OP_ACC      = (SELECT AVG(PCTV1M)       FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_OP_ACC  = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_MS_OP_OP_ACC               = (SELECT AVG(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_MS_OP_OP_ACC               = (SELECT MAX(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_MS_OP_BRG_OP_ACC           = (SELECT MIN(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_OP_ACC = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_MS_OP_OP_ACC               = (SELECT MIN(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_SALINI_OP_ACC              = (SELECT MIN(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_MS_OP_BRG_OP_ACC           = (SELECT AVG(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_OP_ACC   = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_MS_OP_BRG_R_OP_ACC         = (SELECT MIN(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_R_OP_ACC   = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_SALINI_OP_ACC_03M          = (SELECT MIN(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_MS_OP_BRG_R_OP_ACC         = (SELECT MAX(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_R_OP_ACC = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_SALINI_OP_ACC_03M          = (SELECT AVG(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_MS_OP_BRG_OP_ACC           = (SELECT MAX(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_OP_ACC    = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_MS_OP_BRG_R_OP_ACC         = (SELECT AVG(CR_MS_OP)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_R_OP_ACC  = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_SALINI_OP_ACC              = (SELECT AVG(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_SALINI_BRG_OP_ACC_03M      = (SELECT MIN(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND BRG_OP_ACC    = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_SALINI_BRG_R_OP_ACC_03M    = (SELECT MIN(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND BRG_R_OP_ACC  = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_SALINI_BRG_R_OP_ACC_03M    = (SELECT AVG(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND BRG_R_OP_ACC  = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_SALINI_BRG_OP_ACC          = (SELECT MIN(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_OP_ACC   = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_SALINI_BRG_R_OP_ACC        = (SELECT AVG(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_R_OP_ACC = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_SALINI_BRG_R_OP_ACC        = (SELECT MIN(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_R_OP_ACC = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_SALINI_OP_ACC              = (SELECT MAX(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MIN_SALINI_OP_ACC_06M          = (SELECT MIN(SaldoInicial) FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <7 AND DIF_MESES >=0 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_VIGENTEC_OP_ACC_12M        = (SELECT AVG(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <13 AND DIF_MESES >=0 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_VIGENTEC_OP_ACC_03M        = (SELECT AVG(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_VIGENTEC_OP_ACC_06M        = (SELECT AVG(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <7 AND DIF_MESES >=0 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_VIGENTEC_BRG_R_OP_ACC_03M  = (SELECT AVG(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND BRG_R_OP_ACC = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	MAX_VIGENTEC_BRG_OP_ACC_03M    = (SELECT MAX(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE DIF_MESES <4 AND DIF_MESES >=0 AND BRG_OP_ACC   = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO),
	AVG_VIGENTEC_BRG_OP_ACC        = (SELECT AVG(VigenteC)     FROM LGG_MCV_PRUEBA_CREDITOS_ACTIVOS T2  WHERE BRG_OP_ACC             = 1 AND T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO);
	
										
--  Lorena García González
--  Agosto 20, 2018
--  MCV: Variables - Copia Buro Historia con Banderas. Es la misma tabla que la oficial, solo que esta tiene la banderas necesarias.


USE DBMYMWORK;

DROP TABLE IF EXISTS LGG_MCV_PRUEBA_HI;
CREATE TABLE IF NOT EXISTS LGG_MCV_PRUEBA_HI 
AS
SELECT 
	DISTINCT FOLIO,RFC,FECHACONSULTA,PERIODO,CALIFICACIONCARTERA,
CONCAT(YEAR(DATE_ADD(FECHACONSULTA,INTERVAL -3 MONTH)) *100+MONTH(DATE_ADD(FECHACONSULTA,INTERVAL -3 MONTH)))  AS FECHA_TOPE_03M, 
CONCAT(YEAR(DATE_ADD(FECHACONSULTA,INTERVAL -6 MONTH)) *100+MONTH(DATE_ADD(FECHACONSULTA,INTERVAL -6 MONTH)))  AS FECHA_TOPE_06M,
CONCAT(YEAR(DATE_ADD(FECHACONSULTA,INTERVAL -12 MONTH))*100+MONTH(DATE_ADD(FECHACONSULTA,INTERVAL -12 MONTH))) AS FECHA_TOPE_12M,
--  SALDOS VENCIDOS 
VENCIDO1A29	,
VENCIDO30A59,
VENCIDO60A89,
VENCIDOMAS89 AS VENCIDO90MAS,
VIGENTEH,
--  ACUMULACION DE SALDOS VENCIDOS
(VENCIDO1A29 + VENCIDO30A59 + VENCIDO60A89 + VENCIDOMAS89 + VIGENTEH) AS SALDOTOTAL,
(VENCIDO1A29 + VENCIDO30A59 + VENCIDO60A89 + VENCIDOMAS89 ) AS VENCIDO1MAS,
(VENCIDO30A59 + VENCIDO60A89 + VENCIDOMAS89 ) AS VENCIDO30MAS,
(VENCIDO60A89 + VENCIDOMAS89) AS VENCIDO60MAS
FROM 
	(SELECT * FROM DBRSKDATAMART.Tbl_BuroHistoriaPM_recurrente WHERE FOLIO IN (SELECT FOLIO FROM DBMYMWORK.LGG_MCV_SET_PRUEBA))T10;

ALTER TABLE LGG_MCV_PRUEBA_HI ADD INDEX LLAVE(RFC);
ALTER TABLE LGG_MCV_PRUEBA_HI ADD INDEX LLAVE1(FOLIO);
ALTER TABLE LGG_MCV_PRUEBA_HI ADD INDEX LLAVE2(FECHACONSULTA);
ALTER TABLE LGG_MCV_PRUEBA_HI ADD INDEX LLAVE3(PERIODO);

--  ACTUALIZAMOS LOS PESOS
--  PND_MASXXX SE LE DA MAS PESO A LAS VARIABLES RECIENTES.
--  PND_MENOSXXX SE LE DA MENOS PESO A LAS VARIABLES RECIENTES.
ALTER TABLE LGG_MCV_PRUEBA_HI  --  PESO PARA LAS PONDERACIONES
	ADD COLUMN PND_MAS03M   INT AFTER FECHA_TOPE_12M,
	ADD COLUMN PND_MAS06M   INT AFTER PND_MAS03M  ,
	ADD COLUMN PND_MAS12M   INT AFTER PND_MAS06M  ,
	ADD COLUMN PND_MENOS03M INT AFTER PND_MAS12M  ,
	ADD COLUMN PND_MENOS06M INT AFTER PND_MENOS03M,
	ADD COLUMN PND_MENOS12M INT AFTER PND_MENOS06M;

UPDATE LGG_MCV_PRUEBA_HI  T1
LEFT JOIN(SELECT FOLIO, PERIODO,
((YEAR(FECHACONSULTA)-FLOOR(PERIODO/100))*12+ MONTH(FECHACONSULTA)- MOD(PERIODO,100)+1) AS PND_MAS
FROM LGG_MCV_PRUEBA_HI )T2
ON T1.FOLIO = T2.FOLIO AND T1.PERIODO = T2.PERIODO 
SET T1.PND_MAS03M    = IF(VIGENTEH IS NULL,NULL,5  - IF(T2.PND_MAS > 4 ,NULL,T2.PND_MAS)),
	T1.PND_MAS06M    = IF(VIGENTEH IS NULL,NULL,8  - IF(T2.PND_MAS > 7 ,NULL,T2.PND_MAS)),
	T1.PND_MAS12M    = IF(VIGENTEH IS NULL,NULL,14 - IF(T2.PND_MAS > 13,NULL,T2.PND_MAS)),
	T1.PND_MENOS03M  = IF(VIGENTEH IS NULL,NULL,IF(T2.PND_MAS > 4 ,NULL,T2.PND_MAS)),
	T1.PND_MENOS06M  = IF(VIGENTEH IS NULL,NULL,IF(T2.PND_MAS > 7 ,NULL,T2.PND_MAS)),
	T1.PND_MENOS12M  = IF(VIGENTEH IS NULL,NULL,IF(T2.PND_MAS > 13,NULL,T2.PND_MAS));

--  AGREGAMOS LAS COLUMNAS DE LOS PORCENTAJES
ALTER TABLE LGG_MCV_PRUEBA_HI 
	ADD COLUMN PCT_VENC29   DOUBLE NULL,
	ADD COLUMN PCT_VENC59   DOUBLE NULL,
	ADD COLUMN PCT_VENC89   DOUBLE NULL,
	ADD COLUMN PCT_VENC90M  DOUBLE NULL,
	ADD COLUMN PCT_VIGENTEH DOUBLE NULL,
	ADD COLUMN PCT_VENC1M   DOUBLE NULL,
	ADD COLUMN PCT_VENC30M  DOUBLE NULL,
	ADD COLUMN PCT_VENC60M  DOUBLE NULL;

UPDATE LGG_MCV_PRUEBA_HI T1
SET 
--  PORCENTAJE DE SALDOS VENCIDOS Y VIGENTE
PCT_VENC29   = IF(SALDOTOTAL IS NULL OR SALDOTOTAL = 0, NULL, VENCIDO1A29/SALDOTOTAL) ,
PCT_VENC59   = IF(SALDOTOTAL IS NULL OR SALDOTOTAL = 0, NULL, VENCIDO30A59/SALDOTOTAL),
PCT_VENC89   = IF(SALDOTOTAL IS NULL OR SALDOTOTAL = 0, NULL, VENCIDO60A89/SALDOTOTAL),
PCT_VENC90M  = IF(SALDOTOTAL IS NULL OR SALDOTOTAL = 0, NULL, VENCIDO90MAS/SALDOTOTAL),
PCT_VIGENTEH = IF(SALDOTOTAL IS NULL OR SALDOTOTAL = 0, NULL, VIGENTEH/SALDOTOTAL),
--  PORCENTAJE DE SALDOS ACUMULADOS
PCT_VENC1M  = IF(SALDOTOTAL IS NULL OR SALDOTOTAL = 0, NULL, VENCIDO1MAS/SALDOTOTAL)  ,
PCT_VENC30M = IF(SALDOTOTAL IS NULL OR SALDOTOTAL = 0, NULL, VENCIDO30MAS/SALDOTOTAL) ,
PCT_VENC60M = IF(SALDOTOTAL IS NULL OR SALDOTOTAL = 0, NULL, VENCIDO60MAS/SALDOTOTAL) ;


--  AGREGAMOS LOS RESULTADOS DE LA CALIFICACION
ALTER TABLE LGG_MCV_PRUEBA_HI 
	ADD COLUMN AVG_HI_CALCAR_L     DOUBLE NULL ,
	ADD COLUMN MAX_HI_CALCAR_L     DOUBLE NULL ,
	ADD COLUMN AVG_HI_CALCAR_CEIL  DOUBLE NULL , 
	ADD COLUMN MAX_HI_CALCAR_CEIL  DOUBLE NULL ,
	ADD COLUMN MAX_HI_CALCAR_FLOOR DOUBLE NULL ,
	ADD COLUMN AVG_HI_CALCAR_FLOOR DOUBLE NULL ;

--  CALIFICACION DE CARTERA 
/* ACTUALIZAR EN CASO NECESARIO
DROP TABLE IF EXISTS LGG_MCV_TMP_02;
 CREATE TABLE IF NOT EXISTS LGG_MCV_TMP_02
(
SELECT RFC,FOLIO,PERIODO,
LGG_MCV_CAL_HI(CALIFICACIONCARTERA,1,1) AS  AVG_HI_CALCAR_L,
LGG_MCV_CAL_HI(CALIFICACIONCARTERA,1,2) AS  MAX_HI_CALCAR_L,
LGG_MCV_CAL_HI(CALIFICACIONCARTERA,2,1) AS  AVG_HI_CALCAR_CEIL, -- CORTE SUPERIOR
LGG_MCV_CAL_HI(CALIFICACIONCARTERA,2,2) AS  MAX_HI_CALCAR_CEIL,
LGG_MCV_CAL_HI(CALIFICACIONCARTERA,3,1) AS  MAX_HI_CALCAR_FLOOR, --  CORTE INFERIOR
LGG_MCV_CAL_HI(CALIFICACIONCARTERA,3,2) AS  AVG_HI_CALCAR_FLOOR
FROM DBMYMWORK.JEA_MCV_HISTORIA);

ALTER TABLE LGG_MCV_TMP_02 ADD INDEX LLAVE(FOLIO);
ALTER TABLE LGG_MCV_TMP_02 ADD INDEX LLAVE1(RFC);
ALTER TABLE LGG_MCV_TMP_02 ADD INDEX LLAVE2(PERIODO); */	
	
--  ACTUALIZAMOS LA INFORMACION
UPDATE LGG_MCV_PRUEBA_HI T1 
LEFT JOIN (
SELECT *
FROM LGG_MCV_TMP_02) T2 
ON T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T1.PERIODO = T2.PERIODO
SET T1.AVG_HI_CALCAR_L     = T2.AVG_HI_CALCAR_L    ,
    T1.MAX_HI_CALCAR_L     = T2.MAX_HI_CALCAR_L    ,
    T1.AVG_HI_CALCAR_CEIL  = T2.AVG_HI_CALCAR_CEIL ,
    T1.MAX_HI_CALCAR_CEIL  = T2.MAX_HI_CALCAR_CEIL ,
    T1.MAX_HI_CALCAR_FLOOR = T2.MAX_HI_CALCAR_FLOOR,
    T1.AVG_HI_CALCAR_FLOOR = T2.AVG_HI_CALCAR_FLOOR;

--  OBTENEMOS EL PRODUCTO DEL VALOR POR SU PONDERACION.
--  PND_MAS03M: COLUMNAS
ALTER TABLE  LGG_MCV_PRUEBA_HI
	ADD COLUMN PND_MAS_VENC29_U03M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC59_U03M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC89_U03M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC90M_U03M             DOUBLE NULL,
	ADD COLUMN PND_MAS_VIGENTEH_U03M            DOUBLE NULL,
	ADD COLUMN PND_MAS_SALDOTOTAL_U03M          DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC1M_U03M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC30M_U03M             DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC60M_U03M             DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC29_U03M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC59_U03M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC89_U03M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC90M_U03M         DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VIGENTEH_U03M        DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC1M_U03M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC30M_U03M         DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC60M_U03M         DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_L_U03M     DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_L_U03M     DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_CEIL_U03M  DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_CEIL_U03M  DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_FLOOR_U03M DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_FLOOR_U03M DOUBLE NULL;

--  PND_MAS03M: VALORES
UPDATE LGG_MCV_PRUEBA_HI T1 
SET PND_MAS_VENC29_U03M              = PND_MAS03M * VENCIDO1A29         ,
    PND_MAS_VENC59_U03M              = PND_MAS03M * VENCIDO30A59        ,
    PND_MAS_VENC89_U03M              = PND_MAS03M * VENCIDO60A89        ,
	PND_MAS_VENC90M_U03M             = PND_MAS03M * VENCIDO90MAS        ,
	PND_MAS_VIGENTEH_U03M            = PND_MAS03M * VIGENTEH            ,
    PND_MAS_SALDOTOTAL_U03M          = PND_MAS03M * SALDOTOTAL          ,
    PND_MAS_VENC1M_U03M              = PND_MAS03M * VENCIDO1MAS         ,
    PND_MAS_VENC30M_U03M             = PND_MAS03M * VENCIDO30MAS        ,
    PND_MAS_VENC60M_U03M             = PND_MAS03M * VENCIDO60MAS        ,
    PND_MAS_PCT_VENC29_U03M          = PND_MAS03M * PCT_VENC29          ,
    PND_MAS_PCT_VENC59_U03M          = PND_MAS03M * PCT_VENC59          ,
    PND_MAS_PCT_VENC89_U03M          = PND_MAS03M * PCT_VENC89          ,
    PND_MAS_PCT_VENC90M_U03M         = PND_MAS03M * PCT_VENC90M         ,
    PND_MAS_PCT_VIGENTEH_U03M        = PND_MAS03M * PCT_VIGENTEH        ,
    PND_MAS_PCT_VENC1M_U03M          = PND_MAS03M * PCT_VENC1M          ,
    PND_MAS_PCT_VENC30M_U03M         = PND_MAS03M * PCT_VENC30M         ,
    PND_MAS_PCT_VENC60M_U03M         = PND_MAS03M * PCT_VENC60M         ,
    PND_MAS_AVG_HI_CALCAR_L_U03M     = PND_MAS03M * AVG_HI_CALCAR_L     ,
    PND_MAS_MAX_HI_CALCAR_L_U03M     = PND_MAS03M * MAX_HI_CALCAR_L     ,
    PND_MAS_AVG_HI_CALCAR_CEIL_U03M  = PND_MAS03M * AVG_HI_CALCAR_CEIL  ,
    PND_MAS_MAX_HI_CALCAR_CEIL_U03M  = PND_MAS03M * MAX_HI_CALCAR_CEIL  ,
    PND_MAS_MAX_HI_CALCAR_FLOOR_U03M = PND_MAS03M * MAX_HI_CALCAR_FLOOR ,
    PND_MAS_AVG_HI_CALCAR_FLOOR_U03M = PND_MAS03M * AVG_HI_CALCAR_FLOOR ;
	
--  PND_MAS06M: COLUMNAS
ALTER TABLE  LGG_MCV_PRUEBA_HI
	ADD COLUMN PND_MAS_VENC29_U06M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC59_U06M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC89_U06M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC90M_U06M             DOUBLE NULL,
	ADD COLUMN PND_MAS_VIGENTEH_U06M            DOUBLE NULL,
	ADD COLUMN PND_MAS_SALDOTOTAL_U06M          DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC1M_U06M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC30M_U06M             DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC60M_U06M             DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC29_U06M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC59_U06M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC89_U06M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC90M_U06M         DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VIGENTEH_U06M        DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC1M_U06M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC30M_U06M         DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC60M_U06M         DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_L_U06M     DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_L_U06M     DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_CEIL_U06M  DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_CEIL_U06M  DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_FLOOR_U06M DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_FLOOR_U06M DOUBLE NULL;

--  PND_MAS06M: VALORES
UPDATE LGG_MCV_PRUEBA_HI T1 
SET PND_MAS_VENC29_U06M              = PND_MAS06M * VENCIDO1A29         ,
    PND_MAS_VENC59_U06M              = PND_MAS06M * VENCIDO30A59        ,
    PND_MAS_VENC89_U06M              = PND_MAS06M * VENCIDO60A89        ,
	PND_MAS_VENC90M_U06M             = PND_MAS06M * VENCIDO90MAS        ,
	PND_MAS_VIGENTEH_U06M            = PND_MAS06M * VIGENTEH            ,
    PND_MAS_SALDOTOTAL_U06M          = PND_MAS06M * SALDOTOTAL          ,
    PND_MAS_VENC1M_U06M              = PND_MAS06M * VENCIDO1MAS         ,
    PND_MAS_VENC30M_U06M             = PND_MAS06M * VENCIDO30MAS        ,
    PND_MAS_VENC60M_U06M             = PND_MAS06M * VENCIDO60MAS        ,
    PND_MAS_PCT_VENC29_U06M          = PND_MAS06M * PCT_VENC29          ,
    PND_MAS_PCT_VENC59_U06M          = PND_MAS06M * PCT_VENC59          ,
    PND_MAS_PCT_VENC89_U06M          = PND_MAS06M * PCT_VENC89          ,
    PND_MAS_PCT_VENC90M_U06M         = PND_MAS06M * PCT_VENC90M         ,
    PND_MAS_PCT_VIGENTEH_U06M        = PND_MAS06M * PCT_VIGENTEH        ,
    PND_MAS_PCT_VENC1M_U06M          = PND_MAS06M * PCT_VENC1M          ,
    PND_MAS_PCT_VENC30M_U06M         = PND_MAS06M * PCT_VENC30M         ,
    PND_MAS_PCT_VENC60M_U06M         = PND_MAS06M * PCT_VENC60M         ,
    PND_MAS_AVG_HI_CALCAR_L_U06M     = PND_MAS06M * AVG_HI_CALCAR_L     ,
    PND_MAS_MAX_HI_CALCAR_L_U06M     = PND_MAS06M * MAX_HI_CALCAR_L     ,
    PND_MAS_AVG_HI_CALCAR_CEIL_U06M  = PND_MAS06M * AVG_HI_CALCAR_CEIL  ,
    PND_MAS_MAX_HI_CALCAR_CEIL_U06M  = PND_MAS06M * MAX_HI_CALCAR_CEIL  ,
    PND_MAS_MAX_HI_CALCAR_FLOOR_U06M = PND_MAS06M * MAX_HI_CALCAR_FLOOR ,
    PND_MAS_AVG_HI_CALCAR_FLOOR_U06M = PND_MAS06M * AVG_HI_CALCAR_FLOOR ;

--  PND_MAS12M: COLUMNAS
ALTER TABLE  LGG_MCV_PRUEBA_HI
	ADD COLUMN PND_MAS_VENC29_U12M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC59_U12M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC89_U12M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC90M_U12M             DOUBLE NULL,
	ADD COLUMN PND_MAS_VIGENTEH_U12M            DOUBLE NULL,
	ADD COLUMN PND_MAS_SALDOTOTAL_U12M          DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC1M_U12M              DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC30M_U12M             DOUBLE NULL,
	ADD COLUMN PND_MAS_VENC60M_U12M             DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC29_U12M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC59_U12M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC89_U12M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC90M_U12M         DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VIGENTEH_U12M        DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC1M_U12M          DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC30M_U12M         DOUBLE NULL,
	ADD COLUMN PND_MAS_PCT_VENC60M_U12M         DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_L_U12M     DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_L_U12M     DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_CEIL_U12M  DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_CEIL_U12M  DOUBLE NULL,
	ADD COLUMN PND_MAS_MAX_HI_CALCAR_FLOOR_U12M DOUBLE NULL,
	ADD COLUMN PND_MAS_AVG_HI_CALCAR_FLOOR_U12M DOUBLE NULL;

--  PND_MAS12M: VALORES
UPDATE LGG_MCV_PRUEBA_HI T1 
SET PND_MAS_VENC29_U12M              = PND_MAS12M * VENCIDO1A29         ,
    PND_MAS_VENC59_U12M              = PND_MAS12M * VENCIDO30A59        ,
    PND_MAS_VENC89_U12M              = PND_MAS12M * VENCIDO60A89        ,
	PND_MAS_VENC90M_U12M             = PND_MAS12M * VENCIDO90MAS        ,
	PND_MAS_VIGENTEH_U12M            = PND_MAS12M * VIGENTEH            ,
    PND_MAS_SALDOTOTAL_U12M          = PND_MAS12M * SALDOTOTAL          ,
    PND_MAS_VENC1M_U12M              = PND_MAS12M * VENCIDO1MAS         ,
    PND_MAS_VENC30M_U12M             = PND_MAS12M * VENCIDO30MAS        ,
    PND_MAS_VENC60M_U12M             = PND_MAS12M * VENCIDO60MAS        ,
    PND_MAS_PCT_VENC29_U12M          = PND_MAS12M * PCT_VENC29          ,
    PND_MAS_PCT_VENC59_U12M          = PND_MAS12M * PCT_VENC59          ,
    PND_MAS_PCT_VENC89_U12M          = PND_MAS12M * PCT_VENC89          ,
    PND_MAS_PCT_VENC90M_U12M         = PND_MAS12M * PCT_VENC90M         ,
    PND_MAS_PCT_VIGENTEH_U12M        = PND_MAS12M * PCT_VIGENTEH        ,
    PND_MAS_PCT_VENC1M_U12M          = PND_MAS12M * PCT_VENC1M          ,
    PND_MAS_PCT_VENC30M_U12M         = PND_MAS12M * PCT_VENC30M         ,
    PND_MAS_PCT_VENC60M_U12M         = PND_MAS12M * PCT_VENC60M         ,
    PND_MAS_AVG_HI_CALCAR_L_U12M     = PND_MAS12M * AVG_HI_CALCAR_L     ,
    PND_MAS_MAX_HI_CALCAR_L_U12M     = PND_MAS12M * MAX_HI_CALCAR_L     ,
    PND_MAS_AVG_HI_CALCAR_CEIL_U12M  = PND_MAS12M * AVG_HI_CALCAR_CEIL  ,
    PND_MAS_MAX_HI_CALCAR_CEIL_U12M  = PND_MAS12M * MAX_HI_CALCAR_CEIL  ,
    PND_MAS_MAX_HI_CALCAR_FLOOR_U12M = PND_MAS12M * MAX_HI_CALCAR_FLOOR ,
    PND_MAS_AVG_HI_CALCAR_FLOOR_U12M = PND_MAS12M * AVG_HI_CALCAR_FLOOR ;

--  PND_MENOS03M: COLUMNAS
ALTER TABLE  LGG_MCV_PRUEBA_HI
	ADD COLUMN PND_MENOS_VENC29_U03M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC59_U03M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC89_U03M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC90M_U03M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_VIGENTEH_U03M            DOUBLE NULL,
	ADD COLUMN PND_MENOS_SALDOTOTAL_U03M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC1M_U03M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC30M_U03M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC60M_U03M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC29_U03M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC59_U03M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC89_U03M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC90M_U03M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VIGENTEH_U03M        DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC1M_U03M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC30M_U03M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC60M_U03M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_L_U03M     DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_L_U03M     DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_CEIL_U03M  DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_CEIL_U03M  DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_FLOOR_U03M DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_FLOOR_U03M DOUBLE NULL;

--  PND_MENOS03M: VALORES
UPDATE LGG_MCV_PRUEBA_HI T1 
SET PND_MENOS_VENC29_U03M              = PND_MENOS03M * VENCIDO1A29         ,
    PND_MENOS_VENC59_U03M              = PND_MENOS03M * VENCIDO30A59        ,
    PND_MENOS_VENC89_U03M              = PND_MENOS03M * VENCIDO60A89        ,
	PND_MENOS_VENC90M_U03M             = PND_MENOS03M * VENCIDO90MAS        ,
	PND_MENOS_VIGENTEH_U03M            = PND_MENOS03M * VIGENTEH            ,
    PND_MENOS_SALDOTOTAL_U03M          = PND_MENOS03M * SALDOTOTAL          ,
    PND_MENOS_VENC1M_U03M              = PND_MENOS03M * VENCIDO1MAS         ,
    PND_MENOS_VENC30M_U03M             = PND_MENOS03M * VENCIDO30MAS        ,
    PND_MENOS_VENC60M_U03M             = PND_MENOS03M * VENCIDO60MAS        ,
    PND_MENOS_PCT_VENC29_U03M          = PND_MENOS03M * PCT_VENC29          ,
    PND_MENOS_PCT_VENC59_U03M          = PND_MENOS03M * PCT_VENC59          ,
    PND_MENOS_PCT_VENC89_U03M          = PND_MENOS03M * PCT_VENC89          ,
    PND_MENOS_PCT_VENC90M_U03M         = PND_MENOS03M * PCT_VENC90M         ,
    PND_MENOS_PCT_VIGENTEH_U03M        = PND_MENOS03M * PCT_VIGENTEH        ,
    PND_MENOS_PCT_VENC1M_U03M          = PND_MENOS03M * PCT_VENC1M          ,
    PND_MENOS_PCT_VENC30M_U03M         = PND_MENOS03M * PCT_VENC30M         ,
    PND_MENOS_PCT_VENC60M_U03M         = PND_MENOS03M * PCT_VENC60M         ,
    PND_MENOS_AVG_HI_CALCAR_L_U03M     = PND_MENOS03M * AVG_HI_CALCAR_L     ,
    PND_MENOS_MAX_HI_CALCAR_L_U03M     = PND_MENOS03M * MAX_HI_CALCAR_L     ,
    PND_MENOS_AVG_HI_CALCAR_CEIL_U03M  = PND_MENOS03M * AVG_HI_CALCAR_CEIL  ,
    PND_MENOS_MAX_HI_CALCAR_CEIL_U03M  = PND_MENOS03M * MAX_HI_CALCAR_CEIL  ,
    PND_MENOS_MAX_HI_CALCAR_FLOOR_U03M = PND_MENOS03M * MAX_HI_CALCAR_FLOOR ,
    PND_MENOS_AVG_HI_CALCAR_FLOOR_U03M = PND_MENOS03M * AVG_HI_CALCAR_FLOOR ;
	
--  PND_MENOS06M: COLUMNAS
ALTER TABLE  LGG_MCV_PRUEBA_HI
	ADD COLUMN PND_MENOS_VENC29_U06M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC59_U06M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC89_U06M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC90M_U06M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_VIGENTEH_U06M            DOUBLE NULL,
	ADD COLUMN PND_MENOS_SALDOTOTAL_U06M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC1M_U06M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC30M_U06M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC60M_U06M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC29_U06M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC59_U06M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC89_U06M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC90M_U06M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VIGENTEH_U06M        DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC1M_U06M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC30M_U06M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC60M_U06M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_L_U06M     DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_L_U06M     DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_CEIL_U06M  DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_CEIL_U06M  DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_FLOOR_U06M DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_FLOOR_U06M DOUBLE NULL;

--  PND_MENOS06M: VALORES
UPDATE LGG_MCV_PRUEBA_HI T1 
SET PND_MENOS_VENC29_U06M              = PND_MENOS06M * VENCIDO1A29         ,
    PND_MENOS_VENC59_U06M              = PND_MENOS06M * VENCIDO30A59        ,
    PND_MENOS_VENC89_U06M              = PND_MENOS06M * VENCIDO60A89        ,
	PND_MENOS_VENC90M_U06M             = PND_MENOS06M * VENCIDO90MAS        ,
	PND_MENOS_VIGENTEH_U06M            = PND_MENOS06M * VIGENTEH            ,
    PND_MENOS_SALDOTOTAL_U06M          = PND_MENOS06M * SALDOTOTAL          ,
    PND_MENOS_VENC1M_U06M              = PND_MENOS06M * VENCIDO1MAS         ,
    PND_MENOS_VENC30M_U06M             = PND_MENOS06M * VENCIDO30MAS        ,
    PND_MENOS_VENC60M_U06M             = PND_MENOS06M * VENCIDO60MAS        ,
    PND_MENOS_PCT_VENC29_U06M          = PND_MENOS06M * PCT_VENC29          ,
    PND_MENOS_PCT_VENC59_U06M          = PND_MENOS06M * PCT_VENC59          ,
    PND_MENOS_PCT_VENC89_U06M          = PND_MENOS06M * PCT_VENC89          ,
    PND_MENOS_PCT_VENC90M_U06M         = PND_MENOS06M * PCT_VENC90M         ,
    PND_MENOS_PCT_VIGENTEH_U06M        = PND_MENOS06M * PCT_VIGENTEH        ,
    PND_MENOS_PCT_VENC1M_U06M          = PND_MENOS06M * PCT_VENC1M          ,
    PND_MENOS_PCT_VENC30M_U06M         = PND_MENOS06M * PCT_VENC30M         ,
    PND_MENOS_PCT_VENC60M_U06M         = PND_MENOS06M * PCT_VENC60M         ,
    PND_MENOS_AVG_HI_CALCAR_L_U06M     = PND_MENOS06M * AVG_HI_CALCAR_L     ,
    PND_MENOS_MAX_HI_CALCAR_L_U06M     = PND_MENOS06M * MAX_HI_CALCAR_L     ,
    PND_MENOS_AVG_HI_CALCAR_CEIL_U06M  = PND_MENOS06M * AVG_HI_CALCAR_CEIL  ,
    PND_MENOS_MAX_HI_CALCAR_CEIL_U06M  = PND_MENOS06M * MAX_HI_CALCAR_CEIL  ,
    PND_MENOS_MAX_HI_CALCAR_FLOOR_U06M = PND_MENOS06M * MAX_HI_CALCAR_FLOOR ,
    PND_MENOS_AVG_HI_CALCAR_FLOOR_U06M = PND_MENOS06M * AVG_HI_CALCAR_FLOOR ;

--  PND_MENOS12M: COLUMNAS
ALTER TABLE  LGG_MCV_PRUEBA_HI
	ADD COLUMN PND_MENOS_VENC29_U12M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC59_U12M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC89_U12M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC90M_U12M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_VIGENTEH_U12M            DOUBLE NULL,
	ADD COLUMN PND_MENOS_SALDOTOTAL_U12M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC1M_U12M              DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC30M_U12M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_VENC60M_U12M             DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC29_U12M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC59_U12M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC89_U12M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC90M_U12M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VIGENTEH_U12M        DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC1M_U12M          DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC30M_U12M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_PCT_VENC60M_U12M         DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_L_U12M     DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_L_U12M     DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_CEIL_U12M  DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_CEIL_U12M  DOUBLE NULL,
	ADD COLUMN PND_MENOS_MAX_HI_CALCAR_FLOOR_U12M DOUBLE NULL,
	ADD COLUMN PND_MENOS_AVG_HI_CALCAR_FLOOR_U12M DOUBLE NULL;

--  PND_MENOS12M: VALORES
UPDATE LGG_MCV_PRUEBA_HI T1 
SET PND_MENOS_VENC29_U12M              = PND_MENOS12M * VENCIDO1A29         ,
    PND_MENOS_VENC59_U12M              = PND_MENOS12M * VENCIDO30A59        ,
    PND_MENOS_VENC89_U12M              = PND_MENOS12M * VENCIDO60A89        ,
	PND_MENOS_VENC90M_U12M             = PND_MENOS12M * VENCIDO90MAS        ,
	PND_MENOS_VIGENTEH_U12M            = PND_MENOS12M * VIGENTEH            ,
    PND_MENOS_SALDOTOTAL_U12M          = PND_MENOS12M * SALDOTOTAL          ,
    PND_MENOS_VENC1M_U12M              = PND_MENOS12M * VENCIDO1MAS         ,
    PND_MENOS_VENC30M_U12M             = PND_MENOS12M * VENCIDO30MAS        ,
    PND_MENOS_VENC60M_U12M             = PND_MENOS12M * VENCIDO60MAS        ,
    PND_MENOS_PCT_VENC29_U12M          = PND_MENOS12M * PCT_VENC29          ,
    PND_MENOS_PCT_VENC59_U12M          = PND_MENOS12M * PCT_VENC59          ,
    PND_MENOS_PCT_VENC89_U12M          = PND_MENOS12M * PCT_VENC89          ,
    PND_MENOS_PCT_VENC90M_U12M         = PND_MENOS12M * PCT_VENC90M         ,
    PND_MENOS_PCT_VIGENTEH_U12M        = PND_MENOS12M * PCT_VIGENTEH        ,
    PND_MENOS_PCT_VENC1M_U12M          = PND_MENOS12M * PCT_VENC1M          ,
    PND_MENOS_PCT_VENC30M_U12M         = PND_MENOS12M * PCT_VENC30M         ,
    PND_MENOS_PCT_VENC60M_U12M         = PND_MENOS12M * PCT_VENC60M         ,
    PND_MENOS_AVG_HI_CALCAR_L_U12M     = PND_MENOS12M * AVG_HI_CALCAR_L     ,
    PND_MENOS_MAX_HI_CALCAR_L_U12M     = PND_MENOS12M * MAX_HI_CALCAR_L     ,
    PND_MENOS_AVG_HI_CALCAR_CEIL_U12M  = PND_MENOS12M * AVG_HI_CALCAR_CEIL  ,
    PND_MENOS_MAX_HI_CALCAR_CEIL_U12M  = PND_MENOS12M * MAX_HI_CALCAR_CEIL  ,
    PND_MENOS_MAX_HI_CALCAR_FLOOR_U12M = PND_MENOS12M * MAX_HI_CALCAR_FLOOR ,
    PND_MENOS_AVG_HI_CALCAR_FLOOR_U12M = PND_MENOS12M * AVG_HI_CALCAR_FLOOR ;		
    
    --  Resumen Crédito
DROP TABLE IF EXISTS LGG_MCV_PRUEBA_VAR_CR_RESUMEN;
CREATE TABLE IF NOT EXISTS LGG_MCV_PRUEBA_VAR_CR_RESUMEN (
-- INFORMACIÓN GENERAL
RFC                      VARCHAR(15),
FOLIO                    VARCHAR(10),
FECHACONSULTA            VARCHAR(6) ,
NUM_CL_ACC               DOUBLE,
NUM_OP_ACC               DOUBLE,
NUM_BRG_R_OP_ACC         DOUBLE,
NUM_BK_R_OP_ACC          DOUBLE,
NUM_BRG_OP_ACC           DOUBLE,
NUM_BK_OP_ACC            DOUBLE,
NUM_BK_R_CL_ACC          DOUBLE,
NUM_BK_CS_OP_ACC         DOUBLE,
NUM_BK_CS_CL_ACC         DOUBLE,
NUM_OTHER_FIN_OP_ACC     DOUBLE,
NUM_BRG_CL_ACC           DOUBLE,
NUM_BRG_R_CL_ACC         DOUBLE,
NUM_OTHER_FIN_CL_ACC     DOUBLE,
NUM_OTHER_FIN_LSG_OP_ACC DOUBLE,
NUM_BRG_CS_OP_ACC        DOUBLE,
NUM_LSE_OP_ACC           DOUBLE,
NUM_BRG_CS_CL_ACC        DOUBLE,
NUM_GBN_CF_CL_ACC        DOUBLE,
NUM_LSE_LSG_OP_ACC       DOUBLE,
PCT_CL_ACC               DOUBLE,
PCT_BRG_R_OP_ACC         DOUBLE,
PCT_BK_R_OP_ACC          DOUBLE,
PCT_BRG_OP_ACC           DOUBLE,
PCT_BK_OP_ACC            DOUBLE,
PCT_BK_R_CL_ACC          DOUBLE,
PCT_BK_CS_OP_ACC         DOUBLE,
PCT_BK_CS_CL_ACC         DOUBLE,
PCT_OTHER_FIN_OP_ACC     DOUBLE,
PCT_BRG_CL_ACC           DOUBLE,
PCT_BRG_R_CL_ACC         DOUBLE,
PCT_OTHER_FIN_CL_ACC     DOUBLE,
PCT_OTHER_FIN_LSG_OP_ACC DOUBLE,
PCT_BRG_CS_OP_ACC        DOUBLE,
PCT_LSE_OP_ACC           DOUBLE,
PCT_BRG_CS_CL_ACC        DOUBLE,
PCT_GBN_CF_CL_ACC        DOUBLE,
PCT_LSE_LSG_OP_ACC       DOUBLE);

ALTER TABLE LGG_MCV_PRUEBA_VAR_CR_RESUMEN ADD INDEX LLAVE(RFC);
ALTER TABLE LGG_MCV_PRUEBA_VAR_CR_RESUMEN ADD INDEX LLAVE1 (FECHACONSULTA);
ALTER TABLE LGG_MCV_PRUEBA_VAR_CR_RESUMEN ADD INDEX LLAVE2(FOLIO);

INSERT INTO  
	 LGG_MCV_PRUEBA_VAR_CR_RESUMEN (RFC, FOLIO, FECHACONSULTA)
SELECT DISTINCT RFC, FOLIO, FECHA
	FROM LGG_MCV_SET_PRUEBA;

UPDATE LGG_MCV_PRUEBA_VAR_CR_RESUMEN T1 
SET 
	NUM_CL_ACC                 = (SELECT COUNT(RFC)           FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'CL_ACC'),
	NUM_OP_ACC                 = (SELECT COUNT(RFC)           FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC'),
	NUM_BRG_R_OP_ACC           = (SELECT SUM(BRG_R)           FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_BK_R_OP_ACC            = (SELECT SUM(BK_R)            FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_BRG_OP_ACC             = (SELECT SUM(BRG)             FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_BK_OP_ACC              = (SELECT SUM(BK)              FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_BK_R_CL_ACC            = (SELECT SUM(BK_R)            FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'CL_ACC' ),
	NUM_BK_CS_OP_ACC           = (SELECT SUM(BK_CS)           FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_BK_CS_CL_ACC           = (SELECT SUM(BK_CS)           FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'CL_ACC' ),
	NUM_OTHER_FIN_OP_ACC       = (SELECT SUM(OTHER_FIN)       FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_BRG_CL_ACC             = (SELECT SUM(BRG)             FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'CL_ACC' ),
	NUM_BRG_R_CL_ACC           = (SELECT SUM(BRG_R)           FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'CL_ACC' ),
	NUM_OTHER_FIN_CL_ACC       = (SELECT SUM(OTHER_FIN)       FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'CL_ACC' ),
	NUM_OTHER_FIN_LSG_OP_ACC   = (SELECT SUM(OTHER_FIN_LSG)   FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_BRG_CS_OP_ACC          = (SELECT SUM(BRG_CS)          FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_LSE_OP_ACC             = (SELECT SUM(LSE)             FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' ),
	NUM_BRG_CS_CL_ACC          = (SELECT SUM(BRG_CS)          FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'CL_ACC' ),
	NUM_GBN_CF_CL_ACC          = (SELECT SUM(GBN_CF)          FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'CL_ACC' ),
	NUM_LSE_LSG_OP_ACC         = (SELECT SUM(LSE_LSG)         FROM LGG_MCV_PRUEBA_CR T2  WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND ESTATUS = 'OP_ACC' );

UPDATE LGG_MCV_PRUEBA_VAR_CR_RESUMEN T1 
SET
PCT_CL_ACC                 = NUM_CL_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BRG_R_OP_ACC           = NUM_BRG_R_OP_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BK_R_OP_ACC            = NUM_BK_R_OP_ACC  / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BRG_OP_ACC             = NUM_BRG_OP_ACC   / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BK_OP_ACC              = NUM_BK_OP_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BK_R_CL_ACC            = NUM_BK_R_CL_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BK_CS_OP_ACC           = NUM_BK_CS_OP_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BK_CS_CL_ACC           = NUM_BK_CS_CL_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_OTHER_FIN_OP_ACC       = NUM_OTHER_FIN_OP_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BRG_CL_ACC             = NUM_BRG_CL_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BRG_R_CL_ACC           = NUM_BRG_R_CL_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_OTHER_FIN_CL_ACC       = NUM_OTHER_FIN_CL_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_OTHER_FIN_LSG_OP_ACC   = NUM_OTHER_FIN_LSG_OP_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BRG_CS_OP_ACC          = NUM_BRG_CS_OP_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_LSE_OP_ACC             = NUM_LSE_OP_ACC / (NUM_OP_ACC + NUM_CL_ACC),
PCT_BRG_CS_CL_ACC          = NUM_BRG_CS_CL_ACC/ (NUM_OP_ACC + NUM_CL_ACC),
PCT_GBN_CF_CL_ACC          = NUM_GBN_CF_CL_ACC  / (NUM_OP_ACC + NUM_CL_ACC),
PCT_LSE_LSG_OP_ACC         = NUM_LSE_LSG_OP_ACC  / (NUM_OP_ACC + NUM_CL_ACC);
											
--  Segmento Historia.
UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET											
T1.MIN_VIGENTEH_12M = (SELECT MIN(VIGENTEH) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS12M IS NOT NULL),																		
T1.MIN_VIGENTEH_03M =(SELECT MIN(VIGENTEH) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS03M IS NOT NULL),
 T1.SUM_VIGENTEH_12M = (SELECT SUM(VIGENTEH) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS12M IS NOT NULL),
AVG_PND_MENOS_PCT_VENC29_12M =  ROUND((SELECT (SUM(PND_MENOS_PCT_VENC29_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6),
AVG_PND_MENOS_AVG_HI_CALCAR_L_12M =  ROUND((SELECT (SUM(PND_MENOS_AVG_HI_CALCAR_L_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6),							
T1.MIN_VIGENTEH_06M = (SELECT MIN(VIGENTEH) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS06M IS NOT NULL),
T1.AVG_PND_MENOS_MAX_HI_CALCAR_L_12M =  ROUND((SELECT (SUM(PND_MENOS_MAX_HI_CALCAR_L_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6),
T1.AVG_PND_MENOS_PCT_VENC29_03M = ROUND((SELECT (SUM(PND_MENOS_PCT_VENC29_U03M)/SUM(PND_MENOS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MENOS03M IS NOT NULL),6),   
T1.AVG_PND_MAS_AVG_HI_CALCAR_L_03M = ROUND((SELECT (SUM(PND_MAS_AVG_HI_CALCAR_L_U03M)/SUM(PND_MAS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS03M IS NOT NULL),6),   
AVG_PND_MENOS_AVG_HI_CALCAR_CEIL_12M =  ROUND((SELECT (SUM(PND_MENOS_AVG_HI_CALCAR_CEIL_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6),	
AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_12M =  ROUND((SELECT (SUM(PND_MENOS_MAX_HI_CALCAR_FLOOR_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6),
AVG_PND_MAS_AVG_HI_CALCAR_CEIL_12M =  ROUND((SELECT (SUM(PND_MAS_AVG_HI_CALCAR_CEIL_U12M)/SUM(PND_MAS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MAS12M IS NOT NULL),6);	

UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET										
AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_12M =  ROUND((SELECT (SUM(PND_MENOS_MAX_HI_CALCAR_CEIL_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6),
T1.SUM_VIGENTEH_03M =(SELECT SUM(VIGENTEH) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS03M IS NOT NULL),
T1.SUM_VIGENTEH_06M = (SELECT SUM(VIGENTEH) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS06M IS NOT NULL),
T1.AVG_PND_MENOS_PCT_VENC29_06M = ROUND((SELECT (SUM(PND_MENOS_PCT_VENC29_U06M)/SUM(PND_MENOS06M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS06M IS NOT NULL),6),   	
T1.AVG_PND_MENOS_AVG_HI_CALCAR_L_06M = ROUND((SELECT (SUM(PND_MENOS_AVG_HI_CALCAR_L_U06M)/SUM(PND_MENOS06M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS06M IS NOT NULL),6),   	
T1.AVG_PND_MENOS_PCT_VENC59_12M =  ROUND((SELECT (SUM(PND_MENOS_PCT_VENC59_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6),	
T1.AVG_PND_MAS_MAX_HI_CALCAR_L_03M = ROUND((SELECT (SUM(PND_MAS_MAX_HI_CALCAR_L_U03M)/SUM(PND_MAS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS03M IS NOT NULL),6),   
T1.AVG_PND_MENOS_AVG_HI_CALCAR_FLOOR_12M =  ROUND((SELECT (SUM(PND_MENOS_AVG_HI_CALCAR_FLOOR_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6);	
									
UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET		
T1.AVG_PND_MENOS_AVG_HI_CALCAR_L_03M = ROUND((SELECT (SUM(PND_MENOS_AVG_HI_CALCAR_L_U03M)/SUM(PND_MENOS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MENOS03M IS NOT NULL),6),   
T1.NUM_VIGENTEH_12M = (SELECT COUNT(VIGENTEH) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MAS12M IS NOT NULL AND  T2.VIGENTEH > 0),	
T1.AVG_PCT_VENC29_06M = (SELECT ROUND(AVG(PCT_VENC29),6) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS06M IS NOT NULL),
T1.AVG_PND_MAS_PCT_VENC29_03M = ROUND((SELECT (SUM(PND_MAS_PCT_VENC29_U03M)/SUM(PND_MAS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS03M IS NOT NULL),6),   
T1.AVG_PND_MENOS_AVG_HI_CALCAR_CEIL_06M = ROUND((SELECT (SUM(PND_MENOS_AVG_HI_CALCAR_CEIL_U06M)/SUM(PND_MENOS06M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS06M IS NOT NULL),6),   	
T1.AVG_PND_MENOS_MAX_HI_CALCAR_L_06M = ROUND((SELECT (SUM(PND_MENOS_MAX_HI_CALCAR_L_U06M)/SUM(PND_MENOS06M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS06M IS NOT NULL),6),   	
T1.AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_06M = ROUND((SELECT (SUM(PND_MAS_MAX_HI_CALCAR_FLOOR_U06M)/SUM(PND_MAS06M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MAS06M IS NOT NULL),6),   	
 T1.NUM_MAX_HI_CALCAR_FLOOR_12M = (SELECT COUNT(MAX_HI_CALCAR_FLOOR) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MAS12M IS NOT NULL AND T2.MAX_HI_CALCAR_FLOOR > 0);
				  
UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET	
T1.AVG_PND_MAS_AVG_HI_CALCAR_L_12M =  ROUND((SELECT (SUM(PND_MAS_AVG_HI_CALCAR_L_U12M)/SUM(PND_MAS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MAS12M IS NOT NULL),6),
T1.AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_03M = ROUND((SELECT (SUM(PND_MENOS_MAX_HI_CALCAR_FLOOR_U03M)/SUM(PND_MENOS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MENOS03M IS NOT NULL),6),   
T1.MAX_VENC29_03M =(SELECT MAX(VENCIDO1A29) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS03M IS NOT NULL),
T1.AVG_PND_MAS_MAX_HI_CALCAR_L_12M =  ROUND((SELECT (SUM(PND_MAS_MAX_HI_CALCAR_L_U12M)/SUM(PND_MAS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MAS12M IS NOT NULL),6),
T1.AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_06M = ROUND((SELECT (SUM(PND_MENOS_MAX_HI_CALCAR_CEIL_U06M)/SUM(PND_MENOS06M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS06M IS NOT NULL),6),   	
T1.AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_03M = ROUND((SELECT (SUM(PND_MAS_MAX_HI_CALCAR_FLOOR_U03M)/SUM(PND_MAS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS03M IS NOT NULL),6),   
T1.AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_12M =  ROUND((SELECT (SUM(PND_MAS_MAX_HI_CALCAR_FLOOR_U12M)/SUM(PND_MAS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MAS12M IS NOT NULL),6);											
UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET		
T1.AVG_PND_MAS_AVG_HI_CALCAR_CEIL_03M = ROUND((SELECT (SUM(PND_MAS_AVG_HI_CALCAR_CEIL_U03M)/SUM(PND_MAS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS03M IS NOT NULL),6),   
T1.AVG_PCT_VENC29_12M = (SELECT ROUND(AVG(PCT_VENC29),6) FROM DBMYMWORK.LGG_MCV_PRUEBA_HI T2
							WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MAS12M IS NOT NULL),									
T1.AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_03M = ROUND((SELECT (SUM(PND_MENOS_MAX_HI_CALCAR_CEIL_U03M)/SUM(PND_MENOS03M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE  T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND T2.PND_MENOS03M IS NOT NULL),6),   
T1.AVG_PND_MENOS_PCT_VENC1M_12M =  ROUND((SELECT (SUM(PND_MENOS_PCT_VENC1M_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6),															
T1.AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_06M = ROUND((SELECT (SUM(PND_MENOS_MAX_HI_CALCAR_FLOOR_U06M)/SUM(PND_MENOS06M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS06M IS NOT NULL),6),   	
T1.AVG_PND_MAS_AVG_HI_CALCAR_L_06M = ROUND((SELECT (SUM(PND_MAS_AVG_HI_CALCAR_L_U06M)/SUM(PND_MAS06M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MAS06M IS NOT NULL),6),
AVG_PND_MENOS_VENC29_12M =  ROUND((SELECT (SUM(PND_MENOS_VENC29_U12M)/SUM(PND_MENOS12M))
										FROM DBMYMWORK.LGG_MCV_PRUEBA_HI AS T2
									WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO AND PND_MENOS12M IS NOT NULL),6);									
--  Segmento Califica.
UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET	MONTHS_ON_FILE_BANKING  = (SELECT IF(MONTHS_ON_FILE_BANKING ='--',NULL,MONTHS_ON_FILE_BANKING )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    BK_DEUDA_CP             = (SELECT IF(BK_DEUDA_CP            ='--',NULL,BK_DEUDA_CP            )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    DEUDA_TOT_CP            = (SELECT IF(DEUDA_TOT_CP           ='--',NULL,DEUDA_TOT_CP           )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    BK12_NUM_EXP_PAIDONTIME = (SELECT IF(BK12_NUM_EXP_PAIDONTIME='--',NULL,BK12_NUM_EXP_PAIDONTIME)  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    DEUDA_TOT               = (SELECT IF(DEUDA_TOT              ='--',NULL,DEUDA_TOT              )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    BK_DEUDA_TOT            = (SELECT IF(BK_DEUDA_TOT           ='--',NULL,BK_DEUDA_TOT           )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    BK12_MAX_CREDIT_AMT     = (SELECT IF(BK12_MAX_CREDIT_AMT    ='--',NULL,BK12_MAX_CREDIT_AMT    )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    NBK_DEUDA_TOT           = (SELECT IF(NBK_DEUDA_TOT          ='--',NULL,NBK_DEUDA_TOT          )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    BK12_DPD_PROM           = (SELECT IF(BK12_DPD_PROM          ='--',NULL,BK12_DPD_PROM          )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    BK_IND_PMOR             = (SELECT IF(BK_IND_PMOR            ='--',NULL,BK_IND_PMOR            )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    12_INST                 = (SELECT IF(12_INST                ='--',NULL,12_INST                )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
    AVG_FD_CALCAR_CEIL      = (SELECT IF(AVG_FD_CALCAR_CEIL     ='--',NULL,AVG_FD_CALCAR_CEIL     )  FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO );

	
	--  Movimiento de Linea
UPDATE LGG_MCV_PRUEBA_VARIABLES T1	
SET  T1.MS_OP = (SELECT MS_OP FROM LGG_MCV_PRUEBA_MOV_LIN T2 WHERE T1.RFC = T2.RFC AND T1.FECHACARTERA = T2.FECHACARTERA ),
	 T1.DS_CL = (SELECT DS_CL FROM LGG_MCV_PRUEBA_MOV_LIN T2 WHERE T1.RFC = T2.RFC AND T1.FECHACARTERA = T2.FECHACARTERA ),
	 T1.DS_OL_CL = (SELECT DS_OL_CL FROM LGG_MCV_PRUEBA_MOV_LIN T2 WHERE T1.RFC = T2.RFC AND T1.FECHACARTERA = T2.FECHACARTERA );
	 
--  Resumen Crédito															
UPDATE LGG_MCV_PRUEBA_VARIABLES T1 
SET
PCT_CL_ACC	              = (SELECT PCT_CL_ACC	              FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BRG_OP_ACC            = (SELECT PCT_BRG_OP_ACC            FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BK_R_OP_ACC           = (SELECT PCT_BK_R_OP_ACC           FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BRG_OP_ACC            = (SELECT PCT_BRG_OP_ACC            FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BK_OP_ACC             = (SELECT PCT_BK_OP_ACC             FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BK_CL_ACC             = (SELECT PCT_BK_CL_ACC             FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BK_R_CL_ACC           = (SELECT PCT_BK_R_CL_ACC           FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BK_CS_OP_ACC          = (SELECT PCT_BK_CS_OP_ACC          FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BK_CS_CL_ACC          = (SELECT PCT_BK_CS_CL_ACC          FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_OTHER_FIN_OP_ACC      = (SELECT PCT_OTHER_FIN_OP_ACC      FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BRG_CL_ACC            = (SELECT PCT_BRG_CL_ACC            FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BRG_R_CL_ACC          = (SELECT PCT_BRG_R_CL_ACC          FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_OTHER_FIN_CL_ACC      = (SELECT PCT_OTHER_FIN_CL_ACC      FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_OTHER_FIN_LSG_OP_ACC  = (SELECT PCT_OTHER_FIN_LSG_OP_ACC  FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BRG_CS_OP_ACC         = (SELECT PCT_BRG_CS_OP_ACC         FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_LSE_LSG_OP_ACC        = (SELECT PCT_LSE_LSG_OP_ACC        FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_LSE_OP_ACC            = (SELECT PCT_LSE_OP_ACC            FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_BRG_CS_CL_ACC         = (SELECT PCT_BRG_CS_CL_ACC         FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),	
PCT_GBN_CF_CL_ACC         = (SELECT PCT_GBN_CF_CL_ACC         FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO ),
PCT_BRG_R_OP_ACC          = (SELECT PCT_BRG_R_OP_ACC          FROM DBMYMWORK.LGG_MCV_PRUEBA_VAR_CR_RESUMEN T2 WHERE T1.RFC = T2.RFC AND T1.FOLIO = T2.FOLIO );	




























									