%hive

DROP TABLE IF EXISTS JAT_MCV_UNIVERSO_LINEAS_RFC_201901;

CREATE TABLE JAT_MCV_UNIVERSO_LINEAS_RFC_201901
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MCV/UNIVERSO_LINEAS_RFC/JAT_MCV_UNIVERSO_LINEAS_RFC_201901' AS
SELECT
    DISTINCT
    T1.RFC,
    T1.LINEA
FROM
    DBRISKDATAMART.TBL_CARTERACREDITICIA T1
INNER JOIN
    (SELECT DISTINCT RFC FROM DBRISKDATAMART.TBL_CARTERACREDITICIA WHERE MIS <> 0 AND FECHA = '${FECHA_CALIFICACION}') T2
ON
    T1.RFC = T2.RFC
WHERE
    T1.MIS <> 0
    AND T1.RFC = T2.RFC
;

SELECT COUNT(*) FROM JAT_MCV_UNIVERSO_LINEAS_RFC_201901;