%hive

DROP TABLE IF EXISTS JEA_MCV_UNIVERSO_LLAVES;

CREATE TABLE IF NOT EXISTS JEA_MCV_UNIVERSO_LLAVES
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/JEA/dbmymwork/JEA_MCV_UNIVERSO_LLAVES' AS

SELECT 
	A.LLAVE_UNIVERSAL_20 as llave_universal,
	A.RFC,
	A.FECHA, 
	A.TIPO_DE_CREDITO ,
	A.cartera_vencida,
	A.dias_atraso,
	A.mesesdc
FROM RSS_MCV_CARTERA_CREDITICIA_LINEA A 
INNER JOIN JEA_MCV_UNIVERSO_RFC_LLAVES B
ON A.RFC = B.RFC AND A.fecha = B.fecha




