%hive

DROP TABLE IF EXISTS JEA_MCV_UNIVERSO_RFC_LLAVES;

CREATE TABLE IF NOT EXISTS JEA_MCV_UNIVERSO_RFC_LLAVES
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/JEA/dbmymwork/JEA_MCV_UNIVERSO_RFC_LLAVES' AS

SELECT DISTINCT
	A.FECHA,
	A.RFC
FROM RSS_MCV_CARTERA_CREDITICIA_LINEA A 
INNER JOIN RSS_MCV_COLOCACION_PEQUE B
ON A.LLAVE_UNIVERSAL_20 = B.llave_universal AND A.fecha = B.fecha


