DROP TABLE IF EXISTS JEA_MCV_UNIVERSO_WDW;

CREATE TABLE IF NOT EXISTS
JEA_MCV_UNIVERSO_WDW 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/JEA/dbmymwork/JEA_MCV_UNIVERSO_WDW' AS
SELECT
  A.RFC,  
  A.LLAVE_UNIVERSAL_20,
  A.FECHA,
  A.CLIENTE,
  A.LINEA,
  A.TIPO_DE_CREDITO,
  A.MESESDC,
  A.MONTO_LINEA,
  A.DIAS_ATRASO,
  A.CCI,
  A.SOBREGIRO,
  A.INTERCOMPANIA,
  A.CARTERA_ADQUIRIDA,
  A.REESTRUCTURA,
  A.REVOLVENTE,
  CASE
    WHEN COALESCE(DIAS_ATRASO, 0) = 0 THEN 0
    WHEN DIAS_ATRASO BETWEEN 1 AND 29 THEN 1
    WHEN DIAS_ATRASO BETWEEN 30 AND 59 THEN 2
    WHEN DIAS_ATRASO BETWEEN 60 AND 89 THEN 3
    WHEN DIAS_ATRASO >= 89 THEN 4
    ELSE 5
  END AS BUCKET,
  CASE 
    WHEN MONTO_LINEA <= 8000000 THEN 0
    WHEN MONTO_LINEA > 8000000 AND MONTO_LINEA <= 15000000 THEN 1
    WHEN MONTO_LINEA > 15000000 THEN 2
    ELSE 3
  END AS MONTO_CLS,
  CARTERA_VENCIDA,
  CASE
      WHEN COALESCE(A.CARTERA_VENCIDA, 0) = 0 THEN 0
      ELSE 1
  END AS SDOVDO_M0,
  CASE
      WHEN COALESCE(A.CARTERA_VENCIDA, 0) = 0 
          AND COALESCE(B.CARTERA_VENCIDA, 0) = 0 THEN 0
      ELSE 1
  END AS SDOVDO_M1,
  CASE
      WHEN COALESCE(A.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(B.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(C.CARTERA_VENCIDA, 0) = 0 THEN 0
      ELSE 1
  END AS SDOVDO_M2,
  CASE
      WHEN COALESCE(A.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(B.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(C.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(D.CARTERA_VENCIDA, 0) = 0 THEN 0
      ELSE 1
  END AS SDOVDO_M3,
  CASE
     WHEN COALESCE(A.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(B.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(C.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(D.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(E.CARTERA_VENCIDA, 0) = 0 THEN 0
      ELSE 1
  END AS SDOVDO_M4,
  CASE
      WHEN COALESCE(A.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(B.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(C.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(D.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(E.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(F.CARTERA_VENCIDA, 0) = 0 THEN 0
      ELSE 1
  END AS SDOVDO_M5,
  CASE
      WHEN COALESCE(A.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(B.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(C.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(D.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(E.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(F.CARTERA_VENCIDA, 0) = 0
          AND COALESCE(G.CARTERA_VENCIDA, 0) = 0 THEN 0
      ELSE 1
  END AS SDOVDO_M6
FROM RSS_MCV_PREUNIVERSO A
LEFT JOIN  RSS_MCV_UNIVERSO_LLAVES B  
  ON A.LLAVE_UNIVERSAL_20 = B.llave_universal AND A.MESESDC + 1 = B.MESESDC
LEFT JOIN  RSS_MCV_UNIVERSO_LLAVES C  
  ON A.LLAVE_UNIVERSAL_20 = C.llave_universal AND A.MESESDC + 2 = C.MESESDC
LEFT JOIN  RSS_MCV_UNIVERSO_LLAVES D
  ON A.LLAVE_UNIVERSAL_20 = D.llave_universal AND A.MESESDC + 3 = D.MESESDC
LEFT JOIN  RSS_MCV_UNIVERSO_LLAVES E  
  ON A.LLAVE_UNIVERSAL_20 = E.llave_universal AND A.MESESDC + 4 = E.MESESDC
LEFT JOIN  RSS_MCV_UNIVERSO_LLAVES F  
  ON A.LLAVE_UNIVERSAL_20 = F.llave_universal AND A.MESESDC + 5 = F.MESESDC
LEFT JOIN  RSS_MCV_UNIVERSO_LLAVES G  
  ON A.LLAVE_UNIVERSAL_20 = G.llave_universal AND G.MESESDC + 6 = G.MESESDC
GROUP BY A.RFC, A.FECHA;