%hive
DROP TABLE IF EXISTS RSS_MCV_PREUNIVERSO;

CREATE TABLE IF NOT EXISTS RSS_MCV_PREUNIVERSO AS
SELECT 
  A.*

FROM RSS_MCV_CARTERA_CREDITICIA_LINEA  A

INNER JOIN RSS_MCV_UNIVERSO_LLAVES B
ON A.LLAVE_UNIVERSAL_20 = B.llaveuniversal AND A.fecha = B.fecha;