%hive
ROP TABLE IF EXISTS JAT_MCV_UNIVERSO_LINEAS_RFC_201901;

CREATE TABLE JAT_MCV_UNIVERSO_LINEAS_RFC_201901
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MCV/UNIVERSO_LINEAS_RFC/JAT_MCV_UNIVERSO_LINEAS_RFC_201901' AS
SELECT