%hive
DROP TABLE IF EXISTS RSS_MCV_CATALOGO_NO_REVOLVENTE;

CREATE TABLE IF NOT EXISTS RSS_MCV_CATALOGO_NO_REVOLVENTE 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MCV/RSS_MCV_CATALOGO_NO_REVOLVENTE' AS
SELECT DISTINCT TIPO_DE_CREDITO
FROM RSS_MCV_UNIVERSO_LLAVES a
WHERE TIPO_DE_CREDITO IN (
    SELECT DISTINCT 
      descripcion_del_tipo_de_credito
    FROM dbriskdatamart.MZM_MYM_CATALOGO_LINEAS_ENE2019
    WHERE credito_revolvente = 'No'
  ) 
UNION 
SELECT DISTINCT TIPO_DE_CREDITO
FROM RSS_MCV_UNIVERSO_LLAVES a
WHERE TIPO_DE_CREDITO IN (
    SELECT DISTINCT 
      abreviacion
    FROM dbriskdatamart.MZM_MYM_CATALOGO_LINEAS_ENE2019
    WHERE credito_revolvente = 'No'
  )   
UNION  
SELECT 
  'Simple' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'ARRENDAMIENTO PURO' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'A. PURO' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'A. FIN' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'Credito' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'ACSSGR PE NAFIN' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'ARRENDAMIENTO FINANCIERO' AS TIPO_DE_CREDITO
UNION
SELECT
  'ARRENDAMIENTO PURO CAPITALIZABLE' AS TIPO_DE_CREDITO
UNION
SELECT
  'ARRENDAMIENTO PURO FINANCIERO' AS TIPO_DE_CREDITO
 UNION
SELECT
  'ARRENDAMIENTO FINANCIERO (ENT FINANC.) PROVIENE DE TCC' AS TIPO_DE_CREDITO
UNION
SELECT
  'ARRENDAMIENTO FINANCIERO 502 (ENT FINANCIERAS)' AS TIPO_DE_CREDITO
UNION
SELECT 
  'ARRENDAMIENTO FINANCIERO' AS TIPO_DE_CREDITO
UNION
SELECT
  'ARRENDAMIENTO FINANCIERO 502' AS TIPO_DE_CREDITO
UNION
SELECT
  'CARTERA DE ARREN. POR BIENES DE CONSUMO' AS TIPO_DE_CREDITO
UNION
SELECT
  'CREDITO AUTOREGIO ARREN.' AS TIPO_DE_CREDITO
UNION
SELECT
  'ARRENDAMIENTO FINANCIERO (PROVIENE DE TCC)' AS TIPO_DE_CREDITO
UNION
SELECT
'ARRENDAMIENTO FINANCIERO 502' AS TIPO_DE_CREDITO
UNION
SELECT
'ARRENDAMIENTO FINANCIERO 502 (ENT FINANCIERAS)' AS TIPO_DE_CREDITO
UNION
SELECT
'ARRENDAMIENTO FINANCIERO AL COMERCIO' AS TIPO_DE_CREDITO
UNION
SELECT
'ARRENDAMIENTO PURO CAPITALIZABLE' AS TIPO_DE_CREDITO
UNION
SELECT
'ARRENDAMIENTO PURO CAPITALIZABLE (PROVIENE DE TCC)' AS TIPO_DE_CREDITO
UNION
SELECT
'ARRENDAMIENTO PURO FINANCIERO' AS TIPO_DE_CREDITO
UNION
SELECT
'AUTO LEASING PLUS' AS TIPO_DE_CREDITO
UNION
SELECT
'AUTOREGIO P.MORALES (SIMPLE CON GTIA.PRENDARIA)' AS TIPO_DE_CREDITO
UNION
SELECT
'REESTRUCTURA DE ARREND. AL COMERCIO' AS TIPO_DE_CREDITO
UNION
SELECT
'REESTRUCTURAS JUDICIAL AL COMERCIO' AS TIPO_DE_CREDITO
UNION
SELECT
'SEGURO ACS AUTOPRESTO' AS TIPO_DE_CREDITO
UNION
SELECT
'AUTOREGIO PERSONA MORAL (REVOLVENTE)' AS TIPO_DE_CREDITO


  
