%hive
DROP TABLE IF EXISTS RSS_MCV_PEQUE_VAR_CR_CL_ACC_201902;

CREATE TABLE  RSS_MCV_PEQUE_VAR_CR_CL_ACC_201902(

folio  VARCHAR(510) ,
rfc           VARCHAR(510)

)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MCV/RSS_MCV_PEQUE_VAR_CR_CL_ACC_201902' ;
INSERT INTO  MZM_MCV_VAR_CR_CL_ACC_201902	
	
SELECT  folio , rfc 
FROM dbriskdatamart.MZM_MCV_CREDITOS_ACTIVOS_201902 a
LEFT JOIN dbriskdatamart.MZM_MCV_UNIVERSO_MODELADO_201902 b
on a.folio = b.FOLIORESPUESTABC and a.rfc=b.rfc
where fecha >=201607 ;