
DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO;
CREATE TABLE IF NOT EXISTS DBMYMWORK.JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO AS

SELECT 
RFC, FECHA, MESESDC, SUM(SALDO) AS SALDO 
FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA GROUP BY 1,2,3;

CREATE INDEX DBMYMWORK_JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO_RFC 
ON DBMYMWORK.JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO (RFC);

CREATE INDEX DBMYMWORK_JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO_FECHA 
ON DBMYMWORK.JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO (FECHA);

CREATE INDEX DBMYMWORK_JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO_MESESDC 
ON DBMYMWORK.JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO (MESESDC);

CREATE UNIQUE INDEX DBMYMWORK_JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO_FECHA_RFC 
ON DBMYMWORK.JEA_MCV_CARTERA_COMERCIAL_RFC_SALDO (RFC, FECHA);