%hive

DROP TABLE IF EXISTS BTDC_MOVLINEAS;
CREATE TABLE BTDC_MOVLINEAS
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/BTDC_MOVLINEAS' AS

SELECT 
ANIOMES,
CREDITO,
LIMITECREDITOCIERRE,
MONTOMINIMOT0,
MONTOMINIMOT1,
MONTOMINIMOT2,
MONTOMINIMOT3,
MONTOMINIMOT4,
MONTOMINIMOT5,
MONTOMINIMOT6,
PAGOREALIZADOT0,
PAGOREALIZADOT1,
PAGOREALIZADOT2,
PAGOREALIZADOT3,
PAGOREALIZADOT4,
PAGOREALIZADOT5,
PAGOREALIZADOT6,
FECHAAPERTURA,
APERTURAPRIMERCREDITO,
PRODUCTO,
MEDIOSBLOQUEADOS

FROM dbriskdatamart.tbl_reservas_revolvente
WHERE TIPOLINEA = 'TARJETA DE CREDITO BANREGIO.';