%hive
DROP TABLE IF EXISTS BTDC_UNIVERSO;
CREATE TABLE BTDC_UNIVERSO
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/BTDC_UNIVERSO' AS


SELECT 
CREDITO,
CLIENTE,
FECHA,
DIAS_ATRASO,
SALDO,
CARTERA_VENCIDA,
CLASIFICACION,
MONTO_LINEA,
MONTO_ORIGINAL

FROM dbriskdatamart.Tbl_CarteraCrediticia

WHERE tipo_de_credito = 'TARJETA DE CREDITO BANREGIO.';