%hive

DROP TABLE IF EXISTS dbriskdatamart.JAT_MCV_VAR_HI__${FECHA_CALIFICACION};

CREATE TABLE dbriskdatamart.JAT_MCV_VAR_HI__${FECHA_CALIFICACION}
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MZM/MCV/JAT_MCV_VAR_HI__${FECHA_CALIFICACION}' AS

SELECT
    RFC,
    FOLIO,
    FECHACONSULTA,
    
--  PERIODO DE 1 A 29 DÍAS VENCIDOS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS MAX_VENC29_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS MAX_VENC29_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS MAX_VENC29_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS MIN_VENC29_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS MIN_VENC29_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS MIN_VENC29_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS AVG_VENC29_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS AVG_VENC29_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS AVG_VENC29_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_VENC29_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_VENC29_03M,
    ROUND(SUM(PND_MENOS_VENC29_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_VENC29_06M,
    ROUND(SUM(PND_MENOS_VENC29_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_VENC29_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_VENC29_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_VENC29_03M,
    ROUND(SUM(PND_MAS_VENC29_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_VENC29_06M,
    ROUND(SUM(PND_MAS_VENC29_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_VENC29_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND VENCIDO1A29 > 0 THEN 1 ELSE NULL END) AS NUM_VENC29_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND VENCIDO1A29 > 0 THEN 1 ELSE NULL END) AS NUM_VENC29_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND VENCIDO1A29 > 0 THEN 1 ELSE NULL END) AS NUM_VENC29_12M,
    
--  PERIODO DE 30 A 59 DÍAS VENCIDOS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS MAX_VENC59_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS MAX_VENC59_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS MAX_VENC59_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS MIN_VENC59_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS MIN_VENC59_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS MIN_VENC59_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS AVG_VENC59_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS AVG_VENC59_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS AVG_VENC59_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_VENC59_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_VENC59_03M,
    ROUND(SUM(PND_MENOS_VENC59_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_VENC59_06M,
    ROUND(SUM(PND_MENOS_VENC59_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_VENC59_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_VENC59_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_VENC59_03M,
    ROUND(SUM(PND_MAS_VENC59_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_VENC59_06M,
    ROUND(SUM(PND_MAS_VENC59_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_VENC59_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND VENCIDO30A59 > 0 THEN 1 ELSE NULL END) AS NUM_VENC59_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND VENCIDO30A59 > 0 THEN 1 ELSE NULL END) AS NUM_VENC59_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND VENCIDO30A59 > 0 THEN 1 ELSE NULL END) AS NUM_VENC59_12M,
    
--  PERIODO DE 60 A 89 DÍAS VENCIDOS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS MAX_VENC89_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS MAX_VENC89_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS MAX_VENC89_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS MIN_VENC89_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS MIN_VENC89_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS MIN_VENC89_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS AVG_VENC89_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS AVG_VENC89_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS AVG_VENC89_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_VENC89_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_VENC89_03M,
    ROUND(SUM(PND_MENOS_VENC89_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_VENC89_06M,
    ROUND(SUM(PND_MENOS_VENC89_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_VENC89_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_VENC89_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_VENC89_03M,
    ROUND(SUM(PND_MAS_VENC89_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_VENC89_06M,
    ROUND(SUM(PND_MAS_VENC89_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_VENC89_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND VENCIDO60A89 > 0 THEN 1 ELSE NULL END) AS NUM_VENC89_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND VENCIDO60A89 > 0 THEN 1 ELSE NULL END) AS NUM_VENC89_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND VENCIDO60A89 > 0 THEN 1 ELSE NULL END) AS NUM_VENC89_12M,
    
--  PERIODO DE 90 MAS DÍAS VENCIDOS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS MAX_VENC90M_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS MAX_VENC90M_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS MAX_VENC90M_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS MIN_VENC90M_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS MIN_VENC90M_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS MIN_VENC90M_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS AVG_VENC90M_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS AVG_VENC90M_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS AVG_VENC90M_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_VENC90M_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_VENC90M_03M,
    ROUND(SUM(PND_MENOS_VENC90M_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_VENC90M_06M,
    ROUND(SUM(PND_MENOS_VENC90M_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_VENC90M_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_VENC90M_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_VENC90M_03M,
    ROUND(SUM(PND_MAS_VENC90M_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_VENC90M_06M,
    ROUND(SUM(PND_MAS_VENC90M_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_VENC90M_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND VENCIDO90MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENC90M_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND VENCIDO90MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENC90M_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND VENCIDO90MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENC90M_12M,

--  PERIODO VIGENTE
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS MAX_VIGENTEH_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS MAX_VIGENTEH_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS MAX_VIGENTEH_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS MIN_VIGENTEH_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS MIN_VIGENTEH_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS MIN_VIGENTEH_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS AVG_VIGENTEH_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS AVG_VIGENTEH_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS AVG_VIGENTEH_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_VIGENTEH_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_VIGENTEH_03M,
    ROUND(SUM(PND_MENOS_VIGENTEH_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_VIGENTEH_06M,
    ROUND(SUM(PND_MENOS_VIGENTEH_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_VIGENTEH_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_VIGENTEH_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_VIGENTEH_03M,
    ROUND(SUM(PND_MAS_VIGENTEH_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_VIGENTEH_06M,
    ROUND(SUM(PND_MAS_VIGENTEH_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_VIGENTEH_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND VIGENTEH > 0 THEN 1 ELSE NULL END) AS NUM_VIGENTEH_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND VIGENTEH > 0 THEN 1 ELSE NULL END) AS NUM_VIGENTEH_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND VIGENTEH > 0 THEN 1 ELSE NULL END) AS NUM_VIGENTEH_12M,

--  PORCENTAJE VENCIDO 1 A 29 DÍAS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS MAX_PCT_VENC29_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS MAX_PCT_VENC29_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS MAX_PCT_VENC29_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS MIN_PCT_VENC29_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS MIN_PCT_VENC29_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS MIN_PCT_VENC29_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS AVG_PCT_VENC29_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS AVG_PCT_VENC29_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC29 ELSE NULL END) AS AVG_PCT_VENC29_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_PCT_VENC29_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_PCT_VENC29_03M,
    ROUND(SUM(PND_MENOS_PCT_VENC29_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_PCT_VENC29_06M,
    ROUND(SUM(PND_MENOS_PCT_VENC29_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_PCT_VENC29_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_PCT_VENC29_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_PCT_VENC29_03M,
    ROUND(SUM(PND_MAS_PCT_VENC29_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_PCT_VENC29_06M,
    ROUND(SUM(PND_MAS_PCT_VENC29_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_PCT_VENC29_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND PCT_VENC29 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC29_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND PCT_VENC29 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC29_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND PCT_VENC29 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC29_12M,
    
--  PORCENTAJE VENCIDO 30 A 59 DÍAS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS MAX_PCT_VENC59_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS MAX_PCT_VENC59_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS MAX_PCT_VENC59_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS MIN_PCT_VENC59_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS MIN_PCT_VENC59_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS MIN_PCT_VENC59_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS AVG_PCT_VENC59_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS AVG_PCT_VENC59_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC59 ELSE NULL END) AS AVG_PCT_VENC59_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_PCT_VENC59_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_PCT_VENC59_03M,
    ROUND(SUM(PND_MENOS_PCT_VENC59_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_PCT_VENC59_06M,
    ROUND(SUM(PND_MENOS_PCT_VENC59_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_PCT_VENC59_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_PCT_VENC59_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_PCT_VENC59_03M,
    ROUND(SUM(PND_MAS_PCT_VENC59_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_PCT_VENC59_06M,
    ROUND(SUM(PND_MAS_PCT_VENC59_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_PCT_VENC59_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND PCT_VENC59 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC59_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND PCT_VENC59 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC59_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND PCT_VENC59 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC59_12M,

--  PORCENTAJE VENCIDO 60 A 89 DÍAS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS MAX_PCT_VENC89_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS MAX_PCT_VENC89_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS MAX_PCT_VENC89_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS MIN_PCT_VENC89_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS MIN_PCT_VENC89_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS MIN_PCT_VENC89_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS AVG_PCT_VENC89_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS AVG_PCT_VENC89_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC89 ELSE NULL END) AS AVG_PCT_VENC89_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_PCT_VENC89_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_PCT_VENC89_03M,
    ROUND(SUM(PND_MENOS_PCT_VENC89_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_PCT_VENC89_06M,
    ROUND(SUM(PND_MENOS_PCT_VENC89_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_PCT_VENC89_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_PCT_VENC89_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_PCT_VENC89_03M,
    ROUND(SUM(PND_MAS_PCT_VENC89_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_PCT_VENC89_06M,
    ROUND(SUM(PND_MAS_PCT_VENC89_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_PCT_VENC89_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND PCT_VENC89 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC89_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND PCT_VENC89 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC89_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND PCT_VENC89 > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC89_12M,
    
--  PORCENTAJE VENCIDO 90 A MÁS DÍAS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS MAX_PCT_VENC90M_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS MAX_PCT_VENC90M_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS MAX_PCT_VENC90M_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS MIN_PCT_VENC90M_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS MIN_PCT_VENC90M_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS MIN_PCT_VENC90M_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS AVG_PCT_VENC90M_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS AVG_PCT_VENC90M_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC90M ELSE NULL END) AS AVG_PCT_VENC90M_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_PCT_VENC90M_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_PCT_VENC90M_03M,
    ROUND(SUM(PND_MENOS_PCT_VENC90M_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_PCT_VENC90M_06M,
    ROUND(SUM(PND_MENOS_PCT_VENC90M_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_PCT_VENC90M_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_PCT_VENC90M_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_PCT_VENC90M_03M,
    ROUND(SUM(PND_MAS_PCT_VENC90M_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_PCT_VENC90M_06M,
    ROUND(SUM(PND_MAS_PCT_VENC90M_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_PCT_VENC90M_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND PCT_VENC90M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC90M_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND PCT_VENC90M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC90M_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND PCT_VENC90M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC90M_12M,    
    
--  PORCENTAJE VIGENTE
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS MAX_PCT_VIGENTEH_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS MAX_PCT_VIGENTEH_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS MAX_PCT_VIGENTEH_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS MIN_PCT_VIGENTEH_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS MIN_PCT_VIGENTEH_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS MIN_PCT_VIGENTEH_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS AVG_PCT_VIGENTEH_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS AVG_PCT_VIGENTEH_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VIGENTEH ELSE NULL END) AS AVG_PCT_VIGENTEH_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_PCT_VIGENTEH_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_PCT_VIGENTEH_03M,
    ROUND(SUM(PND_MENOS_PCT_VIGENTEH_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_PCT_VIGENTEH_06M,
    ROUND(SUM(PND_MENOS_PCT_VIGENTEH_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_PCT_VIGENTEH_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_PCT_VIGENTEH_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_PCT_VIGENTEH_03M,
    ROUND(SUM(PND_MAS_PCT_VIGENTEH_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_PCT_VIGENTEH_06M,
    ROUND(SUM(PND_MAS_PCT_VIGENTEH_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_PCT_VIGENTEH_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND PCT_VIGENTEH > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VIGENTEH_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND PCT_VIGENTEH > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VIGENTEH_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND PCT_VIGENTEH > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VIGENTEH_12M,

--  PERIODO 1 A MÁS DÍAS VENCIDOS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS MAX_VENCIDO1MAS_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS MAX_VENCIDO1MAS_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS MAX_VENCIDO1MAS_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS MIN_VENCIDO1MAS_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS MIN_VENCIDO1MAS_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS MIN_VENCIDO1MAS_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS AVG_VENCIDO1MAS_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS AVG_VENCIDO1MAS_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO1MAS ELSE NULL END) AS AVG_VENCIDO1MAS_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_VENC1M_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_VENCIDO1MAS_03M,
    ROUND(SUM(PND_MENOS_VENC1M_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_VENCIDO1MAS_06M,
    ROUND(SUM(PND_MENOS_VENC1M_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_VENCIDO1MAS_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_VENC1M_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_VENCIDO1MAS_03M,
    ROUND(SUM(PND_MAS_VENC1M_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_VENCIDO1MAS_06M,
    ROUND(SUM(PND_MAS_VENC1M_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_VENCIDO1MAS_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND VENCIDO1MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO1MAS_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND VENCIDO1MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO1MAS_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND VENCIDO1MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO1MAS_12M,
    
--  PERIODO 30 A MÁS DÍAS VENCIDO
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS MAX_VENCIDO30MAS_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS MAX_VENCIDO30MAS_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS MAX_VENCIDO30MAS_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS MIN_VENCIDO30MAS_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS MIN_VENCIDO30MAS_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS MIN_VENCIDO30MAS_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS AVG_VENCIDO30MAS_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS AVG_VENCIDO30MAS_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO30MAS ELSE NULL END) AS AVG_VENCIDO30MAS_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_VENC30M_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_VENCIDO30MAS_03M,
    ROUND(SUM(PND_MENOS_VENC30M_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_VENCIDO30MAS_06M,
    ROUND(SUM(PND_MENOS_VENC30M_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_VENCIDO30MAS_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_VENC30M_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_VENCIDO30MAS_03M,
    ROUND(SUM(PND_MAS_VENC30M_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_VENCIDO30MAS_06M,
    ROUND(SUM(PND_MAS_VENC30M_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_VENCIDO30MAS_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND VENCIDO30MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO30MAS_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND VENCIDO30MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO30MAS_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND VENCIDO30MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO30MAS_12M,

--  PERIODO 60 A MÁS DÍAS VENCIDOS
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS MAX_VENCIDO60MAS_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS MAX_VENCIDO60MAS_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS MAX_VENCIDO60MAS_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS MIN_VENCIDO60MAS_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS MIN_VENCIDO60MAS_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS MIN_VENCIDO60MAS_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS AVG_VENCIDO60MAS_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS AVG_VENCIDO60MAS_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO60MAS ELSE NULL END) AS AVG_VENCIDO60MAS_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_VENC60M_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_VENCIDO60MAS_03M,
    ROUND(SUM(PND_MENOS_VENC60M_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_VENCIDO60MAS_06M,
    ROUND(SUM(PND_MENOS_VENC60M_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_VENCIDO60MAS_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_VENC60M_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_VENCIDO60MAS_03M,
    ROUND(SUM(PND_MAS_VENC60M_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_VENCIDO60MAS_06M,
    ROUND(SUM(PND_MAS_VENC60M_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_VENCIDO60MAS_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND VENCIDO60MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO60MAS_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND VENCIDO60MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO60MAS_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND VENCIDO60MAS > 0 THEN 1 ELSE NULL END) AS NUM_VENCIDO60MAS_12M,

--  SUMA
    SUM(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS SUM_VENC29_03M,
    SUM(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS SUM_VENC29_06M,
    SUM(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO1A29 ELSE NULL END) AS SUM_VENC29_12M,

    SUM(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS SUM_VENC59_03M,
    SUM(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS SUM_VENC59_06M,
    SUM(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO30A59 ELSE NULL END) AS SUM_VENC59_12M,

    SUM(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS SUM_VENC89_03M,
    SUM(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS SUM_VENC89_06M,
    SUM(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO60A89 ELSE NULL END) AS SUM_VENC89_12M,

    SUM(CASE WHEN PND_MAS03M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS SUM_VENC90MAS_03M,
    SUM(CASE WHEN PND_MAS06M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS SUM_VENC90MAS_06M,
    SUM(CASE WHEN PND_MAS12M IS NOT NULL THEN VENCIDO90MAS ELSE NULL END) AS SUM_VENC90MAS_12M,
    
    SUM(CASE WHEN PND_MAS03M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS SUM_VIGENTEH_03M,
    SUM(CASE WHEN PND_MAS06M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS SUM_VIGENTEH_06M,
    SUM(CASE WHEN PND_MAS12M IS NOT NULL THEN VIGENTEH ELSE NULL END) AS SUM_VIGENTEH_12M,
    
--  PORCIÓN DE VENCIDOS							
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS MAX_PCT_VENC1M_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS MAX_PCT_VENC1M_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS MAX_PCT_VENC1M_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS MIN_PCT_VENC1M_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS MIN_PCT_VENC1M_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS MIN_PCT_VENC1M_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS AVG_PCT_VENC1M_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS AVG_PCT_VENC1M_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC1M ELSE NULL END) AS AVG_PCT_VENC1M_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_PCT_VENC1M_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_PCT_VENC1M_03M,
    ROUND(SUM(PND_MENOS_PCT_VENC1M_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_PCT_VENC1M_06M,
    ROUND(SUM(PND_MENOS_PCT_VENC1M_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_PCT_VENC1M_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_PCT_VENC1M_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_PCT_VENC1M_03M,
    ROUND(SUM(PND_MAS_PCT_VENC1M_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_PCT_VENC1M_06M,
    ROUND(SUM(PND_MAS_PCT_VENC1M_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_PCT_VENC1M_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND PCT_VENC1M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC1M_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND PCT_VENC1M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC1M_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND PCT_VENC1M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC1M_12M,

--  PORCION VENCIDO 30 MÁS DÍAS DE ATRASO
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS MAX_PCT_VENC30M_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS MAX_PCT_VENC30M_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS MAX_PCT_VENC30M_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS MIN_PCT_VENC30M_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS MIN_PCT_VENC30M_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS MIN_PCT_VENC30M_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS AVG_PCT_VENC30M_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS AVG_PCT_VENC30M_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC30M ELSE NULL END) AS AVG_PCT_VENC30M_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_PCT_VENC30M_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_PCT_VENC30M_03M,
    ROUND(SUM(PND_MENOS_PCT_VENC30M_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_PCT_VENC30M_06M,
    ROUND(SUM(PND_MENOS_PCT_VENC30M_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_PCT_VENC30M_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_PCT_VENC30M_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_PCT_VENC30M_03M,
    ROUND(SUM(PND_MAS_PCT_VENC30M_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_PCT_VENC30M_06M,
    ROUND(SUM(PND_MAS_PCT_VENC30M_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_PCT_VENC30M_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND PCT_VENC30M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC30M_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND PCT_VENC30M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC30M_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND PCT_VENC30M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC30M_12M,

-- PORCIÓN VENCIDO 60 MÁS DÍAS DE ATRASO
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS MAX_PCT_VENC60M_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS MAX_PCT_VENC60M_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS MAX_PCT_VENC60M_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS MIN_PCT_VENC60M_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS MIN_PCT_VENC60M_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS MIN_PCT_VENC60M_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS AVG_PCT_VENC60M_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS AVG_PCT_VENC60M_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN PCT_VENC60M ELSE NULL END) AS AVG_PCT_VENC60M_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_PCT_VENC60M_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_PCT_VENC60M_03M,
    ROUND(SUM(PND_MENOS_PCT_VENC60M_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_PCT_VENC60M_06M,
    ROUND(SUM(PND_MENOS_PCT_VENC60M_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_PCT_VENC60M_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_PCT_VENC60M_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_PCT_VENC60M_03M,
    ROUND(SUM(PND_MAS_PCT_VENC60M_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_PCT_VENC60M_06M,
    ROUND(SUM(PND_MAS_PCT_VENC60M_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_PCT_VENC60M_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND PCT_VENC60M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC60M_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND PCT_VENC60M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC60M_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND PCT_VENC60M > 0 THEN 1 ELSE NULL END) AS NUM_PCT_VENC60M_12M,

--  VARIABLES DE CALIFICACION DE CATERTA
--  AVG_HI_CALCAR_L
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS MAX_AVG_HI_CALCAR_L_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS MAX_AVG_HI_CALCAR_L_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS MAX_AVG_HI_CALCAR_L_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS MIN_AVG_HI_CALCAR_L_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS MIN_AVG_HI_CALCAR_L_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS MIN_AVG_HI_CALCAR_L_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS AVG_AVG_HI_CALCAR_L_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS AVG_AVG_HI_CALCAR_L_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_L ELSE NULL END) AS AVG_AVG_HI_CALCAR_L_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_L_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_L_03M,
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_L_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_L_06M,
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_L_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_L_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_AVG_HI_CALCAR_L_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_L_03M,
    ROUND(SUM(PND_MAS_AVG_HI_CALCAR_L_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_L_06M,
    ROUND(SUM(PND_MAS_AVG_HI_CALCAR_L_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_L_12M,

--  MAX_HI_CALCAR_L
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS MAX_MAX_HI_CALCAR_L_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS MAX_MAX_HI_CALCAR_L_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS MAX_MAX_HI_CALCAR_L_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS MIN_MAX_HI_CALCAR_L_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS MIN_MAX_HI_CALCAR_L_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS MIN_MAX_HI_CALCAR_L_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS AVG_MAX_HI_CALCAR_L_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS AVG_MAX_HI_CALCAR_L_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_L ELSE NULL END) AS AVG_MAX_HI_CALCAR_L_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_L_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_L_03M,
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_L_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_L_06M,
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_L_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_L_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_MAX_HI_CALCAR_L_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_L_03M,
    ROUND(SUM(PND_MAS_MAX_HI_CALCAR_L_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_L_06M,
    ROUND(SUM(PND_MAS_MAX_HI_CALCAR_L_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_L_12M,

--  AVG_HI_CALCAR_CEIL
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS MAX_AVG_HI_CALCAR_CEIL_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS MAX_AVG_HI_CALCAR_CEIL_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS MAX_AVG_HI_CALCAR_CEIL_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS MIN_AVG_HI_CALCAR_CEIL_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS MIN_AVG_HI_CALCAR_CEIL_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS MIN_AVG_HI_CALCAR_CEIL_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS AVG_AVG_HI_CALCAR_CEIL_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS AVG_AVG_HI_CALCAR_CEIL_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_CEIL ELSE NULL END) AS AVG_AVG_HI_CALCAR_CEIL_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_CEIL_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_CEIL_03M,
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_CEIL_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_CEIL_06M,
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_CEIL_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_CEIL_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_AVG_HI_CALCAR_CEIL_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_CEIL_03M,
    ROUND(SUM(PND_MAS_AVG_HI_CALCAR_CEIL_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_CEIL_06M,
    ROUND(SUM(PND_MAS_AVG_HI_CALCAR_CEIL_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_CEIL_12M,

--  MAX_HI_CALCAR_CEIL
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS MAX_MAX_HI_CALCAR_CEIL_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS MAX_MAX_HI_CALCAR_CEIL_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS MAX_MAX_HI_CALCAR_CEIL_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS MIN_MAX_HI_CALCAR_CEIL_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS MIN_MAX_HI_CALCAR_CEIL_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS MIN_MAX_HI_CALCAR_CEIL_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS AVG_MAX_HI_CALCAR_CEIL_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS AVG_MAX_HI_CALCAR_CEIL_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_CEIL ELSE NULL END) AS AVG_MAX_HI_CALCAR_CEIL_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_CEIL_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_03M,
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_CEIL_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_06M,
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_CEIL_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_CEIL_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_MAX_HI_CALCAR_CEIL_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_CEIL_03M,
    ROUND(SUM(PND_MAS_MAX_HI_CALCAR_CEIL_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_CEIL_06M,
    ROUND(SUM(PND_MAS_MAX_HI_CALCAR_CEIL_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_CEIL_12M,

--  MAX_HI_CALCAR_FLOOR
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS MAX_MAX_HI_CALCAR_FLOOR_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS MAX_MAX_HI_CALCAR_FLOOR_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS MAX_MAX_HI_CALCAR_FLOOR_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS MIN_MAX_HI_CALCAR_FLOOR_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS MIN_MAX_HI_CALCAR_FLOOR_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS MIN_MAX_HI_CALCAR_FLOOR_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS AVG_MAX_HI_CALCAR_FLOOR_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS AVG_MAX_HI_CALCAR_FLOOR_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN MAX_HI_CALCAR_FLOOR ELSE NULL END) AS AVG_MAX_HI_CALCAR_FLOOR_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_FLOOR_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_03M,
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_FLOOR_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_06M,
    ROUND(SUM(PND_MENOS_MAX_HI_CALCAR_FLOOR_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_MAX_HI_CALCAR_FLOOR_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_MAX_HI_CALCAR_FLOOR_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_03M,
    ROUND(SUM(PND_MAS_MAX_HI_CALCAR_FLOOR_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_06M,
    ROUND(SUM(PND_MAS_MAX_HI_CALCAR_FLOOR_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_MAX_HI_CALCAR_FLOOR_12M,
    
--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND MAX_HI_CALCAR_FLOOR > 0 THEN 1 ELSE NULL END) AS NUM_MAX_HI_CALCAR_FLOOR_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND MAX_HI_CALCAR_FLOOR > 0 THEN 1 ELSE NULL END) AS NUM_MAX_HI_CALCAR_FLOOR_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND MAX_HI_CALCAR_FLOOR > 0 THEN 1 ELSE NULL END) AS NUM_MAX_HI_CALCAR_FLOOR_12M,

--  AVG_HI_CALCAR_FLOOR
--  MAXIMO
    MAX(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS MAX_AVG_HI_CALCAR_FLOOR_03M,
    MAX(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS MAX_AVG_HI_CALCAR_FLOOR_06M,
    MAX(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS MAX_AVG_HI_CALCAR_FLOOR_12M,

--  MINIMO
    MIN(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS MIN_AVG_HI_CALCAR_FLOOR_03M,
    MIN(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS MIN_AVG_HI_CALCAR_FLOOR_06M,
    MIN(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS MIN_AVG_HI_CALCAR_FLOOR_12M,

--  PROMEDIO
    AVG(CASE WHEN PND_MAS03M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS AVG_AVG_HI_CALCAR_FLOOR_03M,
    AVG(CASE WHEN PND_MAS06M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS AVG_AVG_HI_CALCAR_FLOOR_06M,
    AVG(CASE WHEN PND_MAS12M IS NOT NULL THEN AVG_HI_CALCAR_FLOOR ELSE NULL END) AS AVG_AVG_HI_CALCAR_FLOOR_12M,
    
--  PROMEDIO PONDERADO, MENOS
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_FLOOR_U03M)/SUM(PND_MENOS03M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_FLOOR_03M,
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_FLOOR_U06M)/SUM(PND_MENOS06M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_FLOOR_06M,
    ROUND(SUM(PND_MENOS_AVG_HI_CALCAR_FLOOR_U12M)/SUM(PND_MENOS12M),6) AS AVG_PND_MENOS_AVG_HI_CALCAR_FLOOR_12M,

--  PROMEDIO PONDERADO, MAS
	ROUND(SUM(PND_MAS_AVG_HI_CALCAR_FLOOR_U03M)/SUM(PND_MAS03M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_FLOOR_03M,
    ROUND(SUM(PND_MAS_AVG_HI_CALCAR_FLOOR_U06M)/SUM(PND_MAS06M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_FLOOR_06M,
    ROUND(SUM(PND_MAS_AVG_HI_CALCAR_FLOOR_U12M)/SUM(PND_MAS12M),6) AS AVG_PND_MAS_AVG_HI_CALCAR_FLOOR_12M,

--  CONTEOS V
    COUNT(CASE WHEN PND_MAS03M IS NOT NULL AND AVG_HI_CALCAR_FLOOR > 0 THEN 1 ELSE NULL END) AS NUM_AVG_HI_CALCAR_FLOOR_03M,
    COUNT(CASE WHEN PND_MAS06M IS NOT NULL AND AVG_HI_CALCAR_FLOOR > 0 THEN 1 ELSE NULL END) AS NUM_AVG_HI_CALCAR_FLOOR_06M,
    COUNT(CASE WHEN PND_MAS12M IS NOT NULL AND AVG_HI_CALCAR_FLOOR > 0 THEN 1 ELSE NULL END) AS NUM_AVG_HI_CALCAR_FLOOR_12M

FROM
    dbriskdatamart.JAT_MCV_HI_TMP2__${FECHA_CALIFICACION}
GROUP BY
    RFC,
    FOLIO,
    FECHACONSULTA
;

SELECT * FROM dbriskdatamart.JAT_MCV_VAR_HI__${FECHA_CALIFICACION} LIMIT 100