%hive
DROP TABLE IF EXISTS RSS_MCV_SEGMENTO_COMERCIAL;

CREATE TABLE IF NOT EXISTS
RSS_MCV_SEGMENTO_COMERCIAL
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MCV/RSS/RSS_MCV_SEGMENTO_COMERCIAL' AS


SELECT B.FECHA, B.RFC , B.LLAVE_UNIVERSAL_20, C.foliorespuestabc
FROM RSS_MCV_CARTERA_CREDITICIA_LINEA B
LEFT JOIN (
	SELECT  fecha , rfc , max(foliorespuestabc) as foliorespuestabc 
	FROM dbriskdatamart.MZM_MCV_UNIVERSO_MODELADO_201906
	GROUP BY fecha , rfc 
) C
ON B.FECHA = C.fecha and B.RFC = C.rfc
where B.fecha = '201907'
GROUP BY B.FECHA,B.RFC, B.LLAVE_UNIVERSAL_20,C.foliorespuestabc ;