%hive

USE dbriskdatamart;

DROP TABLE IF EXISTS dbriskdatamart.MZM_MCV_CR__${FECHA_CALIFICACION};
CREATE TABLE dbriskdatamart.MZM_MCV_CR__${FECHA_CALIFICACION}
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MZM/MCV/MZM_MCV_CR__${FECHA_CALIFICACION}' AS


SELECT RFC,FOLIO,FECHACONSULTA,'OP_ACC' AS ESTATUS,
BK_OP_ACC               AS BK              ,
BK_PQ_OP_ACC            AS BK_PQ           ,
BK_CS_OP_ACC            AS BK_CS           ,
BK_LSG_OP_ACC           AS BK_LSG          ,
BK_R_OP_ACC             AS BK_R            ,
BK_CF_OP_ACC            AS BK_CF           ,
BK_OTHER_OP_ACC         AS BK_OTHER        ,
LSE_OP_ACC              AS LSE             ,
LSE_PQ_OP_ACC           AS LSE_PQ          ,
LSE_CS_OP_ACC           AS LSE_CS          ,
LSE_LSG_OP_ACC          AS LSE_LSG         ,
LSE_R_OP_ACC            AS LSE_R           ,
LSE_CF_OP_ACC           AS LSE_CF          ,
LSE_OTHER_OP_ACC        AS LSE_OTHER       ,
UN_CRE_OP_ACC           AS UN_CRE          ,
UN_CRE_PQ_OP_ACC        AS UN_CRE_PQ       ,
UN_CRE_CS_OP_ACC        AS UN_CRE_CS       ,
UN_CRE_LSG_OP_ACC       AS UN_CRE_LSG      ,
UN_CRE_R_OP_ACC         AS UN_CRE_R        ,
UN_CRE_CF_OP_ACC        AS UN_CRE_CF       ,
UN_CRE_OTHER_OP_ACC     AS UN_CRE_OTHER    ,
OTHER_FIN_OP_ACC        AS OTHER_FIN       ,
OTHER_FIN_PQ_OP_ACC     AS OTHER_FIN_PQ    ,
OTHER_FIN_CS_OP_ACC     AS OTHER_FIN_CS    ,
OTHER_FIN_LSG_OP_ACC    AS OTHER_FIN_LSG   ,
OTHER_FIN_R_OP_ACC      AS OTHER_FIN_R     ,
OTHER_FIN_CF_OP_ACC     AS OTHER_FIN_CF    ,
OTHER_FIN_OTHER_OP_ACC  AS OTHER_FIN_OTHER ,
GBN_OP_ACC              AS GBN             ,
GBN_PQ_OP_ACC           AS GBN_PQ          ,
GBN_CS_OP_ACC           AS GBN_CS          ,
GBN_LSG_OP_ACC          AS GBN_LSG         ,
GBN_R_OP_ACC            AS GBN_R           ,
GBN_CF_OP_ACC           AS GBN_CF          ,
GBN_OTHER_OP_ACC        AS GBN_OTHER       ,
BRG_OP_ACC              AS BRG             ,
BRG_PQ_OP_ACC           AS BRG_PQ          ,
BRG_CS_OP_ACC           AS BRG_CS          ,
BRG_LSG_OP_ACC          AS BRG_LSG         ,
BRG_R_OP_ACC            AS BRG_R           ,
BRG_CF_OP_ACC           AS BRG_CF          ,
BRG_OTHER_OP_ACC        AS BRG_OTHER       ,
BRG_LSE_OP_ACC          AS BRG_LSE         ,
BRG_LSE_PQ_OP_ACC       AS BRG_LSE_PQ      ,
BRG_LSE_CS_OP_ACC       AS BRG_LSE_CS      ,
BRG_LSE_LSG_OP_ACC      AS BRG_LSE_LSG     ,
BRG_LSE_R_OP_ACC        AS BRG_LSE_R       ,
BRG_LSE_CF_OP_ACC       AS BRG_LSE_CF      ,
BRG_LSE_OTHER_OP_ACC    AS BRG_LSE_OTHER
FROM MZM_MCV_CREDITOS_ACTIVOS__${FECHA_CALIFICACION};

INSERT INTO  
	 MZM_MCV_CR__${FECHA_CALIFICACION} 
SELECT DISTINCT RFC, FOLIO, FECHACONSULTA,'CL_ACC',
BK_CL_ACC              ,
BK_PQ_CL_ACC           ,
BK_CS_CL_ACC           ,
BK_LSG_CL_ACC          ,
BK_R_CL_ACC            ,
BK_CF_CL_ACC           ,
BK_OTHER_CL_ACC        ,
LSE_CL_ACC             ,
LSE_PQ_CL_ACC          ,
LSE_CS_CL_ACC          ,
LSE_LSG_CL_ACC         ,
LSE_R_CL_ACC           ,
LSE_CF_CL_ACC          ,
LSE_OTHER_CL_ACC       ,
UN_CRE_CL_ACC          ,
UN_CRE_PQ_CL_ACC       ,
UN_CRE_CS_CL_ACC       ,
UN_CRE_LSG_CL_ACC      ,
UN_CRE_R_CL_ACC        ,
UN_CRE_CF_CL_ACC       ,
UN_CRE_OTHER_CL_ACC    ,
OTHER_FIN_CL_ACC       ,
OTHER_FIN_PQ_CL_ACC    ,
OTHER_FIN_CS_CL_ACC    ,
OTHER_FIN_LSG_CL_ACC   ,
OTHER_FIN_R_CL_ACC     ,
OTHER_FIN_CF_CL_ACC    ,
OTHER_FIN_OTHER_CL_ACC ,
GBN_CL_ACC             ,
GBN_PQ_CL_ACC          ,
GBN_CS_CL_ACC          ,
GBN_LSG_CL_ACC         ,
GBN_R_CL_ACC           ,
GBN_CF_CL_ACC          ,
GBN_OTHER_CL_ACC       ,
BRG_CL_ACC             ,
BRG_PQ_CL_ACC          ,
BRG_CS_CL_ACC          ,
BRG_LSG_CL_ACC         ,
BRG_R_CL_ACC           ,
BRG_CF_CL_ACC          ,
BRG_OTHER_CL_ACC       ,
BRG_LSE_CL_ACC         ,
BRG_LSE_PQ_CL_ACC      ,
BRG_LSE_CS_CL_ACC      ,
BRG_LSE_LSG_CL_ACC     ,
BRG_LSE_R_CL_ACC       ,
BRG_LSE_CF_CL_ACC      ,
BRG_LSE_OTHER_CL_ACC
	FROM MZM_MCV_CREDITOS_LIQUIDADOS__${FECHA_CALIFICACION} ;
	
SELECT * FROM dbriskdatamart.MZM_MCV_CR__${FECHA_CALIFICACION} LIMIT 100;
