%hive
DROP TABLE IF EXISTS RSS_MCV_CARTERA_CREDITICIA_LINEA_A;


-- La creación tarda bastante
CREATE TABLE RSS_MCV_CARTERA_CREDITICIA_LINEA_A 

ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MCV/RSS/RSS_MCV_CARTERA_CREDITICIA_LINEA_A' AS

SELECT    
    LPAD(CONCAT(LINEA,MONEDA),20,'0') AS LLAVE_UNIVERSAL_20,
    A.* 
FROM dbriskdatamart.Tbl_CarteraCrediticia A
WHERE LINEA IS NOT NULL AND LINEA != '';