DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA_UEN;


-- La creación tarda bastante
CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA_UEN AS
SELECT    
    A.*,
    CASE 
        WHEN B.UEN IN ('05 PEQUEÑA EMPRESA NL', '09 PEQUEÑA EMPRESA TERRITORIAL') 
            AND B.PERFIL_NEGOCIO_ACTUAL NOT IN ('CORPORATIVO', 'DIRECCION', 'DUMMY', 'GOBIERNO')
            AND B.PRODUCTO NOT IN ('3I ACS AUTOPRESTO', '3N ACS AUTOPRESTO', 'Z1 SEGURO ACS AUTOPRESTO')
            AND B.SUBSEGMENTO_PRODUCTO <> 'AB - VARIOS' THEN 1
        ELSE 0
    END AS UEN_PEQ
FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA A
LEFT JOIN DBMYMWORK.JEA_MCV_COLOCACION B
ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL AND A.FECHA = B.FECHA
WHERE A.LINEA IS NOT NULL AND A.LINEA != '';


-- Es preferibke correr la creación de la tabla y despues la creacion del indice 
CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_UEN_fecha_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA_UEN (FECHA);

CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_UEN_llave_universal_20_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA_UEN (LLAVE_UNIVERSAL_20);

CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_UEN_cliente_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA_UEN (CLIENTE);

CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_UEN_rfc_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA_UEN (RFC);

CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_UEN_mesesdc_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA_UEN (MESESDC);