DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_PREUNIVERSO;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_PREUNIVERSO AS
SELECT 
  A.*,
  -- A.CCI,
  CASE A.TIPO_DE_CREDITO
        WHEN 'CARTA DE CREDITO' THEN 1
        WHEN 'CCI' THEN 1
        WHEN 'CCI PROV' THEN 1
        ELSE 0
  END AS CCI,
    
  CASE
      WHEN A.TIPO_DE_CREDITO IN ('LINEA DE CREDITO POR SOBREGIRO', 'LINEA SOBREGIRO') THEN 1
      ELSE 0
  END as SOBREGIRO,
  
  CASE 
      WHEN A.HSC_CIC_GRUPO = 'CIC' THEN 1
      ELSE 0
  END as INTERCOMPANIA,
  
  CASE
      WHEN A.MIS = '5' OR A.MIS = '2' OR A.MIS = '3' THEN 1
      ELSE 0
  END as CARTERA_ADQUIRIDA,
  
  -- El siguiente campo tiene dependencia ciclica (JEA_MCV_CATALOGO_LIN_NEC_VENC)
  -- debe correrse el script comentándolo, generar JEA_MCV_CATALOGO_LIN_NEC_VENC, y volver
  -- a correrlo descomentado
  -- /*
  CASE 
      WHEN A.TIPO_DE_CREDITO like '%REE%' or A.TIPO_DE_CREDITO = 'CVMGA' THEN 1
      WHEN A.LLAVE_UNIVERSAL_20 in (
      	SELECT LLAVE_UNIVERSAL 
      	FROM DBMYMWORK.JEA_MCV_CATALOGO_LIN_REEST
      ) THEN 1
      WHEN A.LLAVE_UNIVERSAL_20 in (
      	SELECT LLAVE_UNIVERSAL_20 
      	FROM DBMYMWORK.JEA_MCV_CATALOGO_LIN_NAC_VENC
      ) THEN 1
      ELSE 0
  END AS REESTRUCTURA,
  -- */

  -- El siguiente campo tiene dependencia ciclica (JEA_MCV_CATALOGO_REVOLVENTE, JEA_MCV_CATALOGO_NO_REVOLVENTE)
  -- debe correrse el script comentándolo, generar JEA_MCV_CATALOGO_REVOLVENTE, JEA_MCV_CATALOGO_NO_REVOLVENTE, y volver
  -- a correrlo descomentado
  -- /*
  CASE      
      WHEN A.TIPO_DE_CREDITO IN (
      	SELECT TIPO_DE_CREDITO 
      	FROM DBMYMWORK.JEA_MCV_CATALOGO_REVOLVENTE
      ) then 1
      WHEN A.TIPO_DE_CREDITO IN (
      	SELECT TIPO_DE_CREDITO 
      	FROM DBMYMWORK.JEA_MCV_CATALOGO_NO_REVOLVENTE
      ) then 0
      ELSE -1
  END AS REVOLVENTE
  -- */

FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA A
INNER JOIN DBMYMWORK.JEA_MCV_UNIVERSO_LLAVES B
ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL AND A.FECHA = B.FECHA;

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_FECHA_IDX
ON DBMYMWORK.JEA_MCV_PREUNIVERSO (FECHA);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_LLAVE_UNIVERSAL_20_IDX
ON DBMYMWORK.JEA_MCV_PREUNIVERSO (LLAVE_UNIVERSAL_20);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_CLIENTE_IDX
ON DBMYMWORK.JEA_MCV_PREUNIVERSO (CLIENTE);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_RFC_IDX
ON DBMYMWORK.JEA_MCV_PREUNIVERSO (RFC);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_LLAVE_UNI_20_FECHA_IDX
ON DBMYMWORK.JEA_MCV_PREUNIVERSO (LLAVE_UNIVERSAL_20, FECHA);