DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_UNIVERSO;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_UNIVERSO AS
SELECT
  A.RFC,  
  A.LLAVE_UNIVERSAL_20,
  A.FECHA,
  A.CLIENTE,
  A.LINEA,
  A.MESESDC,
  A.MONTO_LINEA,
  A.DIAS_ATRASO,
  A.CCI,
  A.SOBREGIRO,
  A.INTERCOMPANIA,
  A.CARTERA_ADQUIRIDA,
  A.REESTRUCTURA,
  A.REVOLVENTE,
  A.BUCKET,
  A.MONTO_CLS,
  A.CARTERA_VENCIDA, 
  7 - (B.SDOVDO_MAX_M0 + B.SDOVDO_MAX_M1 + 
  B.SDOVDO_MAX_M2 + B.SDOVDO_MAX_M3 + 
  B.SDOVDO_MAX_M4 + B.SDOVDO_MAX_M5 + B.SDOVDO_MAX_M6) as LABEL
FROM  DBMYMWORK.JEA_MCV_UNIVERSO_WDW A
LEFT JOIN DBMYMWORK.JEA_MCV_UNIVERSO_RFC_AGG B
ON A.RFC = B.RFC AND A.FECHA = B.FECHA;

-- Add Indexes
CREATE INDEX UNIVERSO_RFC_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (RFC);

CREATE INDEX UNIVERSO_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (FECHA);

CREATE INDEX UNIVERSO_LLAVE_UNIVERSAL_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (LLAVE_UNIVERSAL_20);

CREATE UNIQUE INDEX UNIVERSO_LLAVE_UNIVERSAL_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (LLAVE_UNIVERSAL_20, FECHA);

-- AGREGAMOS TIPO_CREDITO  QUE SERVIRÁ PARA CLACULAR LAS VARIABLES DE DIAS DE ATRASO
ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO ADD COLUMN TIPO_DE_CREDITO VARCHAR(100) AFTER FECHA;
-- UPDATING
UPDATE DBMYMWORK.JEA_MCV_UNIVERSO A
LEFT JOIN  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA B  
  ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.FECHA = B.FECHA
SET A.TIPO_DE_CREDITO = B.TIPO_DE_CREDITO;



-- AGREGAMOS FOLIO CALIFICA SOBRE EL CUAL TRAEREMOS INFORMACIÓN
ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO ADD COLUMN FOLIO_BC VARCHAR(15) AFTER LINEA;
ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO ADD COLUMN FECHA_BC DATE AFTER FOLIO_BC;


UPDATE
  DBMYMWORK.JEA_MCV_UNIVERSO T1
LEFT JOIN
  (SELECT 
    A.LLAVE_UNIVERSAL_20, 
    A.FECHA, 
    MAX(CASE WHEN YEAR(B.FECHACONSULTA)*100+MONTH(B.FECHACONSULTA) <= A.FECHA*1 THEN B.FOLIO ELSE NULL END) AS FOLIO_BC 
    FROM DBMYMWORK.JEA_MCV_UNIVERSO A 
       LEFT JOIN DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente B 
       ON A.RFC = B.RFC 
    GROUP BY 1, 2
  ) T2
ON
  T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20 AND T1.FECHA = T2.FECHA
SET
  T1.FOLIO_BC = T2.FOLIO_BC
;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO ADD KEY FOLIO_BC(FOLIO_BC);


-- TABLA DE PASO PARA OBTENER FECHAS DE BURO POR RFC
DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_BURO_FOLIO;
CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_BURO_FOLIO AS
SELECT DISTINCT 
  RFC, 
  FOLIO, 
  DATE(FECHACONSULTA) AS FECHACONSULTA
FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente;

ALTER TABLE JEA_MCV_BURO_FOLIO ADD KEY RFC(RFC);
ALTER TABLE JEA_MCV_BURO_FOLIO ADD KEY FOLIO(FOLIO);


-- AGRAEDAMOS FECHA DE CONSULTA DE BURO A UNIVERSO
UPDATE
  DBMYMWORK.JEA_MCV_UNIVERSO T1
LEFT JOIN
  DBMYMWORK.JEA_MCV_BURO_FOLIO T2
ON
  T1.RFC = T2.RFC AND T1.FOLIO_BC = T2.FOLIO
SET
  T1.FECHA_BC = T2.FECHACONSULTA
;



-- AGREGAMOS VARIABLE DIAS_ATRASO_06M (MAXIMO)
DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_VARIABLE_DIAS_ATRASO_06M;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_VARIABLE_DIAS_ATRASO_06M AS
SELECT 
  A.LLAVE_UNIVERSAL_20, 
  A.FECHA, 
  MAX(
    CASE
      WHEN (B.MESESDC - A.MESESDC) BETWEEN 1 AND 6 THEN IFNULL(B.DIAS_ATRASO,0)
      ELSE NULL
    END
  ) AS DIAS_ATRASO_06M,
  MAX(
    CASE
      WHEN (B.MESESDC - A.MESESDC) BETWEEN 1 AND 6 THEN IFNULL(B.BUCKET,0)
      ELSE NULL
    END
  ) AS MAX_BUCKET_06M
FROM DBMYMWORK.JEA_MCV_UNIVERSO A 
   LEFT JOIN DBMYMWORK.JEA_MCV_UNIVERSO B 
   ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 
GROUP BY 1, 2


CREATE INDEX FECHA_IDX
ON DBMYMWORK.JEA_MCV_VARIABLE_DIAS_ATRASO_06M (FECHA);

CREATE INDEX LLAVE_UNIVERSAL_IDX
ON DBMYMWORK.JEA_MCV_VARIABLE_DIAS_ATRASO_06M (LLAVE_UNIVERSAL_20);

CREATE UNIQUE INDEX LLAVE_UNIVERSAL_FECHA_IDX
ON DBMYMWORK.JEA_MCV_VARIABLE_DIAS_ATRASO_06M (LLAVE_UNIVERSAL_20, FECHA);


ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO ADD COLUMN DIAS_ATRASO_06M INT AFTER DIAS_ATRASO;
ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO ADD COLUMN MAX_BUCKET_06M INT AFTER DIAS_ATRASO_06M;

UPDATE
  DBMYMWORK.JEA_MCV_UNIVERSO T1
LEFT JOIN
  DBMYMWORK.JEA_MCV_VARIABLE_DIAS_ATRASO_06M T2
ON
  T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20 AND T1.FECHA = T2.FECHA
SET
  T1.DIAS_ATRASO_06M = T2.DIAS_ATRASO_06M, T1.MAX_BUCKET_06M = T2.MAX_BUCKET_06M
;

-- DELETE FROM JEA_MCV_UNIVERSO_FOLIO WHERE NOT((SUBSTR(FECHA,1,4)-YEAR(FECHA_BC))*12 + SUBSTR(FECHA,5,2) - MONTH(FECHA_BC) BETWEEN 0 AND 4);

-- SELECT DISTINCT LINEA FROM JEA_MCV_UNIVERSO_FOLIO;