DROP TABLE IF EXISTS DBMYMWORK.JEA_MCV_UNIVERSO_BINARY_LABELS;

CREATE TABLE IF NOT EXISTS 
  DBMYMWORK.JEA_MCV_UNIVERSO_BINARY_LABELS AS
SELECT 
  LLAVE_UNIVERSAL_20,
  RFC,
  FECHACARTERA,
  CASE 
    WHEN LABEL = 7 THEN 0 
    ELSE 1
  END AS BLABEL
FROM DBMYMWORK.JEA_MCV_UNIVERSO_BANDERAS_LABELS;

CREATE INDEX DBMYMWORK_JEA_MCV_UNIVERSO_BINARY_LABELS_LLAVE_UNIVERSAL_20_IDX 
ON DBMYMWORK.JEA_MCV_UNIVERSO_BINARY_LABELS (LLAVE_UNIVERSAL_20);

CREATE INDEX DBMYMWORK_JEA_MCV_UNIVERSO_BINARY_LABELS_RFC_IDX 
ON DBMYMWORK.JEA_MCV_UNIVERSO_BINARY_LABELS (RFC);

CREATE INDEX DBMYMWORK_JEA_MCV_UNIVERSO_BINARY_LABELS_FECHACARTERA_IDX 
ON DBMYMWORK.JEA_MCV_UNIVERSO_BINARY_LABELS (FECHACARTERA);

CREATE UNIQUE INDEX DBMYMWORK_JEA_MCV_UNI_BINARYL_LLAVE_UNI_FECHA_IDX 
ON DBMYMWORK.JEA_MCV_UNIVERSO_BINARY_LABELS (FECHACARTERA, LLAVE_UNIVERSAL_20);