DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_UNIVERSO;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_UNIVERSO AS
SELECT 
  B.*,
  A.CCI,
  A.REESTRUCTURA,
  A.SOBREGIRO,
  A.INTERCOMPANIA,
  A.CARTERA_ADQUIRIDA     
FROM DBMYMWORK.JEA_MCV_UNIVERSO_BANDERAS A
LEFT JOIN DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA B
ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.FECHACARTERA = B.FECHA;

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (FECHA);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_LLAVE_UNIVERSAL_20_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (LLAVE_UNIVERSAL_20);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_CLIENTE_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (CLIENTE);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_RFC_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (RFC);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_LLAVE_UNI_20_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (LLAVE_UNIVERSAL_20, FECHA);