DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_CATALOGO_REVOLVENTE;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_CATALOGO_REVOLVENTE AS

SELECT DISTINCT TIPO_DE_CREDITO
FROM DBMYMWORK.JEA_MCV_PREUNIVERSO a
WHERE TIPO_DE_CREDITO IN (
    SELECT DISTINCT 
      descripcion_tipo_credito
    FROM JEA_MCV_CATALOGO_LINEAS
    WHERE es_revolvente = 'Si'
  ) 
UNION 
SELECT DISTINCT TIPO_DE_CREDITO
FROM DBMYMWORK.JEA_MCV_PREUNIVERSO a
WHERE TIPO_DE_CREDITO IN (
    SELECT DISTINCT 
      abreviacion
    FROM JEA_MCV_CATALOGO_LINEAS
    WHERE es_revolvente = 'Si'
  )
UNION
SELECT 
  'AV C/GAD C/A' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'DEUDOR FACTOR PLAN DISTRIBUIDOR' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'DFPD' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'FFCR.' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'CR ANTICIPO' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'FFPCEOP' AS TIPO_DE_CREDITO
UNION 
SELECT 
  '3F' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'CR PUENTE' AS TIPO_DE_CREDITO