DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_CATALOGO_LIN_NAC_VENC;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_CATALOGO_LIN_NAC_VENC AS

SELECT a.*
FROM  DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA a
JOIN 
(
    SELECT 
      LLAVE_UNIVERSAL_20, 
      min(fecha) AS MIN_FECHA, 
      min(mesesdc) AS MIN_MESESDC 
    FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA
    WHERE LLAVE_UNIVERSAL_20 IN (
        SELECT DISTINCT 
          LLAVE_UNIVERSAL_20 
        FROM DBMYMWORK.JEA_MCV_PREUNIVERSO
        WHERE COALESCE(CARTERA_VENCIDA, 0) > 0
    )
    GROUP BY LLAVE_UNIVERSAL_20
) b
ON a.LLAVE_UNIVERSAL_20 = b.LLAVE_UNIVERSAL_20
WHERE a.FECHA = b.MIN_FECHA AND COALESCE(a.CARTERA_VENCIDA, 0) > 0 AND b.MIN_FECHA > 201201;