DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA;


-- La creación tarda bastante
CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA AS
SELECT    
    LPAD(CONCAT(LINEA,MONEDA),20,'0') AS LLAVE_UNIVERSAL_20,
    A.* 
FROM DBRSKDATAMART.Tbl_CarteraCrediticia A
WHERE LINEA IS NOT NULL AND LINEA != '';


-- Es preferibke correr la creación de la tabla y despues la creacion del indice 
CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_fecha_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA (FECHA);

CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_llave_universal_20_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA (LLAVE_UNIVERSAL_20);

CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_cliente_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA (CLIENTE);

CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_rfc_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA (RFC);

CREATE INDEX DBMYMWORK__CARTERA_CREDITICA_LINEA_mesesdc_idx
ON DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA (MESESDC);