DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO AS
SELECT
  RFC,  
  LLAVE_UNIVERSAL_20,
  FECHA,
  CLIENTE,
  LINEA,
  TIPO_DE_CREDITO,
  MESESDC,
  MONTO_LINEA,
  DIAS_ATRASO,
  CCI,
  SOBREGIRO,
  INTERCOMPANIA,
  CARTERA_ADQUIRIDA,
  REESTRUCTURA,
  REVOLVENTE,

  CASE
    WHEN COALESCE(DIAS_ATRASO, 0) = 0 THEN 0
    WHEN DIAS_ATRASO BETWEEN 1 AND 29 THEN 1
    WHEN DIAS_ATRASO BETWEEN 30 AND 59 THEN 2
    WHEN DIAS_ATRASO BETWEEN 60 AND 89 THEN 3
    WHEN DIAS_ATRASO >= 89 THEN 4
    ELSE 5
  END AS BUCKET,
  CASE 
    WHEN MONTO_LINEA <= 8000000 THEN 0
    WHEN MONTO_LINEA > 8000000 AND MONTO_LINEA <= 15000000 THEN 1
    WHEN MONTO_LINEA > 15000000 THEN 2
    ELSE 3
  END AS MONTO_CLS,
  CARTERA_VENCIDA  
FROM DBMYMWORK.JEA_MCV_PREUNIVERSO;

-- Add Indexes
CREATE INDEX CVLABEL_RFC_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO (RFC);

CREATE INDEX CVLABEL_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO (FECHA);

CREATE INDEX CVLABEL_LLAVE_UNIVERSAL_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO (LLAVE_UNIVERSAL_20);

CREATE UNIQUE INDEX CVLABEL_LLAVE_UNIVERSAL_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO (LLAVE_UNIVERSAL_20, FECHA);

-- Add columns
ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO
ADD SDOVDO_M0 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO
ADD SDOVDO_M1 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO
ADD SDOVDO_M2 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO
ADD SDOVDO_M3 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO
ADD SDOVDO_M4 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO
ADD SDOVDO_M5 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO
ADD SDOVDO_M6 DOUBLE;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO
SET SDOVDO_M0 = COALESCE(CARTERA_VENCIDA, 0);

-- Update SDOVDO'S
UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO B  
  ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.MESESDC + 1 = B.MESESDC
SET A.SDOVDO_M1 = B.SDOVDO_M0;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO B  
  ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.MESESDC + 2 = B.MESESDC
SET A.SDOVDO_M2 = B.SDOVDO_M0;  

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO B  
  ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.MESESDC + 3 = B.MESESDC
SET A.SDOVDO_M3 = B.SDOVDO_M0;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO B  
  ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.MESESDC + 4 = B.MESESDC
SET A.SDOVDO_M4 = B.SDOVDO_M0;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO B  
  ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.MESESDC + 5 = B.MESESDC
SET A.SDOVDO_M5 = B.SDOVDO_M0;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_SDOVDO B  
  ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.MESESDC + 6 = B.MESESDC
SET A.SDOVDO_M6 = B.SDOVDO_M0;