DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_UNIVERSO_VARIABLES;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_UNIVERSO_VARIABLES AS

SELECT
  A.LLAVE_UNIVERSAL_20,
  A.RFC,
  A.FECHACARTERA,
  A.LABEL,
  B.CUR_CRED_LIM
FROM DBMYMWORK.JEA_MCV_UNIVERSO_LABEL A
LEFT JOIN DBMYMWORK.LGG_MCV_CRED_LIM B
ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL_20 AND A.FECHACARTERA = B.FECHACARTERA

CREATE INDEX DBMYMWORK_JEA_MCV_UNIVERSO_VARIABLES_LLAVE_UNIVERSAL_20_IDX 
ON DBMYMWORK.JEA_MCV_UNIVERSO_VARIABLES (LLAVE_UNIVERSAL_20);

CREATE INDEX DBMYMWORK_JEA_MCV_UNIVERSO_VARIABLES_RFC_IDX 
ON DBMYMWORK.JEA_MCV_UNIVERSO_VARIABLES (RFC);

CREATE INDEX DBMYMWORK_JEA_MCV_UNIVERSO_VARIABLES_FECHACARTERA_IDX 
ON DBMYMWORK.JEA_MCV_UNIVERSO_VARIABLES (FECHACARTERA); 