DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_UNIVERSO_LLAVES;

CREATE TABLE DBMYMWORK.JEA_MCV_UNIVERSO_LLAVES
(
  LLAVE_UNIVERSAL CHAR(20),
  FECHA CHAR(6)
);

INSERT INTO DBMYMWORK.JEA_MCV_UNIVERSO_LLAVES
select distinct LLAVE_UNIVERSAL, FECHA
from JEA_MCV_COLOCACION
where UEN in ('05 PEQUEÑA EMPRESA NL', '09 PEQUEÑA EMPRESA TERRITORIAL') 
    and PERFIL_NEGOCIO_ACTUAL not in ('CORPORATIVO', 'DIRECCION', 'DUMMY', 'GOBIERNO')
    and PRODUCTO not in ('3I ACS AUTOPRESTO', '3N ACS AUTOPRESTO', 'Z1 SEGURO ACS AUTOPRESTO')
    and SUBSEGMENTO_PRODUCTO <> 'AB - VARIOS';

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_LLAVES_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_LLAVES (FECHA);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_LLAVES_LLAVE_UNIVERSAL_20_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_LLAVES (LLAVE_UNIVERSAL);