DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_UNIVERSO;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_UNIVERSO AS
SELECT A.*
FROM DBMYMWORK.JEA_MCV_CARTERA_CREDITICIA_LINEA A
INNER JOIN (
    SELECT DISTINCT LLAVE_UNIVERSAL, FECHA
    FROM DBMYMWORK.JEA_MCV_COLOCACION
    WHERE UEN IN ('05 PEQUEÑA EMPRESA NL', '09 PEQUEÑA EMPRESA TERRITORIAL') 
        AND PERFIL_NEGOCIO_ACTUAL NOT IN ('CORPORATIVO', 'DIRECCION', 'DUMMY', 'GOBIERNO')
        AND PRODUCTO NOT IN ('3I ACS AUTOPRESTO', '3N ACS AUTOPRESTO', 'Z1 SEGURO ACS AUTOPRESTO')
        AND SUBSEGMENTO_PRODUCTO <> 'AB - VARIOS'
) B
ON A.LLAVE_UNIVERSAL_20 = B.LLAVE_UNIVERSAL AND A.FECHA = B.FECHA;

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (FECHA);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_LLAVE_UNIVERSAL_20_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (LLAVE_UNIVERSAL_20);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_CLIENTE_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (CLIENTE);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_RFC_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (RFC);

CREATE INDEX DBMYMWORK__JEA_MCV_UNIVERSO_LLAVE_UNI_20_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO (LLAVE_UNIVERSAL_20, FECHA):