DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_CATALOGO_NO_REVOLVENTE;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_CATALOGO_NO_REVOLVENTE AS

SELECT DISTINCT TIPO_DE_CREDITO
FROM DBMYMWORK.JEA_MCV_UNIVERSO a
WHERE TIPO_DE_CREDITO IN (
    SELECT DISTINCT 
      descripcion_tipo_credito
    FROM JEA_MCV_CATALOGO_LINEAS
    WHERE es_revolvente = 'No'
  ) 
UNION 
SELECT DISTINCT TIPO_DE_CREDITO
FROM DBMYMWORK.JEA_MCV_UNIVERSO a
WHERE TIPO_DE_CREDITO IN (
    SELECT DISTINCT 
      abreviacion
    FROM JEA_MCV_CATALOGO_LINEAS
    WHERE es_revolvente = 'No'
  ) 
UNION
SELECT 
  'Simple' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'Arrendamiento Puro' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'A. PURO' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'A. FIN' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'Credito' AS TIPO_DE_CREDITO
UNION 
SELECT 
  'ACSSGR PE NAFIN' AS TIPO_DE_CREDITO
UNION 
SELECT 
  '3K' AS TIPO_DE_CREDITO
