DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_COLOCACION;

CREATE TABLE DBMYMWORK.JEA_MCV_COLOCACION (
    LLAVE_UNIVERSAL CHAR(20),
    ACTIVIDAD_ECONOMICA VARCHAR(510),
    CLIENTE VARCHAR(510),
    COMPANIA VARCHAR(510),
    CREDITO_ORIGINAL VARCHAR(510),
    FECHA VARCHAR(6),
    FECHA_CASTIGO_CREDITO DATETIME,
    ID_LINEA VARCHAR(510),
    INGRESO_MENSUAL VARCHAR(510),
    LINEA_ORIGINAL VARCHAR(510),
    MONEDA CHAR(2),
    PERFIL_NEGOCIO_ACTUAL VARCHAR(510),
    PRODUCTO VARCHAR(510),
    SUBSEGMENTO_PRODUCTO VARCHAR(510),
    UEN VARCHAR(510)
);


-- en postgres correr 
-- copy colocacion.tbl_colocacion_mensual_uen_peq_med_credito to '/tmp/colocacion.csv' delimiter '|';
-- y exportar: rsync -avz /tmp/colocacion.csv joseangel@10.24.25.196:/data/mysql-files/joseangel/
LOAD DATA INFILE '/data/mysql-files/joseangel/colocacion.csv'
INTO TABLE DBMYMWORK.JEA_MCV_COLOCACION
CHARACTER SET UTF8
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

CREATE INDEX DBMYMWORK__JEA_MCV_COLOCACION_LLAVE_UNIVERSAL
ON DBMYMWORK.JEA_MCV_COLOCACION (LLAVE_UNIVERSAL);

CREATE INDEX DBMYMWORK__JEA_MCV_COLOCACION_FECHA
ON DBMYMWORK.JEA_MCV_COLOCACION (FECHA);

