SELECT  
	A.RFC, 
	A.LLAVE_UNIVERSAL_20, 
	CASE WHEN B.RFC IS NOT NULL THEN 1 ELSE 0 END AS TDCEMP
INTO OUTFILE '/data/mysql-files/joseangel/MCV_TDCEMP_201812.csv'
FIELDS TERMINATED BY ','
-- OPTIONALLY ENCLOSED BY '"'
-- ESCAPED BY ''
LINES TERMINATED BY '\n'
FROM JEA_MCV_VARIABLES_201811_201812 A  -- JAT_MCV_UNIVERSO_MODELADO_201712_201810  
LEFT JOIN ( SELECT DISTINCT RFC, FECHA 
				FROM JAT_MCV_TDCEMP_CALIFICACION ) B
ON A.RFC = B.RFC AND A.FECHA = B.FECHA
WHERE A.FECHA = 201812 AND A.LABEL <> 0;