DROP TABLE IF EXISTS 
    DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL;

CREATE TABLE IF NOT EXISTS
    DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL AS
SELECT
  RFC,  
  LLAVE_UNIVERSAL_20 AS LLAVE_UNIVERSAL,
  FECHA,
  MESESDC,
  MONTO_LINEA,
  CARTERA_VENCIDA  
FROM DBMYMWORK.JEA_MCV_UNIVERSO;

-- Add Indexes
CREATE INDEX CVLABEL_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL (FECHA);

CREATE INDEX CVLABEL_LLAVE_UNIVERSAL_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL (LLAVE_UNIVERSAL);

CREATE UNIQUE INDEX CVLABEL_LLAVE_UNIVERSAL_FECHA_IDX
ON DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL (LLAVE_UNIVERSAL, FECHA);

-- Add columns
ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL
ADD SDOVDO_M0 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL
ADD SDOVDO_M1 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL
ADD SDOVDO_M2 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL
ADD SDOVDO_M3 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL
ADD SDOVDO_M4 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL
ADD SDOVDO_M5 DOUBLE;

ALTER TABLE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL
ADD SDOVDO_M6 DOUBLE;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL
SET SDOVDO_M0 = COALESCE(CARTERA_VENCIDA, 0);

-- Update SDOVDO'S
UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL B  
  ON A.LLAVE_UNIVERSAL = B.LLAVE_UNIVERSAL AND A.MESESDC + 1 = B.MESESDC
SET A.SDOVDO_M1 = B.SDOVDO_M0;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL B  
  ON A.LLAVE_UNIVERSAL = B.LLAVE_UNIVERSAL AND A.MESESDC + 2 = B.MESESDC
SET A.SDOVDO_M2 = B.SDOVDO_M0;  

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL B  
  ON A.LLAVE_UNIVERSAL = B.LLAVE_UNIVERSAL AND A.MESESDC + 3 = B.MESESDC
SET A.SDOVDO_M3 = B.SDOVDO_M0;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL B  
  ON A.LLAVE_UNIVERSAL = B.LLAVE_UNIVERSAL AND A.MESESDC + 4 = B.MESESDC
SET A.SDOVDO_M4 = B.SDOVDO_M0;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL B  
  ON A.LLAVE_UNIVERSAL = B.LLAVE_UNIVERSAL AND A.MESESDC + 5 = B.MESESDC
SET A.SDOVDO_M5 = B.SDOVDO_M0;

UPDATE DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL A
LEFT JOIN  DBMYMWORK.JEA_MCV_UNIVERSO_CVLABEL B  
  ON A.LLAVE_UNIVERSAL = B.LLAVE_UNIVERSAL AND A.MESESDC + 6 = B.MESESDC
SET A.SDOVDO_M6 = B.SDOVDO_M0;