%hive
DROP TABLE IF EXISTS RSS_MCV_PEQUE_VAR_VARIABLES_DIASATRASO_201902;

CREATE TABLE  RSS_MCV_PEQUE_VAR_VARIABLES_DIASATRASO_201902
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/MCV/RSS_MCV_PEQUE_VAR_VARIABLES_DIASATRASO_201902' AS
SELECT
'fecha' AS fecha,
'rfc' as rfc ,   
'dias_atraso' AS dias_atraso,
'dpcv_cap' AS dpcv_cap;

INSERT INTO RSS_MCV_PEQUE_VAR_VARIABLES_DIASATRASO_201902
SELECT
a.fecha,
a.rfc , 
b.dias_atraso,
b.dpcv_cap
FROM JEA_MCV_UNIVERSO_RFC a
LEFT JOIN dbriskdatamart.MZM_MCV_VAR_VARIABLES_DIASATRASO_201902 b
on a.rfc=b.rfc and a.fecha=b.fecha
where a.fecha >=201607 ;