-- GENERACIÓN DE UNIVERSO

DROP TABLE IF EXISTS JEA_MCV_UNIVERSO_FOLIO;

CREATE TABLE IF NOT EXISTS
	JEA_MCV_UNIVERSO_FOLIO AS
SELECT
    *
	/*LLAVE_UNIVERSAL_20,
	FECHA,
	CLIENTE,
	RFC,
	LINEA,
	LABEL,
	REVOLVENTE*/
FROM
	JEA_MCV_UNIVERSO
WHERE
	-- CCI = 0
	-- AND REESTRUCTURA = 0
	-- AND SOBREGIRO = 0
	-- AND INTERCOMPANIA = 0
	-- AND CARTERA_ADQUIRIDA = 0
	-- AND LABEL <> 0
	FECHA = 201812 -- BETWEEN 201806 AND 201810
;

ALTER TABLE JEA_MCV_UNIVERSO_FOLIO ADD KEY LLAVE_UNIVERSAL_20(LLAVE_UNIVERSAL_20);
ALTER TABLE JEA_MCV_UNIVERSO_FOLIO ADD KEY FECHA(FECHA);
ALTER TABLE JEA_MCV_UNIVERSO_FOLIO ADD KEY CLIENTE(CLIENTE);
ALTER TABLE JEA_MCV_UNIVERSO_FOLIO ADD KEY RFC(RFC);
ALTER TABLE JEA_MCV_UNIVERSO_FOLIO ADD KEY LINEA(LINEA);

-- AGREGAMOS FOLIO CALIFICA SOBRE EL CUAL TRAEREMOS INFORMACIÓN
ALTER TABLE JEA_MCV_UNIVERSO_FOLIO ADD COLUMN FOLIO_BC VARCHAR(15) AFTER LINEA;
ALTER TABLE JEA_MCV_UNIVERSO_FOLIO ADD COLUMN FECHA_BC DATE AFTER FOLIO_BC;
ALTER TABLE JEA_MCV_UNIVERSO_FOLIO ADD KEY FOLIO_BC(FOLIO_BC);

UPDATE
	JEA_MCV_UNIVERSO_FOLIO T1
LEFT JOIN
	(SELECT 
		A.LLAVE_UNIVERSAL_20, 
		A.FECHA, 
		MAX(CASE WHEN YEAR(B.FECHACONSULTA)*100+MONTH(B.FECHACONSULTA) <= A.FECHA*1 THEN B.FOLIO ELSE NULL END) AS FOLIO_BC 
		FROM JEA_MCV_UNIVERSO_FOLIO A 
		   LEFT JOIN DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente B 
		   ON A.RFC = B.RFC 
		GROUP BY 1, 2
	) T2
ON
	T1.LLAVE_UNIVERSAL_20 = T2.LLAVE_UNIVERSAL_20 AND T1.FECHA = T2.FECHA
SET
	T1.FOLIO_BC = T2.FOLIO_BC
;

UPDATE
	JEA_MCV_UNIVERSO_FOLIO T1
LEFT JOIN
	(SELECT DISTINCT RFC, FOLIO, FECHACONSULTA FROM DBRSKDATAMART.Tbl_BuroCalificaPM_recurrente) T2
ON
	T1.RFC = T2.RFC AND T1.FOLIO_BC = T2.FOLIO
SET
	FECHA_BC = FECHACONSULTA
;

DELETE FROM JEA_MCV_UNIVERSO_FOLIO WHERE NOT((SUBSTR(FECHA,1,4)-YEAR(FECHA_BC))*12 + SUBSTR(FECHA,5,2) - MONTH(FECHA_BC) BETWEEN 0 AND 4);

SELECT DISTINCT LINEA FROM JEA_MCV_UNIVERSO_FOLIO;