%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_RESUMEN_IQ_PCT;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_RESUMEN_IQ_PCT
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_RESUMEN_IQ_PCT' AS

SELECT
A.CUENTADEREFERENCIA, 
A.FECHA_CARTERA,

A.NUM_IQ_03M_FL/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_FL,
A.NUM_IQ_03M_BK/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_BK,
A.NUM_IQ_03M_BK_AU/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_BK_AU,
A.NUM_IQ_03M_BK_M/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_BK_M,
A.NUM_IQ_03M_BK_PL/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_BK_PL,
A.NUM_IQ_03M_BK_R/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_BK_R,
A.NUM_IQ_03M_NBK/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_NBK,
A.NUM_IQ_03M_NBK_AU/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_NBK_AU,
A.NUM_IQ_03M_NBK_M/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_NBK_M,
A.NUM_IQ_03M_NBK_PL/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_NBK_PL,
A.NUM_IQ_03M_NBK_R/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_NBK_R,
A.NUM_IQ_03M_AMX/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_AMX,
A.NUM_IQ_03M_AU/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_AU,
A.NUM_IQ_03M_M/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_M,
A.NUM_IQ_03M_PL/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_PL,
A.NUM_IQ_03M_R/B.NUM_IQ_03M AS PCT_NUM_IQ_03M_R,


A.NUM_IQ_06M_FL/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_FL,
A.NUM_IQ_06M_BK/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_BK,
A.NUM_IQ_06M_BK_AU/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_BK_AU,
A.NUM_IQ_06M_BK_M/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_BK_M,
A.NUM_IQ_06M_BK_PL/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_BK_PL,
A.NUM_IQ_06M_BK_R/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_BK_R,
A.NUM_IQ_06M_NBK/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_NBK,
A.NUM_IQ_06M_NBK_AU/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_NBK_AU,
A.NUM_IQ_06M_NBK_M/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_NBK_M,
A.NUM_IQ_06M_NBK_PL/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_NBK_PL,
A.NUM_IQ_06M_NBK_R/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_NBK_R,
A.NUM_IQ_06M_AMX/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_AMX,
A.NUM_IQ_06M_AU/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_AU,
A.NUM_IQ_06M_M/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_M,
A.NUM_IQ_06M_PL/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_PL,
A.NUM_IQ_06M_R/B.NUM_IQ_06M AS PCT_NUM_IQ_06M_R,


A.NUM_IQ_12M_FL/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_FL,
A.NUM_IQ_12M_BK/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_BK,
A.NUM_IQ_12M_BK_AU/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_BK_AU,
A.NUM_IQ_12M_BK_M/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_BK_M,
A.NUM_IQ_12M_BK_PL/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_BK_PL,
A.NUM_IQ_12M_BK_R/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_BK_R,
A.NUM_IQ_12M_NBK/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_NBK,
A.NUM_IQ_12M_NBK_AU/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_NBK_AU,
A.NUM_IQ_12M_NBK_M/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_NBK_M,
A.NUM_IQ_12M_NBK_PL/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_NBK_PL,
A.NUM_IQ_12M_NBK_R/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_NBK_R,
A.NUM_IQ_12M_AMX/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_AMX,
A.NUM_IQ_12M_AU/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_AU,
A.NUM_IQ_12M_M/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_M,
A.NUM_IQ_12M_PL/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_PL,
A.NUM_IQ_12M_R/B.NUM_IQ_12M AS PCT_NUM_IQ_12M_R,


A.NUM_IQ_18M_FL/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_FL,
A.NUM_IQ_18M_BK/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_BK,
A.NUM_IQ_18M_BK_AU/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_BK_AU,
A.NUM_IQ_18M_BK_M/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_BK_M,
A.NUM_IQ_18M_BK_PL/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_BK_PL,
A.NUM_IQ_18M_BK_R/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_BK_R,
A.NUM_IQ_18M_NBK/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_NBK,
A.NUM_IQ_18M_NBK_AU/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_NBK_AU,
A.NUM_IQ_18M_NBK_M/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_NBK_M,
A.NUM_IQ_18M_NBK_PL/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_NBK_PL,
A.NUM_IQ_18M_NBK_R/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_NBK_R,
A.NUM_IQ_18M_AMX/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_AMX,
A.NUM_IQ_18M_AU/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_AU,
A.NUM_IQ_18M_M/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_M,
A.NUM_IQ_18M_PL/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_PL,
A.NUM_IQ_18M_R/B.NUM_IQ_18M AS PCT_NUM_IQ_18M_R,


A.NUM_IQ_24M_FL/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_FL,
A.NUM_IQ_24M_BK/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_BK,
A.NUM_IQ_24M_BK_AU/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_BK_AU,
A.NUM_IQ_24M_BK_M/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_BK_M,
A.NUM_IQ_24M_BK_PL/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_BK_PL,
A.NUM_IQ_24M_BK_R/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_BK_R,
A.NUM_IQ_24M_NBK/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_NBK,
A.NUM_IQ_24M_NBK_AU/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_NBK_AU,
A.NUM_IQ_24M_NBK_M/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_NBK_M,
A.NUM_IQ_24M_NBK_PL/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_NBK_PL,
A.NUM_IQ_24M_NBK_R/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_NBK_R,
A.NUM_IQ_24M_AMX/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_AMX,
A.NUM_IQ_24M_AU/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_AU,
A.NUM_IQ_24M_M/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_M,
A.NUM_IQ_24M_PL/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_PL,
A.NUM_IQ_24M_R/B.NUM_IQ_24M AS PCT_NUM_IQ_24M_R

	
FROM
    dbmymwork.BTDC_LGG_VAR_RESUMEN_IQ A
LEFT JOIN
    dbmymwork.BTDC_LGG_VAR_RESUMEN_IQ B
ON
   A.CUENTADEREFERENCIA = B.CUENTADEREFERENCIA AND A.FECHA_CARTERA = B.FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_RESUMEN_IQ_PCT LIMIT 100;

