%hive
use dbmymwork;

DROP TABLE IF EXISTS BTDC_LGG_VAR_R_MOP_BAL_BY_CRED_LIM;
CREATE TABLE BTDC_LGG_VAR_R_MOP_BAL_BY_CRED_LIM
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_R_MOP_BAL_BY_CRED_LIM' AS

SELECT
CUENTADEREFERENCIA,FECHA_CARTERA,

COUNT(R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC ) AS NUM_R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC , 
COUNT(R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC) AS NUM_R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC,
COUNT(R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    ) AS NUM_R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    ,

ROUND(MAX(R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC ) , 4)  AS MAX_R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC , 
ROUND(MAX(R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC) , 4)  AS MAX_R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC,
ROUND(MAX(R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    ) , 4)  AS MAX_R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    ,
  
ROUND(SUM(R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC ) , 4)  AS SUM_R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC , 
ROUND(SUM(R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC) , 4)  AS SUM_R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC,
ROUND(SUM(R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    ) , 4)  AS SUM_R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    ,

ROUND(SUM(R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC ) / COUNT(R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC ) , 4)  AS AVG_R_MOP_BAL_BY_CRED_LIM_BK_R_OP_ACC , 
ROUND(SUM(R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC) / COUNT(R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC) , 4)  AS AVG_R_MOP_BAL_BY_CRED_LIM_NBK_R_OP_ACC,
ROUND(SUM(R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    ) / COUNT(R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    ) , 4)  AS AVG_R_MOP_BAL_BY_CRED_LIM_R_OP_ACC    

FROM BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,FECHA_CARTERA
;

SELECT * FROM BTDC_LGG_VAR_R_MOP_BAL_BY_CRED_LIM LIMIT 100;