%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_PCT_DLQ_BAL;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_PCT_DLQ_BAL
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_PCT_DLQ_BAL' AS

SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,

COUNT(PCT_DLQ_BAL_AMX_OP_ACC)    AS NUM_PCT_DLQ_BAL_AMX_OP_ACC   ,
COUNT(PCT_DLQ_BAL_AU_OP_ACC)     AS NUM_PCT_DLQ_BAL_AU_OP_ACC    ,
COUNT(PCT_DLQ_BAL_BK_AU_OP_ACC)  AS NUM_PCT_DLQ_BAL_BK_AU_OP_ACC ,
COUNT(PCT_DLQ_BAL_BK_M_OP_ACC)   AS NUM_PCT_DLQ_BAL_BK_M_OP_ACC  ,
COUNT(PCT_DLQ_BAL_BK_OP_ACC)     AS NUM_PCT_DLQ_BAL_BK_OP_ACC    ,
COUNT(PCT_DLQ_BAL_BK_PL_OP_ACC)  AS NUM_PCT_DLQ_BAL_BK_PL_OP_ACC ,
COUNT(PCT_DLQ_BAL_BK_R_OP_ACC)   AS NUM_PCT_DLQ_BAL_BK_R_OP_ACC  ,
COUNT(PCT_DLQ_BAL_M_OP_ACC)      AS NUM_PCT_DLQ_BAL_M_OP_ACC     ,
COUNT(PCT_DLQ_BAL_NBK_AU_OP_ACC) AS NUM_PCT_DLQ_BAL_NBK_AU_OP_ACC,
COUNT(PCT_DLQ_BAL_NBK_M_OP_ACC)  AS NUM_PCT_DLQ_BAL_NBK_M_OP_ACC ,
COUNT(PCT_DLQ_BAL_NBK_OP_ACC)    AS NUM_PCT_DLQ_BAL_NBK_OP_ACC   ,
COUNT(PCT_DLQ_BAL_NBK_PL_OP_ACC) AS NUM_PCT_DLQ_BAL_NBK_PL_OP_ACC,
COUNT(PCT_DLQ_BAL_NBK_R_OP_ACC)  AS NUM_PCT_DLQ_BAL_NBK_R_OP_ACC ,
COUNT(PCT_DLQ_BAL_OP_ACC)        AS NUM_PCT_DLQ_BAL_OP_ACC       ,
COUNT(PCT_DLQ_BAL_PL_OP_ACC)     AS NUM_PCT_DLQ_BAL_PL_OP_ACC    ,
COUNT(PCT_DLQ_BAL_R_OP_ACC)      AS NUM_PCT_DLQ_BAL_R_OP_ACC     ,
COUNT(PCT_DLQ_BAL_TU_OP_ACC    ) AS NUM_PCT_DLQ_BAL_TU_OP_ACC    ,
COUNT(PCT_DLQ_BAL_TU_ALL_OP_ACC) AS NUM_PCT_DLQ_BAL_TU_ALL_OP_ACC,
COUNT(PCT_DLQ_BAL_NBK_TU_OP_ACC) AS NUM_PCT_DLQ_BAL_NBK_TU_OP_ACC,

MAX(PCT_DLQ_BAL_AMX_OP_ACC)    AS MAX_PCT_DLQ_BAL_AMX_OP_ACC   ,
MAX(PCT_DLQ_BAL_AU_OP_ACC)     AS MAX_PCT_DLQ_BAL_AU_OP_ACC    ,
MAX(PCT_DLQ_BAL_BK_AU_OP_ACC)  AS MAX_PCT_DLQ_BAL_BK_AU_OP_ACC ,
MAX(PCT_DLQ_BAL_BK_M_OP_ACC)   AS MAX_PCT_DLQ_BAL_BK_M_OP_ACC  ,
MAX(PCT_DLQ_BAL_BK_OP_ACC)     AS MAX_PCT_DLQ_BAL_BK_OP_ACC    ,
MAX(PCT_DLQ_BAL_BK_PL_OP_ACC)  AS MAX_PCT_DLQ_BAL_BK_PL_OP_ACC ,
MAX(PCT_DLQ_BAL_BK_R_OP_ACC)   AS MAX_PCT_DLQ_BAL_BK_R_OP_ACC  ,
MAX(PCT_DLQ_BAL_M_OP_ACC)      AS MAX_PCT_DLQ_BAL_M_OP_ACC     ,
MAX(PCT_DLQ_BAL_NBK_AU_OP_ACC) AS MAX_PCT_DLQ_BAL_NBK_AU_OP_ACC,
MAX(PCT_DLQ_BAL_NBK_M_OP_ACC)  AS MAX_PCT_DLQ_BAL_NBK_M_OP_ACC ,
MAX(PCT_DLQ_BAL_NBK_OP_ACC)    AS MAX_PCT_DLQ_BAL_NBK_OP_ACC   ,
MAX(PCT_DLQ_BAL_NBK_PL_OP_ACC) AS MAX_PCT_DLQ_BAL_NBK_PL_OP_ACC,
MAX(PCT_DLQ_BAL_NBK_R_OP_ACC)  AS MAX_PCT_DLQ_BAL_NBK_R_OP_ACC ,
MAX(PCT_DLQ_BAL_OP_ACC)        AS MAX_PCT_DLQ_BAL_OP_ACC       ,
MAX(PCT_DLQ_BAL_PL_OP_ACC)     AS MAX_PCT_DLQ_BAL_PL_OP_ACC    ,
MAX(PCT_DLQ_BAL_R_OP_ACC)      AS MAX_PCT_DLQ_BAL_R_OP_ACC     ,
MAX(PCT_DLQ_BAL_TU_OP_ACC    ) AS MAX_PCT_DLQ_BAL_TU_OP_ACC    ,
MAX(PCT_DLQ_BAL_TU_ALL_OP_ACC) AS MAX_PCT_DLQ_BAL_TU_ALL_OP_ACC,
MAX(PCT_DLQ_BAL_NBK_TU_OP_ACC) AS MAX_PCT_DLQ_BAL_NBK_TU_OP_ACC,

SUM(PCT_DLQ_BAL_AMX_OP_ACC)    AS SUM_PCT_DLQ_BAL_AMX_OP_ACC   ,
SUM(PCT_DLQ_BAL_AU_OP_ACC)     AS SUM_PCT_DLQ_BAL_AU_OP_ACC    ,
SUM(PCT_DLQ_BAL_BK_AU_OP_ACC)  AS SUM_PCT_DLQ_BAL_BK_AU_OP_ACC ,
SUM(PCT_DLQ_BAL_BK_M_OP_ACC)   AS SUM_PCT_DLQ_BAL_BK_M_OP_ACC  ,
SUM(PCT_DLQ_BAL_BK_OP_ACC)     AS SUM_PCT_DLQ_BAL_BK_OP_ACC    ,
SUM(PCT_DLQ_BAL_BK_PL_OP_ACC)  AS SUM_PCT_DLQ_BAL_BK_PL_OP_ACC ,
SUM(PCT_DLQ_BAL_BK_R_OP_ACC)   AS SUM_PCT_DLQ_BAL_BK_R_OP_ACC  ,
SUM(PCT_DLQ_BAL_M_OP_ACC)      AS SUM_PCT_DLQ_BAL_M_OP_ACC     ,
SUM(PCT_DLQ_BAL_NBK_AU_OP_ACC) AS SUM_PCT_DLQ_BAL_NBK_AU_OP_ACC,
SUM(PCT_DLQ_BAL_NBK_M_OP_ACC)  AS SUM_PCT_DLQ_BAL_NBK_M_OP_ACC ,
SUM(PCT_DLQ_BAL_NBK_OP_ACC)    AS SUM_PCT_DLQ_BAL_NBK_OP_ACC   ,
SUM(PCT_DLQ_BAL_NBK_PL_OP_ACC) AS SUM_PCT_DLQ_BAL_NBK_PL_OP_ACC,
SUM(PCT_DLQ_BAL_NBK_R_OP_ACC)  AS SUM_PCT_DLQ_BAL_NBK_R_OP_ACC ,
SUM(PCT_DLQ_BAL_OP_ACC)        AS SUM_PCT_DLQ_BAL_OP_ACC       ,
SUM(PCT_DLQ_BAL_PL_OP_ACC)     AS SUM_PCT_DLQ_BAL_PL_OP_ACC    ,
SUM(PCT_DLQ_BAL_R_OP_ACC)      AS SUM_PCT_DLQ_BAL_R_OP_ACC     ,
SUM(PCT_DLQ_BAL_TU_OP_ACC    ) AS SUM_PCT_DLQ_BAL_TU_OP_ACC    ,
SUM(PCT_DLQ_BAL_TU_ALL_OP_ACC) AS SUM_PCT_DLQ_BAL_TU_ALL_OP_ACC,
SUM(PCT_DLQ_BAL_NBK_TU_OP_ACC) AS SUM_PCT_DLQ_BAL_NBK_TU_OP_ACC,
 
ROUND( SUM(PCT_DLQ_BAL_AMX_OP_ACC)    / COUNT(PCT_DLQ_BAL_AMX_OP_ACC)    ,4) AS AVG_PCT_DLQ_BAL_AMX_OP_ACC   ,
ROUND( SUM(PCT_DLQ_BAL_AU_OP_ACC)     / COUNT(PCT_DLQ_BAL_AU_OP_ACC)     ,4) AS AVG_PCT_DLQ_BAL_AU_OP_ACC    ,
ROUND( SUM(PCT_DLQ_BAL_BK_AU_OP_ACC)  / COUNT(PCT_DLQ_BAL_BK_AU_OP_ACC)  ,4) AS AVG_PCT_DLQ_BAL_BK_AU_OP_ACC ,
ROUND( SUM(PCT_DLQ_BAL_BK_M_OP_ACC)   / COUNT(PCT_DLQ_BAL_BK_M_OP_ACC)   ,4) AS AVG_PCT_DLQ_BAL_BK_M_OP_ACC  ,
ROUND( SUM(PCT_DLQ_BAL_BK_OP_ACC)     / COUNT(PCT_DLQ_BAL_BK_OP_ACC)     ,4) AS AVG_PCT_DLQ_BAL_BK_OP_ACC    ,
ROUND( SUM(PCT_DLQ_BAL_BK_PL_OP_ACC)  / COUNT(PCT_DLQ_BAL_BK_PL_OP_ACC)  ,4) AS AVG_PCT_DLQ_BAL_BK_PL_OP_ACC ,
ROUND( SUM(PCT_DLQ_BAL_BK_R_OP_ACC)   / COUNT(PCT_DLQ_BAL_BK_R_OP_ACC)   ,4) AS AVG_PCT_DLQ_BAL_BK_R_OP_ACC  ,
ROUND( SUM(PCT_DLQ_BAL_M_OP_ACC)      / COUNT(PCT_DLQ_BAL_M_OP_ACC)      ,4) AS AVG_PCT_DLQ_BAL_M_OP_ACC     ,
ROUND( SUM(PCT_DLQ_BAL_NBK_AU_OP_ACC) / COUNT(PCT_DLQ_BAL_NBK_AU_OP_ACC) ,4) AS AVG_PCT_DLQ_BAL_NBK_AU_OP_ACC,
ROUND( SUM(PCT_DLQ_BAL_NBK_M_OP_ACC)  / COUNT(PCT_DLQ_BAL_NBK_M_OP_ACC)  ,4) AS AVG_PCT_DLQ_BAL_NBK_M_OP_ACC ,
ROUND( SUM(PCT_DLQ_BAL_NBK_OP_ACC)    / COUNT(PCT_DLQ_BAL_NBK_OP_ACC)    ,4) AS AVG_PCT_DLQ_BAL_NBK_OP_ACC   ,
ROUND( SUM(PCT_DLQ_BAL_NBK_PL_OP_ACC) / COUNT(PCT_DLQ_BAL_NBK_PL_OP_ACC) ,4) AS AVG_PCT_DLQ_BAL_NBK_PL_OP_ACC,
ROUND( SUM(PCT_DLQ_BAL_NBK_R_OP_ACC)  / COUNT(PCT_DLQ_BAL_NBK_R_OP_ACC)  ,4) AS AVG_PCT_DLQ_BAL_NBK_R_OP_ACC ,
ROUND( SUM(PCT_DLQ_BAL_OP_ACC)        / COUNT(PCT_DLQ_BAL_OP_ACC)        ,4) AS AVG_PCT_DLQ_BAL_OP_ACC       ,
ROUND( SUM(PCT_DLQ_BAL_PL_OP_ACC)     / COUNT(PCT_DLQ_BAL_PL_OP_ACC)     ,4) AS AVG_PCT_DLQ_BAL_PL_OP_ACC    ,
ROUND( SUM(PCT_DLQ_BAL_R_OP_ACC)      / COUNT(PCT_DLQ_BAL_R_OP_ACC)      ,4) AS AVG_PCT_DLQ_BAL_R_OP_ACC     ,
ROUND( SUM(PCT_DLQ_BAL_TU_OP_ACC    ) / COUNT(PCT_DLQ_BAL_TU_OP_ACC    ) ,4) AS AVG_PCT_DLQ_BAL_TU_OP_ACC    ,
ROUND( SUM(PCT_DLQ_BAL_TU_ALL_OP_ACC) / COUNT(PCT_DLQ_BAL_TU_ALL_OP_ACC) ,4) AS AVG_PCT_DLQ_BAL_TU_ALL_OP_ACC,
ROUND( SUM(PCT_DLQ_BAL_NBK_TU_OP_ACC) / COUNT(PCT_DLQ_BAL_NBK_TU_OP_ACC) ,4) AS AVG_PCT_DLQ_BAL_NBK_TU_OP_ACC

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_PCT_DLQ_BAL LIMIT 100;