%hive
DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_CRED_LIM;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_CRED_LIM
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_CRED_LIM' AS
SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,

COUNT(CRED_LIM_BK_R_CL_ACC)  AS NUM_CRED_LIM_BK_R_CL_ACC  ,
COUNT(CRED_LIM_BK_R_OP_ACC)  AS NUM_CRED_LIM_BK_R_OP_ACC  ,
COUNT(CRED_LIM_BK_R)         AS NUM_CRED_LIM_BK_R        ,
COUNT(CRED_LIM_NBK_R_CL_ACC) AS NUM_CRED_LIM_NBK_R_CL_ACC ,
COUNT(CRED_LIM_NBK_R_OP_ACC) AS NUM_CRED_LIM_NBK_R_OP_ACC ,
COUNT(CRED_LIM_NBK_R)        AS NUM_CRED_LIM_NBK_R        ,
COUNT(CRED_LIM_R_CL_ACC)     AS NUM_CRED_LIM_R_CL_ACC     ,
COUNT(CRED_LIM_R_OP_ACC)     AS NUM_CRED_LIM_R_OP_ACC     ,
COUNT(CRED_LIM_R)            AS NUM_CRED_LIM_R            ,      
-- MAX
MAX(CRED_LIM_BK_R_CL_ACC)  AS MAX_CRED_LIM_BK_R_CL_ACC  ,
MAX(CRED_LIM_BK_R_OP_ACC)  AS MAX_CRED_LIM_BK_R_OP_ACC  ,
MAX(CRED_LIM_BK_R)         AS MAX_CRED_LIM_BK_R        ,
MAX(CRED_LIM_NBK_R_CL_ACC) AS MAX_CRED_LIM_NBK_R_CL_ACC ,
MAX(CRED_LIM_NBK_R_OP_ACC) AS MAX_CRED_LIM_NBK_R_OP_ACC ,
MAX(CRED_LIM_NBK_R)        AS MAX_CRED_LIM_NBK_R        ,
MAX(CRED_LIM_R_CL_ACC)     AS MAX_CRED_LIM_R_CL_ACC     ,
MAX(CRED_LIM_R_OP_ACC)     AS MAX_CRED_LIM_R_OP_ACC     ,
MAX(CRED_LIM_R)            AS MAX_CRED_LIM_R            ,         

-- SUM
SUM(CRED_LIM_BK_R_CL_ACC)  AS SUM_CRED_LIM_BK_R_CL_ACC ,
SUM(CRED_LIM_BK_R_OP_ACC)  AS SUM_CRED_LIM_BK_R_OP_ACC ,
SUM(CRED_LIM_BK_R)         AS  SUM_CRED_LIM_BK_R       ,
SUM(CRED_LIM_NBK_R_CL_ACC) AS SUM_CRED_LIM_NBK_R_CL_ACC,
SUM(CRED_LIM_NBK_R_OP_ACC) AS SUM_CRED_LIM_NBK_R_OP_ACC,
SUM(CRED_LIM_NBK_R)        AS SUM_CRED_LIM_NBK_R       ,
SUM(CRED_LIM_R_CL_ACC)     AS SUM_CRED_LIM_R_CL_ACC    ,
SUM(CRED_LIM_R_OP_ACC)     AS SUM_CRED_LIM_R_OP_ACC    ,
SUM(CRED_LIM_R)            AS SUM_CRED_LIM_R           ,

-- AVG
ROUND(SUM(CRED_LIM_BK_R_CL_ACC) /COUNT(CRED_LIM_BK_R_CL_ACC  ) ,2)   AS AVG_CRED_LIM_BK_R_CL_ACC   , 	
ROUND(SUM(CRED_LIM_BK_R_OP_ACC) /COUNT(CRED_LIM_BK_R_OP_ACC  ) ,2)   AS AVG_CRED_LIM_BK_R_OP_ACC   ,  
ROUND(SUM(CRED_LIM_BK_R)        /COUNT(CRED_LIM_BK_R         ) ,2)   AS AVG_CRED_LIM_BK_R          ,  
ROUND(SUM(CRED_LIM_NBK_R_CL_ACC)/COUNT(CRED_LIM_NBK_R_CL_ACC ) ,2)   AS AVG_CRED_LIM_NBK_R_CL_ACC  ,  
ROUND(SUM(CRED_LIM_NBK_R_OP_ACC)/COUNT(CRED_LIM_NBK_R_OP_ACC ) ,2)   AS AVG_CRED_LIM_NBK_R_OP_ACC  ,  
ROUND(SUM(CRED_LIM_NBK_R)       /COUNT(CRED_LIM_NBK_R        ) ,2)   AS AVG_CRED_LIM_NBK_R         ,  
ROUND(SUM(CRED_LIM_R_CL_ACC)    /COUNT(CRED_LIM_R_CL_ACC     ) ,2)   AS AVG_CRED_LIM_R_CL_ACC      ,  
ROUND(SUM(CRED_LIM_R_OP_ACC)    /COUNT(CRED_LIM_R_OP_ACC     ) ,2)   AS AVG_CRED_LIM_R_OP_ACC      ,  
ROUND(SUM(CRED_LIM_R)           /COUNT(CRED_LIM_R            ) ,2)   AS AVG_CRED_LIM_R

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;
select * from dbmymwork.BTDC_LGG_VAR_CRED_LIM limit 100;
