%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_PMT;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_PMT
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_PMT' AS

SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,

COUNT(PMT_AMX_OP_ACC)    AS NUM_PMT_AMX_OP_ACC   ,
COUNT(PMT_AU_OP_ACC)     AS NUM_PMT_AU_OP_ACC    ,
COUNT(PMT_BK_AU_OP_ACC)  AS NUM_PMT_BK_AU_OP_ACC ,
COUNT(PMT_BK_M_OP_ACC)   AS NUM_PMT_BK_M_OP_ACC  ,
COUNT(PMT_BK_OP_ACC)     AS NUM_PMT_BK_OP_ACC    ,
COUNT(PMT_BK_PL_OP_ACC)  AS NUM_PMT_BK_PL_OP_ACC ,
COUNT(PMT_BK_R_OP_ACC)   AS NUM_PMT_BK_R_OP_ACC  ,
COUNT(PMT_M_OP_ACC)      AS NUM_PMT_M_OP_ACC     ,
COUNT(PMT_NBK_AU_OP_ACC) AS NUM_PMT_NBK_AU_OP_ACC,
COUNT(PMT_NBK_M_OP_ACC)  AS NUM_PMT_NBK_M_OP_ACC ,
COUNT(PMT_NBK_OP_ACC)    AS NUM_PMT_NBK_OP_ACC   ,
COUNT(PMT_NBK_PL_OP_ACC) AS NUM_PMT_NBK_PL_OP_ACC,
COUNT(PMT_NBK_R_OP_ACC)  AS NUM_PMT_NBK_R_OP_ACC ,
COUNT(PMT_OP_ACC)        AS NUM_PMT_OP_ACC       ,
COUNT(PMT_PL_OP_ACC)     AS NUM_PMT_PL_OP_ACC    ,
COUNT(PMT_R_OP_ACC)      AS NUM_PMT_R_OP_ACC     ,
COUNT(PMT_TU_OP_ACC    ) AS NUM_PMT_TU_OP_ACC    ,
COUNT(PMT_TU_ALL_OP_ACC) AS NUM_PMT_TU_ALL_OP_ACC,
COUNT(PMT_NBK_TU_OP_ACC) AS NUM_PMT_NBK_TU_OP_ACC,

MAX(PMT_AMX_OP_ACC)    AS MAX_PMT_AMX_OP_ACC   ,
MAX(PMT_AU_OP_ACC)     AS MAX_PMT_AU_OP_ACC    ,
MAX(PMT_BK_AU_OP_ACC)  AS MAX_PMT_BK_AU_OP_ACC ,
MAX(PMT_BK_M_OP_ACC)   AS MAX_PMT_BK_M_OP_ACC  ,
MAX(PMT_BK_OP_ACC)     AS MAX_PMT_BK_OP_ACC    ,
MAX(PMT_BK_PL_OP_ACC)  AS MAX_PMT_BK_PL_OP_ACC ,
MAX(PMT_BK_R_OP_ACC)   AS MAX_PMT_BK_R_OP_ACC  ,
MAX(PMT_M_OP_ACC)      AS MAX_PMT_M_OP_ACC     ,
MAX(PMT_NBK_AU_OP_ACC) AS MAX_PMT_NBK_AU_OP_ACC,
MAX(PMT_NBK_M_OP_ACC)  AS MAX_PMT_NBK_M_OP_ACC ,
MAX(PMT_NBK_OP_ACC)    AS MAX_PMT_NBK_OP_ACC   ,
MAX(PMT_NBK_PL_OP_ACC) AS MAX_PMT_NBK_PL_OP_ACC,
MAX(PMT_NBK_R_OP_ACC)  AS MAX_PMT_NBK_R_OP_ACC ,
MAX(PMT_OP_ACC)        AS MAX_PMT_OP_ACC       ,
MAX(PMT_PL_OP_ACC)     AS MAX_PMT_PL_OP_ACC    ,
MAX(PMT_R_OP_ACC)      AS MAX_PMT_R_OP_ACC     ,
MAX(PMT_TU_OP_ACC    ) AS MAX_PMT_TU_OP_ACC    ,
MAX(PMT_TU_ALL_OP_ACC) AS MAX_PMT_TU_ALL_OP_ACC,
MAX(PMT_NBK_TU_OP_ACC) AS MAX_PMT_NBK_TU_OP_ACC,

SUM(PMT_AMX_OP_ACC)    AS SUM_PMT_AMX_OP_ACC   ,
SUM(PMT_AU_OP_ACC)     AS SUM_PMT_AU_OP_ACC    ,
SUM(PMT_BK_AU_OP_ACC)  AS SUM_PMT_BK_AU_OP_ACC ,
SUM(PMT_BK_M_OP_ACC)   AS SUM_PMT_BK_M_OP_ACC  ,
SUM(PMT_BK_OP_ACC)     AS SUM_PMT_BK_OP_ACC    ,
SUM(PMT_BK_PL_OP_ACC)  AS SUM_PMT_BK_PL_OP_ACC ,
SUM(PMT_BK_R_OP_ACC)   AS SUM_PMT_BK_R_OP_ACC  ,
SUM(PMT_M_OP_ACC)      AS SUM_PMT_M_OP_ACC     ,
SUM(PMT_NBK_AU_OP_ACC) AS SUM_PMT_NBK_AU_OP_ACC,
SUM(PMT_NBK_M_OP_ACC)  AS SUM_PMT_NBK_M_OP_ACC ,
SUM(PMT_NBK_OP_ACC)    AS SUM_PMT_NBK_OP_ACC   ,
SUM(PMT_NBK_PL_OP_ACC) AS SUM_PMT_NBK_PL_OP_ACC,
SUM(PMT_NBK_R_OP_ACC)  AS SUM_PMT_NBK_R_OP_ACC ,
SUM(PMT_OP_ACC)        AS SUM_PMT_OP_ACC       ,
SUM(PMT_PL_OP_ACC)     AS SUM_PMT_PL_OP_ACC    ,
SUM(PMT_R_OP_ACC)      AS SUM_PMT_R_OP_ACC     ,
SUM(PMT_TU_OP_ACC    ) AS SUM_PMT_TU_OP_ACC    ,
SUM(PMT_TU_ALL_OP_ACC) AS SUM_PMT_TU_ALL_OP_ACC,
SUM(PMT_NBK_TU_OP_ACC) AS SUM_PMT_NBK_TU_OP_ACC,

ROUND(SUM(PMT_AMX_OP_ACC)   /COUNT(PMT_AMX_OP_ACC)    , 2) AS AVG_PMT_AMX_OP_ACC   ,
ROUND(SUM(PMT_AU_OP_ACC)    /COUNT(PMT_AU_OP_ACC)     , 2) AS AVG_PMT_AU_OP_ACC    ,
ROUND(SUM(PMT_BK_AU_OP_ACC) /COUNT(PMT_BK_AU_OP_ACC)  , 2) AS AVG_PMT_BK_AU_OP_ACC ,
ROUND(SUM(PMT_BK_M_OP_ACC)  /COUNT(PMT_BK_M_OP_ACC)   , 2) AS AVG_PMT_BK_M_OP_ACC  ,
ROUND(SUM(PMT_BK_OP_ACC)    /COUNT(PMT_BK_OP_ACC)     , 2) AS AVG_PMT_BK_OP_ACC    ,
ROUND(SUM(PMT_BK_PL_OP_ACC) /COUNT(PMT_BK_PL_OP_ACC)  , 2) AS AVG_PMT_BK_PL_OP_ACC ,
ROUND(SUM(PMT_BK_R_OP_ACC)  /COUNT(PMT_BK_R_OP_ACC)   , 2) AS AVG_PMT_BK_R_OP_ACC  ,
ROUND(SUM(PMT_M_OP_ACC)     /COUNT(PMT_M_OP_ACC)      , 2) AS AVG_PMT_M_OP_ACC     ,
ROUND(SUM(PMT_NBK_AU_OP_ACC)/COUNT(PMT_NBK_AU_OP_ACC) , 2) AS AVG_PMT_NBK_AU_OP_ACC,
ROUND(SUM(PMT_NBK_M_OP_ACC) /COUNT(PMT_NBK_M_OP_ACC)  , 2) AS AVG_PMT_NBK_M_OP_ACC ,
ROUND(SUM(PMT_NBK_OP_ACC)   /COUNT(PMT_NBK_OP_ACC)    , 2) AS AVG_PMT_NBK_OP_ACC   ,
ROUND(SUM(PMT_NBK_PL_OP_ACC)/COUNT(PMT_NBK_PL_OP_ACC) , 2) AS AVG_PMT_NBK_PL_OP_ACC,
ROUND(SUM(PMT_NBK_R_OP_ACC) /COUNT(PMT_NBK_R_OP_ACC)  , 2) AS AVG_PMT_NBK_R_OP_ACC ,
ROUND(SUM(PMT_OP_ACC)       /COUNT(PMT_OP_ACC)        , 2) AS AVG_PMT_OP_ACC       ,
ROUND(SUM(PMT_PL_OP_ACC)    /COUNT(PMT_PL_OP_ACC)     , 2) AS AVG_PMT_PL_OP_ACC    ,
ROUND(SUM(PMT_R_OP_ACC)     /COUNT(PMT_R_OP_ACC)      , 2) AS AVG_PMT_R_OP_ACC     ,
ROUND(SUM(PMT_TU_OP_ACC    )/COUNT(PMT_TU_OP_ACC    ) , 2) AS AVG_PMT_TU_OP_ACC    ,
ROUND(SUM(PMT_TU_ALL_OP_ACC)/COUNT(PMT_TU_ALL_OP_ACC) , 2) AS AVG_PMT_TU_ALL_OP_ACC,
ROUND(SUM(PMT_NBK_TU_OP_ACC)/COUNT(PMT_NBK_TU_OP_ACC) , 2) AS AVG_PMT_NBK_TU_OP_ACC

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_PMT LIMIT 100;
