%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_UTIL;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_UTIL
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_UTIL' AS

SELECT
CUENTADEREFERENCIA,FECHA_CARTERA,

COUNT(UTIL_BK_R_OP_ACC ) AS NUM_UTIL_BK_R_OP_ACC , 
COUNT(UTIL_NBK_R_OP_ACC) AS NUM_UTIL_NBK_R_OP_ACC,
COUNT(UTIL_R_OP_ACC    ) AS NUM_UTIL_R_OP_ACC    ,

MAX(UTIL_BK_R_OP_ACC )AS    MAX_UTIL_BK_R_OP_ACC , 
MAX(UTIL_NBK_R_OP_ACC)AS    MAX_UTIL_NBK_R_OP_ACC,
MAX(UTIL_R_OP_ACC    )AS    MAX_UTIL_R_OP_ACC    ,
                            
SUM(UTIL_BK_R_OP_ACC )AS    SUM_UTIL_BK_R_OP_ACC , 
SUM(UTIL_NBK_R_OP_ACC)AS    SUM_UTIL_NBK_R_OP_ACC,
SUM(UTIL_R_OP_ACC    )AS    SUM_UTIL_R_OP_ACC    ,

CASE WHEN SUM(UTIL_BK_R_OP_ACC ) <> 0 THEN ROUND(SUM(UTIL_BK_R_OP_ACC ) / COUNT(UTIL_BK_R_OP_ACC ) , 4) END AS AVG_UTIL_BK_R_OP_ACC , 
CASE WHEN SUM(UTIL_NBK_R_OP_ACC) <> 0 THEN ROUND(SUM(UTIL_NBK_R_OP_ACC) / COUNT(UTIL_NBK_R_OP_ACC) , 4) END AS AVG_UTIL_NBK_R_OP_ACC,
CASE WHEN SUM(UTIL_R_OP_ACC    ) <> 0 THEN ROUND(SUM(UTIL_R_OP_ACC    ) / COUNT(UTIL_R_OP_ACC    ) , 4) END AS AVG_UTIL_R_OP_ACC    

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_UTIL LIMIT 100;