%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_MS_LST_BUY;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_MS_LST_BUY
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_MS_LST_BUY' AS

SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,

COUNT(MS_LST_BUY_BK_R_OP_ACC ) AS NUM_MS_LST_BUY_BK_R_OP_ACC , 
COUNT(MS_LST_BUY_NBK_R_OP_ACC) AS NUM_MS_LST_BUY_NBK_R_OP_ACC,
COUNT(MS_LST_BUY_R_OP_ACC    ) AS NUM_MS_LST_BUY_R_OP_ACC    ,

MIN(MS_LST_BUY_BK_R_OP_ACC ) AS MIN_MS_LST_BUY_BK_R_OP_ACC , 
MIN(MS_LST_BUY_NBK_R_OP_ACC) AS MIN_MS_LST_BUY_NBK_R_OP_ACC,
MIN(MS_LST_BUY_R_OP_ACC    ) AS MIN_MS_LST_BUY_R_OP_ACC    ,

MAX(MS_LST_BUY_BK_R_OP_ACC )AS  MAX_MS_LST_BUY_BK_R_OP_ACC , 
MAX(MS_LST_BUY_NBK_R_OP_ACC)AS  MAX_MS_LST_BUY_NBK_R_OP_ACC,
MAX(MS_LST_BUY_R_OP_ACC    )AS  MAX_MS_LST_BUY_R_OP_ACC    ,

SUM(MS_LST_BUY_BK_R_OP_ACC )AS  SUM_MS_LST_BUY_BK_R_OP_ACC , 
SUM(MS_LST_BUY_NBK_R_OP_ACC)AS  SUM_MS_LST_BUY_NBK_R_OP_ACC,
SUM(MS_LST_BUY_R_OP_ACC    )AS  SUM_MS_LST_BUY_R_OP_ACC    ,

MAX(MS_LST_BUY_BK_R_OP_ACC )- MIN(MS_LST_BUY_BK_R_OP_ACC ) AS DIF_MS_LST_BUY_BK_R_OP_ACC ,
MAX(MS_LST_BUY_NBK_R_OP_ACC)- MIN(MS_LST_BUY_NBK_R_OP_ACC) AS DIF_MS_LST_BUY_NBK_R_OP_ACC,
MAX(MS_LST_BUY_R_OP_ACC    )- MIN(MS_LST_BUY_R_OP_ACC    ) AS DIF_MS_LST_BUY_R_OP_ACC    ,

ROUND( SUM(MS_LST_BUY_BK_R_OP_ACC ) / COUNT(MS_LST_BUY_BK_R_OP_ACC ),2)  AS AVG_MS_LST_BUY_BK_R_OP_ACC    ,
ROUND( SUM(MS_LST_BUY_NBK_R_OP_ACC) / COUNT(MS_LST_BUY_NBK_R_OP_ACC),2)  AS AVG_MS_LST_BUY_NBK_R_OP_ACC   ,
ROUND( SUM(MS_LST_BUY_R_OP_ACC    ) / COUNT(MS_LST_BUY_R_OP_ACC    ),2)  AS AVG_MS_LST_BUY_R_OP_ACC       

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_MS_LST_BUY LIMIT 100;
