%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_MAX_MOP_HIST_12M;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_MAX_MOP_HIST_12M
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_MAX_MOP_HIST_12M' AS

SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,

COUNT(MAX_MOP_HIST_12M_BK_AU_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_AU_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_AU_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_AU_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_AU_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_AU_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_AU_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_AU_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_AU_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_AU_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_AU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_AU_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK_AU) AS NUM_MAX_MOP_HIST_12M_BK_AU,
MAX(MAX_MOP_HIST_12M_BK_AU)   AS MAX_MAX_MOP_HIST_12M_BK_AU,
SUM(MAX_MOP_HIST_12M_BK_AU)   AS SUM_MAX_MOP_HIST_12M_BK_AU,
SUM(MAX_MOP_HIST_12M_BK_AU)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_AU),0) AS AVG_MAX_MOP_HIST_12M_BK_AU,

COUNT(MAX_MOP_HIST_12M_BK_M_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_M_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_M_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_M_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_M_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_M_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_M_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_M_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_M_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_M_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_M_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_M_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK_M) AS NUM_MAX_MOP_HIST_12M_BK_M,
MAX(MAX_MOP_HIST_12M_BK_M)   AS MAX_MAX_MOP_HIST_12M_BK_M,
SUM(MAX_MOP_HIST_12M_BK_M)   AS SUM_MAX_MOP_HIST_12M_BK_M,
SUM(MAX_MOP_HIST_12M_BK_M)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_M),0) AS AVG_MAX_MOP_HIST_12M_BK_M,

COUNT(MAX_MOP_HIST_12M_BK_PL_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_PL_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_PL_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_PL_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_PL_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_PL_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_PL_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_PL_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_PL_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_PL_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_PL_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_PL_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK_PL) AS NUM_MAX_MOP_HIST_12M_BK_PL,
MAX(MAX_MOP_HIST_12M_BK_PL)   AS MAX_MAX_MOP_HIST_12M_BK_PL,
SUM(MAX_MOP_HIST_12M_BK_PL)   AS SUM_MAX_MOP_HIST_12M_BK_PL,
SUM(MAX_MOP_HIST_12M_BK_PL)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_PL),0) AS AVG_MAX_MOP_HIST_12M_BK_PL,

COUNT(MAX_MOP_HIST_12M_BK_R_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_R_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_R_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_R_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_R_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_R_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_R_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_R_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_R_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_R_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_R_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_R_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK_R) AS NUM_MAX_MOP_HIST_12M_BK_R,
MAX(MAX_MOP_HIST_12M_BK_R)   AS MAX_MAX_MOP_HIST_12M_BK_R,
SUM(MAX_MOP_HIST_12M_BK_R)   AS SUM_MAX_MOP_HIST_12M_BK_R,
SUM(MAX_MOP_HIST_12M_BK_R)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_R),0) AS AVG_MAX_MOP_HIST_12M_BK_R,

COUNT(MAX_MOP_HIST_12M_BK_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK) AS NUM_MAX_MOP_HIST_12M_BK,
MAX(MAX_MOP_HIST_12M_BK)   AS MAX_MAX_MOP_HIST_12M_BK,
SUM(MAX_MOP_HIST_12M_BK)   AS SUM_MAX_MOP_HIST_12M_BK,
SUM(MAX_MOP_HIST_12M_BK)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK),0) AS AVG_MAX_MOP_HIST_12M_BK,

COUNT(MAX_MOP_HIST_12M_NBK_AU_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_AU_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_AU_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_AU_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_AU_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_AU_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_AU_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_AU_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_AU_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_AU_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_AU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_AU_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_AU) AS NUM_MAX_MOP_HIST_12M_NBK_AU,
MAX(MAX_MOP_HIST_12M_NBK_AU)   AS MAX_MAX_MOP_HIST_12M_NBK_AU,
SUM(MAX_MOP_HIST_12M_NBK_AU)   AS SUM_MAX_MOP_HIST_12M_NBK_AU,
SUM(MAX_MOP_HIST_12M_NBK_AU)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_AU),0) AS AVG_MAX_MOP_HIST_12M_NBK_AU,

COUNT(MAX_MOP_HIST_12M_NBK_M_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_M_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_M_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_M_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_M_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_M_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_M_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_M_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_M_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_M_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_M_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_M_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_M) AS NUM_MAX_MOP_HIST_12M_NBK_M,
MAX(MAX_MOP_HIST_12M_NBK_M)   AS MAX_MAX_MOP_HIST_12M_NBK_M,
SUM(MAX_MOP_HIST_12M_NBK_M)   AS SUM_MAX_MOP_HIST_12M_NBK_M,
SUM(MAX_MOP_HIST_12M_NBK_M)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_M),0) AS AVG_MAX_MOP_HIST_12M_NBK_M,

COUNT(MAX_MOP_HIST_12M_NBK_PL_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_PL_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_PL_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_PL_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_PL_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_PL_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_PL_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_PL_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_PL_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_PL_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_PL_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_PL_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_PL) AS NUM_MAX_MOP_HIST_12M_NBK_PL,
MAX(MAX_MOP_HIST_12M_NBK_PL)   AS MAX_MAX_MOP_HIST_12M_NBK_PL,
SUM(MAX_MOP_HIST_12M_NBK_PL)   AS SUM_MAX_MOP_HIST_12M_NBK_PL,
SUM(MAX_MOP_HIST_12M_NBK_PL)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_PL),0) AS AVG_MAX_MOP_HIST_12M_NBK_PL,

COUNT(MAX_MOP_HIST_12M_NBK_R_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_R_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_R_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_R_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_R_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_R_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_R_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_R_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_R_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_R_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_R_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_R_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_R) AS NUM_MAX_MOP_HIST_12M_NBK_R,
MAX(MAX_MOP_HIST_12M_NBK_R)   AS MAX_MAX_MOP_HIST_12M_NBK_R,
SUM(MAX_MOP_HIST_12M_NBK_R)   AS SUM_MAX_MOP_HIST_12M_NBK_R,
SUM(MAX_MOP_HIST_12M_NBK_R)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_R),0) AS AVG_MAX_MOP_HIST_12M_NBK_R,

COUNT(MAX_MOP_HIST_12M_NBK_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK) AS NUM_MAX_MOP_HIST_12M_NBK,
MAX(MAX_MOP_HIST_12M_NBK)   AS MAX_MAX_MOP_HIST_12M_NBK,
SUM(MAX_MOP_HIST_12M_NBK)   AS SUM_MAX_MOP_HIST_12M_NBK,
SUM(MAX_MOP_HIST_12M_NBK)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK),0) AS AVG_MAX_MOP_HIST_12M_NBK,

COUNT(MAX_MOP_HIST_12M_AMX_CL_ACC) AS NUM_MAX_MOP_HIST_12M_AMX_CL_ACC,
MAX(MAX_MOP_HIST_12M_AMX_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_AMX_CL_ACC,
SUM(MAX_MOP_HIST_12M_AMX_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_AMX_CL_ACC,
SUM(MAX_MOP_HIST_12M_AMX_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_AMX_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_AMX_CL_ACC,

COUNT(MAX_MOP_HIST_12M_AMX_OP_ACC) AS NUM_MAX_MOP_HIST_12M_AMX_OP_ACC,
MAX(MAX_MOP_HIST_12M_AMX_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_AMX_OP_ACC,
SUM(MAX_MOP_HIST_12M_AMX_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_AMX_OP_ACC,
SUM(MAX_MOP_HIST_12M_AMX_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_AMX_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_AMX_OP_ACC,

COUNT(MAX_MOP_HIST_12M_AMX) AS NUM_MAX_MOP_HIST_12M_AMX,
MAX(MAX_MOP_HIST_12M_AMX)   AS MAX_MAX_MOP_HIST_12M_AMX,
SUM(MAX_MOP_HIST_12M_AMX)   AS SUM_MAX_MOP_HIST_12M_AMX,
SUM(MAX_MOP_HIST_12M_AMX)/NULLIF(COUNT(MAX_MOP_HIST_12M_AMX),0) AS AVG_MAX_MOP_HIST_12M_AMX,

COUNT(MAX_MOP_HIST_12M_AU_CL_ACC) AS NUM_MAX_MOP_HIST_12M_AU_CL_ACC,
MAX(MAX_MOP_HIST_12M_AU_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_AU_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_AU_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_AU_CL_ACC,

COUNT(MAX_MOP_HIST_12M_AU_OP_ACC) AS NUM_MAX_MOP_HIST_12M_AU_OP_ACC,
MAX(MAX_MOP_HIST_12M_AU_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_AU_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_AU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_AU_OP_ACC,

COUNT(MAX_MOP_HIST_12M_AU) AS NUM_MAX_MOP_HIST_12M_AU,
MAX(MAX_MOP_HIST_12M_AU)   AS MAX_MAX_MOP_HIST_12M_AU,
SUM(MAX_MOP_HIST_12M_AU)   AS SUM_MAX_MOP_HIST_12M_AU,
SUM(MAX_MOP_HIST_12M_AU)/NULLIF(COUNT(MAX_MOP_HIST_12M_AU),0) AS AVG_MAX_MOP_HIST_12M_AU,

COUNT(MAX_MOP_HIST_12M_M_CL_ACC) AS NUM_MAX_MOP_HIST_12M_M_CL_ACC,
MAX(MAX_MOP_HIST_12M_M_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_M_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_M_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_M_CL_ACC,

COUNT(MAX_MOP_HIST_12M_M_OP_ACC) AS NUM_MAX_MOP_HIST_12M_M_OP_ACC,
MAX(MAX_MOP_HIST_12M_M_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_M_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_M_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_M_OP_ACC,

COUNT(MAX_MOP_HIST_12M_M) AS NUM_MAX_MOP_HIST_12M_M,
MAX(MAX_MOP_HIST_12M_M)   AS MAX_MAX_MOP_HIST_12M_M,
SUM(MAX_MOP_HIST_12M_M)   AS SUM_MAX_MOP_HIST_12M_M,
SUM(MAX_MOP_HIST_12M_M)/NULLIF(COUNT(MAX_MOP_HIST_12M_M),0) AS AVG_MAX_MOP_HIST_12M_M,

COUNT(MAX_MOP_HIST_12M_PL_CL_ACC) AS NUM_MAX_MOP_HIST_12M_PL_CL_ACC,
MAX(MAX_MOP_HIST_12M_PL_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_PL_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_PL_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_PL_CL_ACC,

COUNT(MAX_MOP_HIST_12M_PL_OP_ACC) AS NUM_MAX_MOP_HIST_12M_PL_OP_ACC,
MAX(MAX_MOP_HIST_12M_PL_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_PL_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_PL_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_PL_OP_ACC,

COUNT(MAX_MOP_HIST_12M_PL) AS NUM_MAX_MOP_HIST_12M_PL,
MAX(MAX_MOP_HIST_12M_PL)   AS MAX_MAX_MOP_HIST_12M_PL,
SUM(MAX_MOP_HIST_12M_PL)   AS SUM_MAX_MOP_HIST_12M_PL,
SUM(MAX_MOP_HIST_12M_PL)/NULLIF(COUNT(MAX_MOP_HIST_12M_PL),0) AS AVG_MAX_MOP_HIST_12M_PL,

COUNT(MAX_MOP_HIST_12M_R_CL_ACC) AS NUM_MAX_MOP_HIST_12M_R_CL_ACC,
MAX(MAX_MOP_HIST_12M_R_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_R_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_R_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_R_CL_ACC,

COUNT(MAX_MOP_HIST_12M_R_OP_ACC) AS NUM_MAX_MOP_HIST_12M_R_OP_ACC,
MAX(MAX_MOP_HIST_12M_R_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_R_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_R_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_R_OP_ACC,

COUNT(MAX_MOP_HIST_12M_R) AS NUM_MAX_MOP_HIST_12M_R,
MAX(MAX_MOP_HIST_12M_R)   AS MAX_MAX_MOP_HIST_12M_R,
SUM(MAX_MOP_HIST_12M_R)   AS SUM_MAX_MOP_HIST_12M_R,
SUM(MAX_MOP_HIST_12M_R)/NULLIF(COUNT(MAX_MOP_HIST_12M_R),0) AS AVG_MAX_MOP_HIST_12M_R,

COUNT(MAX_MOP_HIST_12M_CL_ACC) AS NUM_MAX_MOP_HIST_12M_CL_ACC,
MAX(MAX_MOP_HIST_12M_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_CL_ACC,
SUM(MAX_MOP_HIST_12M_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_CL_ACC,
SUM(MAX_MOP_HIST_12M_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_CL_ACC,

COUNT(MAX_MOP_HIST_12M_OP_ACC) AS NUM_MAX_MOP_HIST_12M_OP_ACC,
MAX(MAX_MOP_HIST_12M_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_OP_ACC,
SUM(MAX_MOP_HIST_12M_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_OP_ACC,
SUM(MAX_MOP_HIST_12M_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_OP_ACC,

COUNT(MAX_MOP_HIST_12M) AS NUM_MAX_MOP_HIST_12M,
MAX(MAX_MOP_HIST_12M)   AS MAX_MAX_MOP_HIST_12M,
SUM(MAX_MOP_HIST_12M)   AS SUM_MAX_MOP_HIST_12M,
SUM(MAX_MOP_HIST_12M)/NULLIF(COUNT(MAX_MOP_HIST_12M),0) AS AVG_MAX_MOP_HIST_12M,                             

-- COMUNICACIONES Y SERVICIOS

COUNT(MAX_MOP_HIST_12M_TU_ALL ) AS NUM_MAX_MOP_HIST_12M_TU_ALL, 
MAX(MAX_MOP_HIST_12M_TU_ALL   ) AS MAX_MAX_MOP_HIST_12M_TU_ALL,
SUM(MAX_MOP_HIST_12M_TU_ALL   ) AS SUM_MAX_MOP_HIST_12M_TU_ALL,
SUM(MAX_MOP_HIST_12M_TU_ALL)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_ALL),0) AS AVG_MAX_MOP_HIST_12M_TU_ALL,
                            
COUNT(MAX_MOP_HIST_12M_TU) AS NUM_MAX_MOP_HIST_12M_TU,
MAX(MAX_MOP_HIST_12M_TU  ) AS MAX_MAX_MOP_HIST_12M_TU,
SUM(MAX_MOP_HIST_12M_TU  ) AS SUM_MAX_MOP_HIST_12M_TU,
SUM(MAX_MOP_HIST_12M_TU)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU),0) AS AVG_MAX_MOP_HIST_12M_TU,

COUNT(MAX_MOP_HIST_12M_TU_ALL_OP_ACC ) AS NUM_MAX_MOP_HIST_12M_TU_ALL_OP_ACC,
MAX(MAX_MOP_HIST_12M_TU_ALL_OP_ACC   ) AS MAX_MAX_MOP_HIST_12M_TU_ALL_OP_ACC,
SUM(MAX_MOP_HIST_12M_TU_ALL_OP_ACC   ) AS SUM_MAX_MOP_HIST_12M_TU_ALL_OP_ACC,
SUM(MAX_MOP_HIST_12M_TU_ALL_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_ALL_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_TU_ALL_OP_ACC,
    
COUNT(MAX_MOP_HIST_12M_TU_OP_ACC ) AS NUM_MAX_MOP_HIST_12M_TU_OP_ACC,
MAX(MAX_MOP_HIST_12M_TU_OP_ACC   ) AS MAX_MAX_MOP_HIST_12M_TU_OP_ACC,
SUM(MAX_MOP_HIST_12M_TU_OP_ACC   ) AS SUM_MAX_MOP_HIST_12M_TU_OP_ACC,
SUM(MAX_MOP_HIST_12M_TU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_TU_OP_ACC,
    
COUNT(MAX_MOP_HIST_12M_TU_ALL_CL_ACC ) AS NUM_MAX_MOP_HIST_12M_TU_ALL_CL_ACC,
MAX(MAX_MOP_HIST_12M_TU_ALL_CL_ACC   ) AS MAX_MAX_MOP_HIST_12M_TU_ALL_CL_ACC,
SUM(MAX_MOP_HIST_12M_TU_ALL_CL_ACC   ) AS SUM_MAX_MOP_HIST_12M_TU_ALL_CL_ACC,
SUM(MAX_MOP_HIST_12M_TU_ALL_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_ALL_CL_ACC),0)  AS AVG_MAX_MOP_HIST_12M_TU_ALL_CL_ACC,
    
COUNT(MAX_MOP_HIST_12M_TU_CL_ACC  ) AS NUM_MAX_MOP_HIST_12M_TU_CL_ACC,
MAX(MAX_MOP_HIST_12M_TU_CL_ACC    ) AS MAX_MAX_MOP_HIST_12M_TU_CL_ACC,
SUM(MAX_MOP_HIST_12M_TU_CL_ACC    ) AS SUM_MAX_MOP_HIST_12M_TU_CL_ACC,
SUM(MAX_MOP_HIST_12M_TU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_TU_CL_ACC,
    
COUNT(MAX_MOP_HIST_12M_NBK_TU  ) AS NUM_MAX_MOP_HIST_12M_NBK_TU,
MAX(MAX_MOP_HIST_12M_NBK_TU    ) AS MAX_MAX_MOP_HIST_12M_NBK_TU,
SUM(MAX_MOP_HIST_12M_NBK_TU    ) AS SUM_MAX_MOP_HIST_12M_NBK_TU,
SUM(MAX_MOP_HIST_12M_NBK_TU)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_TU),0)  AS AVG_MAX_MOP_HIST_12M_NBK_TU,
    
COUNT(MAX_MOP_HIST_12M_NBK_TU_OP_ACC  ) AS NUM_MAX_MOP_HIST_12M_NBK_TU_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_TU_OP_ACC    ) AS MAX_MAX_MOP_HIST_12M_NBK_TU_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_TU_OP_ACC    ) AS SUM_MAX_MOP_HIST_12M_NBK_TU_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_TU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_TU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_TU_OP_ACC,
    
COUNT(MAX_MOP_HIST_12M_NBK_TU_CL_ACC ) AS NUM_MAX_MOP_HIST_12M_NBK_TU_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_TU_CL_ACC   ) AS MAX_MAX_MOP_HIST_12M_NBK_TU_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_TU_CL_ACC   ) AS SUM_MAX_MOP_HIST_12M_NBK_TU_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_TU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_TU_CL_ACC),0)  AS AVG_MAX_MOP_HIST_12M_NBK_TU_CL_ACC 	       

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_2
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_MAX_MOP_HIST_12M LIMIT 100;
%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_MAX_MOP_HIST_12M;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_MAX_MOP_HIST_12M
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_MAX_MOP_HIST_12M' AS

SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,

COUNT(MAX_MOP_HIST_12M_BK_AU_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_AU_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_AU_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_AU_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_AU_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_AU_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_AU_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_AU_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_AU_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_AU_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_AU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_AU_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK_AU) AS NUM_MAX_MOP_HIST_12M_BK_AU,
MAX(MAX_MOP_HIST_12M_BK_AU)   AS MAX_MAX_MOP_HIST_12M_BK_AU,
SUM(MAX_MOP_HIST_12M_BK_AU)   AS SUM_MAX_MOP_HIST_12M_BK_AU,
SUM(MAX_MOP_HIST_12M_BK_AU)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_AU),0) AS AVG_MAX_MOP_HIST_12M_BK_AU,

COUNT(MAX_MOP_HIST_12M_BK_M_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_M_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_M_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_M_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_M_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_M_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_M_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_M_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_M_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_M_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_M_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_M_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK_M) AS NUM_MAX_MOP_HIST_12M_BK_M,
MAX(MAX_MOP_HIST_12M_BK_M)   AS MAX_MAX_MOP_HIST_12M_BK_M,
SUM(MAX_MOP_HIST_12M_BK_M)   AS SUM_MAX_MOP_HIST_12M_BK_M,
SUM(MAX_MOP_HIST_12M_BK_M)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_M),0) AS AVG_MAX_MOP_HIST_12M_BK_M,

COUNT(MAX_MOP_HIST_12M_BK_PL_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_PL_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_PL_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_PL_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_PL_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_PL_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_PL_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_PL_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_PL_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_PL_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_PL_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_PL_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK_PL) AS NUM_MAX_MOP_HIST_12M_BK_PL,
MAX(MAX_MOP_HIST_12M_BK_PL)   AS MAX_MAX_MOP_HIST_12M_BK_PL,
SUM(MAX_MOP_HIST_12M_BK_PL)   AS SUM_MAX_MOP_HIST_12M_BK_PL,
SUM(MAX_MOP_HIST_12M_BK_PL)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_PL),0) AS AVG_MAX_MOP_HIST_12M_BK_PL,

COUNT(MAX_MOP_HIST_12M_BK_R_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_R_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_R_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_R_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_R_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_R_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_R_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_R_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_R_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_R_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_R_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_R_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK_R) AS NUM_MAX_MOP_HIST_12M_BK_R,
MAX(MAX_MOP_HIST_12M_BK_R)   AS MAX_MAX_MOP_HIST_12M_BK_R,
SUM(MAX_MOP_HIST_12M_BK_R)   AS SUM_MAX_MOP_HIST_12M_BK_R,
SUM(MAX_MOP_HIST_12M_BK_R)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_R),0) AS AVG_MAX_MOP_HIST_12M_BK_R,

COUNT(MAX_MOP_HIST_12M_BK_CL_ACC) AS NUM_MAX_MOP_HIST_12M_BK_CL_ACC,
MAX(MAX_MOP_HIST_12M_BK_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_CL_ACC,
SUM(MAX_MOP_HIST_12M_BK_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_CL_ACC,

COUNT(MAX_MOP_HIST_12M_BK_OP_ACC) AS NUM_MAX_MOP_HIST_12M_BK_OP_ACC,
MAX(MAX_MOP_HIST_12M_BK_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_BK_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_BK_OP_ACC,
SUM(MAX_MOP_HIST_12M_BK_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_BK_OP_ACC,

COUNT(MAX_MOP_HIST_12M_BK) AS NUM_MAX_MOP_HIST_12M_BK,
MAX(MAX_MOP_HIST_12M_BK)   AS MAX_MAX_MOP_HIST_12M_BK,
SUM(MAX_MOP_HIST_12M_BK)   AS SUM_MAX_MOP_HIST_12M_BK,
SUM(MAX_MOP_HIST_12M_BK)/NULLIF(COUNT(MAX_MOP_HIST_12M_BK),0) AS AVG_MAX_MOP_HIST_12M_BK,

COUNT(MAX_MOP_HIST_12M_NBK_AU_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_AU_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_AU_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_AU_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_AU_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_AU_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_AU_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_AU_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_AU_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_AU_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_AU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_AU_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_AU) AS NUM_MAX_MOP_HIST_12M_NBK_AU,
MAX(MAX_MOP_HIST_12M_NBK_AU)   AS MAX_MAX_MOP_HIST_12M_NBK_AU,
SUM(MAX_MOP_HIST_12M_NBK_AU)   AS SUM_MAX_MOP_HIST_12M_NBK_AU,
SUM(MAX_MOP_HIST_12M_NBK_AU)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_AU),0) AS AVG_MAX_MOP_HIST_12M_NBK_AU,

COUNT(MAX_MOP_HIST_12M_NBK_M_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_M_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_M_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_M_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_M_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_M_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_M_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_M_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_M_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_M_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_M_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_M_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_M) AS NUM_MAX_MOP_HIST_12M_NBK_M,
MAX(MAX_MOP_HIST_12M_NBK_M)   AS MAX_MAX_MOP_HIST_12M_NBK_M,
SUM(MAX_MOP_HIST_12M_NBK_M)   AS SUM_MAX_MOP_HIST_12M_NBK_M,
SUM(MAX_MOP_HIST_12M_NBK_M)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_M),0) AS AVG_MAX_MOP_HIST_12M_NBK_M,

COUNT(MAX_MOP_HIST_12M_NBK_PL_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_PL_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_PL_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_PL_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_PL_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_PL_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_PL_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_PL_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_PL_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_PL_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_PL_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_PL_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_PL) AS NUM_MAX_MOP_HIST_12M_NBK_PL,
MAX(MAX_MOP_HIST_12M_NBK_PL)   AS MAX_MAX_MOP_HIST_12M_NBK_PL,
SUM(MAX_MOP_HIST_12M_NBK_PL)   AS SUM_MAX_MOP_HIST_12M_NBK_PL,
SUM(MAX_MOP_HIST_12M_NBK_PL)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_PL),0) AS AVG_MAX_MOP_HIST_12M_NBK_PL,

COUNT(MAX_MOP_HIST_12M_NBK_R_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_R_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_R_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_R_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_R_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_R_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_R_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_R_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_R_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_R_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_R_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_R_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_R) AS NUM_MAX_MOP_HIST_12M_NBK_R,
MAX(MAX_MOP_HIST_12M_NBK_R)   AS MAX_MAX_MOP_HIST_12M_NBK_R,
SUM(MAX_MOP_HIST_12M_NBK_R)   AS SUM_MAX_MOP_HIST_12M_NBK_R,
SUM(MAX_MOP_HIST_12M_NBK_R)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_R),0) AS AVG_MAX_MOP_HIST_12M_NBK_R,

COUNT(MAX_MOP_HIST_12M_NBK_CL_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_CL_ACC,

COUNT(MAX_MOP_HIST_12M_NBK_OP_ACC) AS NUM_MAX_MOP_HIST_12M_NBK_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_NBK_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_NBK_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_OP_ACC,

COUNT(MAX_MOP_HIST_12M_NBK) AS NUM_MAX_MOP_HIST_12M_NBK,
MAX(MAX_MOP_HIST_12M_NBK)   AS MAX_MAX_MOP_HIST_12M_NBK,
SUM(MAX_MOP_HIST_12M_NBK)   AS SUM_MAX_MOP_HIST_12M_NBK,
SUM(MAX_MOP_HIST_12M_NBK)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK),0) AS AVG_MAX_MOP_HIST_12M_NBK,

COUNT(MAX_MOP_HIST_12M_AMX_CL_ACC) AS NUM_MAX_MOP_HIST_12M_AMX_CL_ACC,
MAX(MAX_MOP_HIST_12M_AMX_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_AMX_CL_ACC,
SUM(MAX_MOP_HIST_12M_AMX_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_AMX_CL_ACC,
SUM(MAX_MOP_HIST_12M_AMX_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_AMX_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_AMX_CL_ACC,

COUNT(MAX_MOP_HIST_12M_AMX_OP_ACC) AS NUM_MAX_MOP_HIST_12M_AMX_OP_ACC,
MAX(MAX_MOP_HIST_12M_AMX_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_AMX_OP_ACC,
SUM(MAX_MOP_HIST_12M_AMX_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_AMX_OP_ACC,
SUM(MAX_MOP_HIST_12M_AMX_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_AMX_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_AMX_OP_ACC,

COUNT(MAX_MOP_HIST_12M_AMX) AS NUM_MAX_MOP_HIST_12M_AMX,
MAX(MAX_MOP_HIST_12M_AMX)   AS MAX_MAX_MOP_HIST_12M_AMX,
SUM(MAX_MOP_HIST_12M_AMX)   AS SUM_MAX_MOP_HIST_12M_AMX,
SUM(MAX_MOP_HIST_12M_AMX)/NULLIF(COUNT(MAX_MOP_HIST_12M_AMX),0) AS AVG_MAX_MOP_HIST_12M_AMX,

COUNT(MAX_MOP_HIST_12M_AU_CL_ACC) AS NUM_MAX_MOP_HIST_12M_AU_CL_ACC,
MAX(MAX_MOP_HIST_12M_AU_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_AU_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_AU_CL_ACC,
SUM(MAX_MOP_HIST_12M_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_AU_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_AU_CL_ACC,

COUNT(MAX_MOP_HIST_12M_AU_OP_ACC) AS NUM_MAX_MOP_HIST_12M_AU_OP_ACC,
MAX(MAX_MOP_HIST_12M_AU_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_AU_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_AU_OP_ACC,
SUM(MAX_MOP_HIST_12M_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_AU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_AU_OP_ACC,

COUNT(MAX_MOP_HIST_12M_AU) AS NUM_MAX_MOP_HIST_12M_AU,
MAX(MAX_MOP_HIST_12M_AU)   AS MAX_MAX_MOP_HIST_12M_AU,
SUM(MAX_MOP_HIST_12M_AU)   AS SUM_MAX_MOP_HIST_12M_AU,
SUM(MAX_MOP_HIST_12M_AU)/NULLIF(COUNT(MAX_MOP_HIST_12M_AU),0) AS AVG_MAX_MOP_HIST_12M_AU,

COUNT(MAX_MOP_HIST_12M_M_CL_ACC) AS NUM_MAX_MOP_HIST_12M_M_CL_ACC,
MAX(MAX_MOP_HIST_12M_M_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_M_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_M_CL_ACC,
SUM(MAX_MOP_HIST_12M_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_M_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_M_CL_ACC,

COUNT(MAX_MOP_HIST_12M_M_OP_ACC) AS NUM_MAX_MOP_HIST_12M_M_OP_ACC,
MAX(MAX_MOP_HIST_12M_M_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_M_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_M_OP_ACC,
SUM(MAX_MOP_HIST_12M_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_M_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_M_OP_ACC,

COUNT(MAX_MOP_HIST_12M_M) AS NUM_MAX_MOP_HIST_12M_M,
MAX(MAX_MOP_HIST_12M_M)   AS MAX_MAX_MOP_HIST_12M_M,
SUM(MAX_MOP_HIST_12M_M)   AS SUM_MAX_MOP_HIST_12M_M,
SUM(MAX_MOP_HIST_12M_M)/NULLIF(COUNT(MAX_MOP_HIST_12M_M),0) AS AVG_MAX_MOP_HIST_12M_M,

COUNT(MAX_MOP_HIST_12M_PL_CL_ACC) AS NUM_MAX_MOP_HIST_12M_PL_CL_ACC,
MAX(MAX_MOP_HIST_12M_PL_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_PL_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_PL_CL_ACC,
SUM(MAX_MOP_HIST_12M_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_PL_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_PL_CL_ACC,

COUNT(MAX_MOP_HIST_12M_PL_OP_ACC) AS NUM_MAX_MOP_HIST_12M_PL_OP_ACC,
MAX(MAX_MOP_HIST_12M_PL_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_PL_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_PL_OP_ACC,
SUM(MAX_MOP_HIST_12M_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_PL_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_PL_OP_ACC,

COUNT(MAX_MOP_HIST_12M_PL) AS NUM_MAX_MOP_HIST_12M_PL,
MAX(MAX_MOP_HIST_12M_PL)   AS MAX_MAX_MOP_HIST_12M_PL,
SUM(MAX_MOP_HIST_12M_PL)   AS SUM_MAX_MOP_HIST_12M_PL,
SUM(MAX_MOP_HIST_12M_PL)/NULLIF(COUNT(MAX_MOP_HIST_12M_PL),0) AS AVG_MAX_MOP_HIST_12M_PL,

COUNT(MAX_MOP_HIST_12M_R_CL_ACC) AS NUM_MAX_MOP_HIST_12M_R_CL_ACC,
MAX(MAX_MOP_HIST_12M_R_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_R_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_R_CL_ACC,
SUM(MAX_MOP_HIST_12M_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_R_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_R_CL_ACC,

COUNT(MAX_MOP_HIST_12M_R_OP_ACC) AS NUM_MAX_MOP_HIST_12M_R_OP_ACC,
MAX(MAX_MOP_HIST_12M_R_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_R_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_R_OP_ACC,
SUM(MAX_MOP_HIST_12M_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_R_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_R_OP_ACC,

COUNT(MAX_MOP_HIST_12M_R) AS NUM_MAX_MOP_HIST_12M_R,
MAX(MAX_MOP_HIST_12M_R)   AS MAX_MAX_MOP_HIST_12M_R,
SUM(MAX_MOP_HIST_12M_R)   AS SUM_MAX_MOP_HIST_12M_R,
SUM(MAX_MOP_HIST_12M_R)/NULLIF(COUNT(MAX_MOP_HIST_12M_R),0) AS AVG_MAX_MOP_HIST_12M_R,

COUNT(MAX_MOP_HIST_12M_CL_ACC) AS NUM_MAX_MOP_HIST_12M_CL_ACC,
MAX(MAX_MOP_HIST_12M_CL_ACC)   AS MAX_MAX_MOP_HIST_12M_CL_ACC,
SUM(MAX_MOP_HIST_12M_CL_ACC)   AS SUM_MAX_MOP_HIST_12M_CL_ACC,
SUM(MAX_MOP_HIST_12M_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_CL_ACC,

COUNT(MAX_MOP_HIST_12M_OP_ACC) AS NUM_MAX_MOP_HIST_12M_OP_ACC,
MAX(MAX_MOP_HIST_12M_OP_ACC)   AS MAX_MAX_MOP_HIST_12M_OP_ACC,
SUM(MAX_MOP_HIST_12M_OP_ACC)   AS SUM_MAX_MOP_HIST_12M_OP_ACC,
SUM(MAX_MOP_HIST_12M_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_OP_ACC,

COUNT(MAX_MOP_HIST_12M) AS NUM_MAX_MOP_HIST_12M,
MAX(MAX_MOP_HIST_12M)   AS MAX_MAX_MOP_HIST_12M,
SUM(MAX_MOP_HIST_12M)   AS SUM_MAX_MOP_HIST_12M,
SUM(MAX_MOP_HIST_12M)/NULLIF(COUNT(MAX_MOP_HIST_12M),0) AS AVG_MAX_MOP_HIST_12M,                             

-- COMUNICACIONES Y SERVICIOS

COUNT(MAX_MOP_HIST_12M_TU_ALL ) AS NUM_MAX_MOP_HIST_12M_TU_ALL, 
MAX(MAX_MOP_HIST_12M_TU_ALL   ) AS MAX_MAX_MOP_HIST_12M_TU_ALL,
SUM(MAX_MOP_HIST_12M_TU_ALL   ) AS SUM_MAX_MOP_HIST_12M_TU_ALL,
SUM(MAX_MOP_HIST_12M_TU_ALL)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_ALL),0) AS AVG_MAX_MOP_HIST_12M_TU_ALL,
                            
COUNT(MAX_MOP_HIST_12M_TU) AS NUM_MAX_MOP_HIST_12M_TU,
MAX(MAX_MOP_HIST_12M_TU  ) AS MAX_MAX_MOP_HIST_12M_TU,
SUM(MAX_MOP_HIST_12M_TU  ) AS SUM_MAX_MOP_HIST_12M_TU,
SUM(MAX_MOP_HIST_12M_TU)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU),0) AS AVG_MAX_MOP_HIST_12M_TU,

COUNT(MAX_MOP_HIST_12M_TU_ALL_OP_ACC ) AS NUM_MAX_MOP_HIST_12M_TU_ALL_OP_ACC,
MAX(MAX_MOP_HIST_12M_TU_ALL_OP_ACC   ) AS MAX_MAX_MOP_HIST_12M_TU_ALL_OP_ACC,
SUM(MAX_MOP_HIST_12M_TU_ALL_OP_ACC   ) AS SUM_MAX_MOP_HIST_12M_TU_ALL_OP_ACC,
SUM(MAX_MOP_HIST_12M_TU_ALL_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_ALL_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_TU_ALL_OP_ACC,
    
COUNT(MAX_MOP_HIST_12M_TU_OP_ACC ) AS NUM_MAX_MOP_HIST_12M_TU_OP_ACC,
MAX(MAX_MOP_HIST_12M_TU_OP_ACC   ) AS MAX_MAX_MOP_HIST_12M_TU_OP_ACC,
SUM(MAX_MOP_HIST_12M_TU_OP_ACC   ) AS SUM_MAX_MOP_HIST_12M_TU_OP_ACC,
SUM(MAX_MOP_HIST_12M_TU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_TU_OP_ACC,
    
COUNT(MAX_MOP_HIST_12M_TU_ALL_CL_ACC ) AS NUM_MAX_MOP_HIST_12M_TU_ALL_CL_ACC,
MAX(MAX_MOP_HIST_12M_TU_ALL_CL_ACC   ) AS MAX_MAX_MOP_HIST_12M_TU_ALL_CL_ACC,
SUM(MAX_MOP_HIST_12M_TU_ALL_CL_ACC   ) AS SUM_MAX_MOP_HIST_12M_TU_ALL_CL_ACC,
SUM(MAX_MOP_HIST_12M_TU_ALL_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_ALL_CL_ACC),0)  AS AVG_MAX_MOP_HIST_12M_TU_ALL_CL_ACC,
    
COUNT(MAX_MOP_HIST_12M_TU_CL_ACC  ) AS NUM_MAX_MOP_HIST_12M_TU_CL_ACC,
MAX(MAX_MOP_HIST_12M_TU_CL_ACC    ) AS MAX_MAX_MOP_HIST_12M_TU_CL_ACC,
SUM(MAX_MOP_HIST_12M_TU_CL_ACC    ) AS SUM_MAX_MOP_HIST_12M_TU_CL_ACC,
SUM(MAX_MOP_HIST_12M_TU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_TU_CL_ACC),0) AS AVG_MAX_MOP_HIST_12M_TU_CL_ACC,
    
COUNT(MAX_MOP_HIST_12M_NBK_TU  ) AS NUM_MAX_MOP_HIST_12M_NBK_TU,
MAX(MAX_MOP_HIST_12M_NBK_TU    ) AS MAX_MAX_MOP_HIST_12M_NBK_TU,
SUM(MAX_MOP_HIST_12M_NBK_TU    ) AS SUM_MAX_MOP_HIST_12M_NBK_TU,
SUM(MAX_MOP_HIST_12M_NBK_TU)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_TU),0)  AS AVG_MAX_MOP_HIST_12M_NBK_TU,
    
COUNT(MAX_MOP_HIST_12M_NBK_TU_OP_ACC  ) AS NUM_MAX_MOP_HIST_12M_NBK_TU_OP_ACC,
MAX(MAX_MOP_HIST_12M_NBK_TU_OP_ACC    ) AS MAX_MAX_MOP_HIST_12M_NBK_TU_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_TU_OP_ACC    ) AS SUM_MAX_MOP_HIST_12M_NBK_TU_OP_ACC,
SUM(MAX_MOP_HIST_12M_NBK_TU_OP_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_TU_OP_ACC),0) AS AVG_MAX_MOP_HIST_12M_NBK_TU_OP_ACC,
    
COUNT(MAX_MOP_HIST_12M_NBK_TU_CL_ACC ) AS NUM_MAX_MOP_HIST_12M_NBK_TU_CL_ACC,
MAX(MAX_MOP_HIST_12M_NBK_TU_CL_ACC   ) AS MAX_MAX_MOP_HIST_12M_NBK_TU_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_TU_CL_ACC   ) AS SUM_MAX_MOP_HIST_12M_NBK_TU_CL_ACC,
SUM(MAX_MOP_HIST_12M_NBK_TU_CL_ACC)/NULLIF(COUNT(MAX_MOP_HIST_12M_NBK_TU_CL_ACC),0)  AS AVG_MAX_MOP_HIST_12M_NBK_TU_CL_ACC 	       

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_2
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_MAX_MOP_HIST_12M LIMIT 100;
