%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_R_MOP_BAL_BY_CRED_MAX;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_R_MOP_BAL_BY_CRED_MAX
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_R_MOP_BAL_BY_CRED_MAX' AS

SELECT
CUENTADEREFERENCIA,FECHA_CARTERA,

-- NUM
COUNT(R_MOP_BAL_BY_CRED_MAX_BK_AU)   AS NUM_R_MOP_BAL_BY_CRED_MAX_BK_AU  ,
COUNT(R_MOP_BAL_BY_CRED_MAX_BK_M)    AS NUM_R_MOP_BAL_BY_CRED_MAX_BK_M   ,
COUNT(R_MOP_BAL_BY_CRED_MAX_BK_PL)   AS NUM_R_MOP_BAL_BY_CRED_MAX_BK_PL  ,
COUNT(R_MOP_BAL_BY_CRED_MAX_BK_R)    AS NUM_R_MOP_BAL_BY_CRED_MAX_BK_R   ,  
COUNT(R_MOP_BAL_BY_CRED_MAX_BK)      AS NUM_R_MOP_BAL_BY_CRED_MAX_BK     ,    
COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_AU)  AS NUM_R_MOP_BAL_BY_CRED_MAX_NBK_AU ,
COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_M)   AS NUM_R_MOP_BAL_BY_CRED_MAX_NBK_M  , 
COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_PL)  AS NUM_R_MOP_BAL_BY_CRED_MAX_NBK_PL ,
COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_R)   AS NUM_R_MOP_BAL_BY_CRED_MAX_NBK_R  , 
COUNT(R_MOP_BAL_BY_CRED_MAX_NBK)     AS NUM_R_MOP_BAL_BY_CRED_MAX_NBK    ,   
COUNT(R_MOP_BAL_BY_CRED_MAX_AMX)     AS NUM_R_MOP_BAL_BY_CRED_MAX_AMX    ,   
COUNT(R_MOP_BAL_BY_CRED_MAX_AU)      AS NUM_R_MOP_BAL_BY_CRED_MAX_AU     ,    
COUNT(R_MOP_BAL_BY_CRED_MAX_M)       AS NUM_R_MOP_BAL_BY_CRED_MAX_M      ,     
COUNT(R_MOP_BAL_BY_CRED_MAX_PL)      AS NUM_R_MOP_BAL_BY_CRED_MAX_PL     ,    
COUNT(R_MOP_BAL_BY_CRED_MAX_R)       AS NUM_R_MOP_BAL_BY_CRED_MAX_R      ,     
COUNT(R_MOP_BAL_BY_CRED_MAX)         AS NUM_R_MOP_BAL_BY_CRED_MAX        ,       
COUNT(R_MOP_BAL_BY_CRED_MAX_TU)      AS NUM_R_MOP_BAL_BY_CRED_MAX_TU     ,    
COUNT(R_MOP_BAL_BY_CRED_MAX_TU_ALL)  AS NUM_R_MOP_BAL_BY_CRED_MAX_TU_ALL ,
COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_TU)  AS NUM_R_MOP_BAL_BY_CRED_MAX_NBK_TU ,
                                                                        
-- MAX
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_BK_AU)  , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_BK_AU  ,
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_BK_M)   , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_BK_M   ,
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_BK_PL)  , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_BK_PL  ,
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_BK_R)   , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_BK_R   , 
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_BK)     , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_BK     ,    
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_NBK_AU) , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_NBK_AU ,
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_NBK_M)  , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_NBK_M  , 
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_NBK_PL) , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_NBK_PL ,
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_NBK_R)  , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_NBK_R  , 
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_NBK)    , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_NBK    ,   
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_AMX)    , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_AMX    ,   
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_AU)     , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_AU     ,        
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_M)      , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_M      ,              
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_PL)     , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_PL     ,        
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_R)      , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_R      ,          
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX)        , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX        ,            
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_TU)     , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_TU     ,    
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_TU_ALL) , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_TU_ALL ,
ROUND(MAX(R_MOP_BAL_BY_CRED_MAX_NBK_TU) , 4) AS MAX_R_MOP_BAL_BY_CRED_MAX_NBK_TU ,
                                                                      
-- SUM
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK_AU) , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_BK_AU ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK_M)  , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_BK_M  , 
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK_PL) , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_BK_PL ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK_R)  , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_BK_R  , 
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK)    , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_BK    ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_AU), 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_NBK_AU,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_M) , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_NBK_M ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_PL), 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_NBK_PL,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_R) , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_NBK_R ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK)   , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_NBK   ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_AMX)   , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_AMX   ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_AU)    , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_AU    ,   
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_M)     , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_M     ,        
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_PL)    , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_PL    ,   
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_R)     , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_R     ,    
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX)       , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX       ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_TU)    , 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_TU    ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_TU_ALL), 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_TU_ALL,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_TU), 4) AS SUM_R_MOP_BAL_BY_CRED_MAX_NBK_TU,

-- AVG   
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK_AU)  /COUNT(R_MOP_BAL_BY_CRED_MAX_BK_AU)  , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_BK_AU ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK_M)   /COUNT(R_MOP_BAL_BY_CRED_MAX_BK_M)   , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_BK_M  ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK_PL)  /COUNT(R_MOP_BAL_BY_CRED_MAX_BK_PL)  , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_BK_PL ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK_R)   /COUNT(R_MOP_BAL_BY_CRED_MAX_BK_R)   , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_BK_R  ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_BK)     /COUNT(R_MOP_BAL_BY_CRED_MAX_BK)     , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_BK    ,  
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_AU) /COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_AU) , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_NBK_AU,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_M)  /COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_M)  , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_NBK_M ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_PL) /COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_PL) , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_NBK_PL,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_R)  /COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_R)  , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_NBK_R ,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK)    /COUNT(R_MOP_BAL_BY_CRED_MAX_NBK)    , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_NBK   , 
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_AMX)    /COUNT(R_MOP_BAL_BY_CRED_MAX_AMX)    , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_AMX   , 
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_AU)     /COUNT(R_MOP_BAL_BY_CRED_MAX_AU)     , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_AU    ,    
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_M)      /COUNT(R_MOP_BAL_BY_CRED_MAX_M)      , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_M     ,     
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_PL)     /COUNT(R_MOP_BAL_BY_CRED_MAX_PL)     , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_PL    ,  
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_R)      /COUNT(R_MOP_BAL_BY_CRED_MAX_R)      , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_R     ,  
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX)        /COUNT(R_MOP_BAL_BY_CRED_MAX)        , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX       ,                                                                                                                                  
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_TU)     /COUNT(R_MOP_BAL_BY_CRED_MAX_TU)     , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_TU    ,   
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_TU_ALL) /COUNT(R_MOP_BAL_BY_CRED_MAX_TU_ALL) , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_TU_ALL,
ROUND(SUM(R_MOP_BAL_BY_CRED_MAX_NBK_TU) /COUNT(R_MOP_BAL_BY_CRED_MAX_NBK_TU) , 4)  AS AVG_R_MOP_BAL_BY_CRED_MAX_NBK_TU 
                                                                                                                       
FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_R_MOP_BAL_BY_CRED_MAX LIMIT 100;