%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_D_MS_LST_BUY_TO_MS_LST_PAY;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_D_MS_LST_BUY_TO_MS_LST_PAY
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_D_MS_LST_BUY_TO_MS_LST_PAY' AS

SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,

COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC ) AS NUM_D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC  , 
COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  ) AS NUM_D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC   ,
COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   ) AS NUM_D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC    ,
COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC) AS NUM_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC ,
COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  ) AS NUM_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC   ,
COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    ) AS NUM_D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC     ,
COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      ) AS NUM_D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC       ,

MIN(D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC ) AS   MIN_D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC  , 
MIN(D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  ) AS   MIN_D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC   ,
MIN(D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   ) AS   MIN_D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC    ,
MIN(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC) AS   MIN_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC ,
MIN(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  ) AS   MIN_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC   ,
MIN(D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    ) AS   MIN_D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC     ,
MIN(D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      ) AS   MIN_D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC       ,
                                       
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC )AS    MAX_D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC , 
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  )AS    MAX_D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   )AS    MAX_D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC)AS    MAX_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  )AS    MAX_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    )AS    MAX_D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      )AS    MAX_D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      ,
                                       
SUM(D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC )AS    SUM_D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC , 
SUM(D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  )AS    SUM_D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  ,
SUM(D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   )AS    SUM_D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   ,
SUM(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC)AS    SUM_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC,
SUM(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  )AS    SUM_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  ,
SUM(D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    )AS    SUM_D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    ,
SUM(D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      )AS    SUM_D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      ,

MAX(D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC )- MIN(D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC ) AS DIF_D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  )- MIN(D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  ) AS DIF_D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   )- MIN(D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   ) AS DIF_D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC)- MIN(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC) AS DIF_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  )- MIN(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  ) AS DIF_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    )- MIN(D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    ) AS DIF_D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    ,
MAX(D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      )- MIN(D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      ) AS DIF_D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      ,

ROUND( SUM(D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC )  / COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC ) ,2) AS AVG_D_MS_LST_BUY_TO_MS_LST_PAY_BK_R_OP_ACC  ,
ROUND( SUM(D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  )  / COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC  ) ,2) AS AVG_D_MS_LST_BUY_TO_MS_LST_PAY_AMX_OP_ACC   ,
ROUND( SUM(D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   )  / COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC   ) ,2) AS AVG_D_MS_LST_BUY_TO_MS_LST_PAY_BK_OP_ACC    ,
ROUND( SUM(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC)  / COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC) ,2) AS AVG_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_R_OP_ACC ,
ROUND( SUM(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  )  / COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC  ) ,2) AS AVG_D_MS_LST_BUY_TO_MS_LST_PAY_NBK_OP_ACC   ,
ROUND( SUM(D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    )  / COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC    ) ,2) AS AVG_D_MS_LST_BUY_TO_MS_LST_PAY_R_OP_ACC     ,
ROUND( SUM(D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      )  / COUNT(D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC      ) ,2) AS AVG_D_MS_LST_BUY_TO_MS_LST_PAY_OP_ACC       

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_D_MS_LST_BUY_TO_MS_LST_PAY LIMIT 100;