%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_MAX_MOP_BAL;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_MAX_MOP_BAL
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_MAX_MOP_BAL' AS

SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,

COUNT(MAX_MOP_BAL_BK_AU_CL_ACC) AS NUM_MAX_MOP_BAL_BK_AU_CL_ACC,
MAX(MAX_MOP_BAL_BK_AU_CL_ACC)   AS MAX_MAX_MOP_BAL_BK_AU_CL_ACC,
SUM(MAX_MOP_BAL_BK_AU_CL_ACC)   AS SUM_MAX_MOP_BAL_BK_AU_CL_ACC,
SUM(MAX_MOP_BAL_BK_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_AU_CL_ACC),0) AS AVG_MAX_MOP_BAL_BK_AU_CL_ACC,

COUNT(MAX_MOP_BAL_BK_AU_OP_ACC) AS NUM_MAX_MOP_BAL_BK_AU_OP_ACC,
MAX(MAX_MOP_BAL_BK_AU_OP_ACC)   AS MAX_MAX_MOP_BAL_BK_AU_OP_ACC,
SUM(MAX_MOP_BAL_BK_AU_OP_ACC)   AS SUM_MAX_MOP_BAL_BK_AU_OP_ACC,
SUM(MAX_MOP_BAL_BK_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_AU_OP_ACC),0) AS AVG_MAX_MOP_BAL_BK_AU_OP_ACC,

COUNT(MAX_MOP_BAL_BK_AU)  AS NUM_MAX_MOP_BAL_BK_AU,
MAX(MAX_MOP_BAL_BK_AU)    AS MAX_MAX_MOP_BAL_BK_AU,
SUM(MAX_MOP_BAL_BK_AU)    AS SUM_MAX_MOP_BAL_BK_AU,
SUM(MAX_MOP_BAL_BK_AU)/NULLIF(COUNT(MAX_MOP_BAL_BK_AU),0) AS AVG_MAX_MOP_BAL_BK_AU,

COUNT(MAX_MOP_BAL_BK_M_CL_ACC) AS NUM_MAX_MOP_BAL_BK_M_CL_ACC,
MAX(MAX_MOP_BAL_BK_M_CL_ACC)   AS MAX_MAX_MOP_BAL_BK_M_CL_ACC,
SUM(MAX_MOP_BAL_BK_M_CL_ACC)   AS SUM_MAX_MOP_BAL_BK_M_CL_ACC,
SUM(MAX_MOP_BAL_BK_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_M_CL_ACC),0) AS AVG_MAX_MOP_BAL_BK_M_CL_ACC,

COUNT(MAX_MOP_BAL_BK_M_OP_ACC) AS NUM_MAX_MOP_BAL_BK_M_OP_ACC,
MAX(MAX_MOP_BAL_BK_M_OP_ACC)   AS MAX_MAX_MOP_BAL_BK_M_OP_ACC,
SUM(MAX_MOP_BAL_BK_M_OP_ACC)   AS SUM_MAX_MOP_BAL_BK_M_OP_ACC,
SUM(MAX_MOP_BAL_BK_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_M_OP_ACC),0) AS AVG_MAX_MOP_BAL_BK_M_OP_ACC,

COUNT(MAX_MOP_BAL_BK_M) AS NUM_MAX_MOP_BAL_BK_M,
MAX(MAX_MOP_BAL_BK_M)   AS MAX_MAX_MOP_BAL_BK_M,
SUM(MAX_MOP_BAL_BK_M)   AS SUM_MAX_MOP_BAL_BK_M,
SUM(MAX_MOP_BAL_BK_M)/NULLIF(COUNT(MAX_MOP_BAL_BK_M),0) AS AVG_MAX_MOP_BAL_BK_M,

COUNT(MAX_MOP_BAL_BK_PL_CL_ACC) AS NUM_MAX_MOP_BAL_BK_PL_CL_ACC,
MAX(MAX_MOP_BAL_BK_PL_CL_ACC)   AS MAX_MAX_MOP_BAL_BK_PL_CL_ACC,
SUM(MAX_MOP_BAL_BK_PL_CL_ACC)   AS SUM_MAX_MOP_BAL_BK_PL_CL_ACC,
SUM(MAX_MOP_BAL_BK_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_PL_CL_ACC),0) AS AVG_MAX_MOP_BAL_BK_PL_CL_ACC,

COUNT(MAX_MOP_BAL_BK_PL_OP_ACC) AS NUM_MAX_MOP_BAL_BK_PL_OP_ACC,
MAX(MAX_MOP_BAL_BK_PL_OP_ACC)   AS MAX_MAX_MOP_BAL_BK_PL_OP_ACC,
SUM(MAX_MOP_BAL_BK_PL_OP_ACC)   AS SUM_MAX_MOP_BAL_BK_PL_OP_ACC,
SUM(MAX_MOP_BAL_BK_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_PL_OP_ACC),0) AS AVG_MAX_MOP_BAL_BK_PL_OP_ACC,

COUNT(MAX_MOP_BAL_BK_PL) AS NUM_MAX_MOP_BAL_BK_PL,
MAX(MAX_MOP_BAL_BK_PL)   AS MAX_MAX_MOP_BAL_BK_PL,
SUM(MAX_MOP_BAL_BK_PL)   AS SUM_MAX_MOP_BAL_BK_PL,
SUM(MAX_MOP_BAL_BK_PL)/NULLIF(COUNT(MAX_MOP_BAL_BK_PL),0) AS AVG_MAX_MOP_BAL_BK_PL,

COUNT(MAX_MOP_BAL_BK_R_CL_ACC) AS NUM_MAX_MOP_BAL_BK_R_CL_ACC,
MAX(MAX_MOP_BAL_BK_R_CL_ACC)   AS MAX_MAX_MOP_BAL_BK_R_CL_ACC,
SUM(MAX_MOP_BAL_BK_R_CL_ACC)   AS SUM_MAX_MOP_BAL_BK_R_CL_ACC,
SUM(MAX_MOP_BAL_BK_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_R_CL_ACC),0) AS AVG_MAX_MOP_BAL_BK_R_CL_ACC,

COUNT(MAX_MOP_BAL_BK_R_OP_ACC) AS NUM_MAX_MOP_BAL_BK_R_OP_ACC,
MAX(MAX_MOP_BAL_BK_R_OP_ACC)   AS MAX_MAX_MOP_BAL_BK_R_OP_ACC,
SUM(MAX_MOP_BAL_BK_R_OP_ACC)   AS SUM_MAX_MOP_BAL_BK_R_OP_ACC,
SUM(MAX_MOP_BAL_BK_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_R_OP_ACC),0) AS AVG_MAX_MOP_BAL_BK_R_OP_ACC,

COUNT(MAX_MOP_BAL_BK_R) AS NUM_MAX_MOP_BAL_BK_R,
MAX(MAX_MOP_BAL_BK_R)   AS MAX_MAX_MOP_BAL_BK_R,
SUM(MAX_MOP_BAL_BK_R)   AS SUM_MAX_MOP_BAL_BK_R,
SUM(MAX_MOP_BAL_BK_R)/NULLIF(COUNT(MAX_MOP_BAL_BK_R),0) AS AVG_MAX_MOP_BAL_BK_R,

COUNT(MAX_MOP_BAL_BK_CL_ACC) AS NUM_MAX_MOP_BAL_BK_CL_ACC,
MAX(MAX_MOP_BAL_BK_CL_ACC)   AS MAX_MAX_MOP_BAL_BK_CL_ACC,
SUM(MAX_MOP_BAL_BK_CL_ACC)   AS SUM_MAX_MOP_BAL_BK_CL_ACC,
SUM(MAX_MOP_BAL_BK_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_CL_ACC),0) AS AVG_MAX_MOP_BAL_BK_CL_ACC,

COUNT(MAX_MOP_BAL_BK_OP_ACC) AS NUM_MAX_MOP_BAL_BK_OP_ACC,
MAX(MAX_MOP_BAL_BK_OP_ACC)   AS MAX_MAX_MOP_BAL_BK_OP_ACC,
SUM(MAX_MOP_BAL_BK_OP_ACC)   AS SUM_MAX_MOP_BAL_BK_OP_ACC,
SUM(MAX_MOP_BAL_BK_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_BK_OP_ACC),0) AS AVG_MAX_MOP_BAL_BK_OP_ACC,

COUNT(MAX_MOP_BAL_BK) AS NUM_MAX_MOP_BAL_BK,
MAX(MAX_MOP_BAL_BK)   AS MAX_MAX_MOP_BAL_BK,
SUM(MAX_MOP_BAL_BK)   AS SUM_MAX_MOP_BAL_BK,
SUM(MAX_MOP_BAL_BK)/NULLIF(COUNT(MAX_MOP_BAL_BK),0) AS AVG_MAX_MOP_BAL_BK,

COUNT(MAX_MOP_BAL_NBK_AU_CL_ACC) AS NUM_MAX_MOP_BAL_NBK_AU_CL_ACC,
MAX(MAX_MOP_BAL_NBK_AU_CL_ACC)   AS MAX_MAX_MOP_BAL_NBK_AU_CL_ACC,
SUM(MAX_MOP_BAL_NBK_AU_CL_ACC)   AS SUM_MAX_MOP_BAL_NBK_AU_CL_ACC,
SUM(MAX_MOP_BAL_NBK_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_AU_CL_ACC),0) AS AVG_MAX_MOP_BAL_NBK_AU_CL_ACC,

COUNT(MAX_MOP_BAL_NBK_AU_OP_ACC) AS NUM_MAX_MOP_BAL_NBK_AU_OP_ACC,
MAX(MAX_MOP_BAL_NBK_AU_OP_ACC)   AS MAX_MAX_MOP_BAL_NBK_AU_OP_ACC,
SUM(MAX_MOP_BAL_NBK_AU_OP_ACC)   AS SUM_MAX_MOP_BAL_NBK_AU_OP_ACC,
SUM(MAX_MOP_BAL_NBK_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_AU_OP_ACC),0) AS AVG_MAX_MOP_BAL_NBK_AU_OP_ACC,

COUNT(MAX_MOP_BAL_NBK_AU) AS NUM_MAX_MOP_BAL_NBK_AU,
MAX(MAX_MOP_BAL_NBK_AU)   AS MAX_MAX_MOP_BAL_NBK_AU,
SUM(MAX_MOP_BAL_NBK_AU)   AS SUM_MAX_MOP_BAL_NBK_AU,
SUM(MAX_MOP_BAL_NBK_AU)/NULLIF(COUNT(MAX_MOP_BAL_NBK_AU),0) AS AVG_MAX_MOP_BAL_NBK_AU,

COUNT(MAX_MOP_BAL_NBK_M_CL_ACC) AS NUM_MAX_MOP_BAL_NBK_M_CL_ACC,
MAX(MAX_MOP_BAL_NBK_M_CL_ACC)   AS MAX_MAX_MOP_BAL_NBK_M_CL_ACC,
SUM(MAX_MOP_BAL_NBK_M_CL_ACC)   AS SUM_MAX_MOP_BAL_NBK_M_CL_ACC,
SUM(MAX_MOP_BAL_NBK_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_M_CL_ACC),0) AS AVG_MAX_MOP_BAL_NBK_M_CL_ACC,

COUNT(MAX_MOP_BAL_NBK_M_OP_ACC) AS NUM_MAX_MOP_BAL_NBK_M_OP_ACC,
MAX(MAX_MOP_BAL_NBK_M_OP_ACC)   AS MAX_MAX_MOP_BAL_NBK_M_OP_ACC,
SUM(MAX_MOP_BAL_NBK_M_OP_ACC)   AS SUM_MAX_MOP_BAL_NBK_M_OP_ACC,
SUM(MAX_MOP_BAL_NBK_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_M_OP_ACC),0) AS AVG_MAX_MOP_BAL_NBK_M_OP_ACC,

COUNT(MAX_MOP_BAL_NBK_M) AS NUM_MAX_MOP_BAL_NBK_M,
MAX(MAX_MOP_BAL_NBK_M)   AS MAX_MAX_MOP_BAL_NBK_M,
SUM(MAX_MOP_BAL_NBK_M)   AS SUM_MAX_MOP_BAL_NBK_M,
SUM(MAX_MOP_BAL_NBK_M)/NULLIF(COUNT(MAX_MOP_BAL_NBK_M),0) AS AVG_MAX_MOP_BAL_NBK_M,

COUNT(MAX_MOP_BAL_NBK_PL_CL_ACC) AS NUM_MAX_MOP_BAL_NBK_PL_CL_ACC,
MAX(MAX_MOP_BAL_NBK_PL_CL_ACC)   AS MAX_MAX_MOP_BAL_NBK_PL_CL_ACC,
SUM(MAX_MOP_BAL_NBK_PL_CL_ACC)   AS SUM_MAX_MOP_BAL_NBK_PL_CL_ACC,
SUM(MAX_MOP_BAL_NBK_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_PL_CL_ACC),0) AS AVG_MAX_MOP_BAL_NBK_PL_CL_ACC,

COUNT(MAX_MOP_BAL_NBK_PL_OP_ACC) AS NUM_MAX_MOP_BAL_NBK_PL_OP_ACC,
MAX(MAX_MOP_BAL_NBK_PL_OP_ACC)   AS MAX_MAX_MOP_BAL_NBK_PL_OP_ACC,
SUM(MAX_MOP_BAL_NBK_PL_OP_ACC)   AS SUM_MAX_MOP_BAL_NBK_PL_OP_ACC,
SUM(MAX_MOP_BAL_NBK_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_PL_OP_ACC),0) AS AVG_MAX_MOP_BAL_NBK_PL_OP_ACC,

COUNT(MAX_MOP_BAL_NBK_PL) AS NUM_MAX_MOP_BAL_NBK_PL,
MAX(MAX_MOP_BAL_NBK_PL)   AS MAX_MAX_MOP_BAL_NBK_PL,
SUM(MAX_MOP_BAL_NBK_PL)   AS SUM_MAX_MOP_BAL_NBK_PL,
SUM(MAX_MOP_BAL_NBK_PL)/NULLIF(COUNT(MAX_MOP_BAL_NBK_PL),0) AS AVG_MAX_MOP_BAL_NBK_PL,

COUNT(MAX_MOP_BAL_NBK_R_CL_ACC) AS NUM_MAX_MOP_BAL_NBK_R_CL_ACC,
MAX(MAX_MOP_BAL_NBK_R_CL_ACC)   AS MAX_MAX_MOP_BAL_NBK_R_CL_ACC,
SUM(MAX_MOP_BAL_NBK_R_CL_ACC)   AS SUM_MAX_MOP_BAL_NBK_R_CL_ACC,
SUM(MAX_MOP_BAL_NBK_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_R_CL_ACC),0) AS AVG_MAX_MOP_BAL_NBK_R_CL_ACC,

COUNT(MAX_MOP_BAL_NBK_R_OP_ACC) AS NUM_MAX_MOP_BAL_NBK_R_OP_ACC,
MAX(MAX_MOP_BAL_NBK_R_OP_ACC)   AS MAX_MAX_MOP_BAL_NBK_R_OP_ACC,
SUM(MAX_MOP_BAL_NBK_R_OP_ACC)   AS SUM_MAX_MOP_BAL_NBK_R_OP_ACC,
SUM(MAX_MOP_BAL_NBK_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_R_OP_ACC),0) AS AVG_MAX_MOP_BAL_NBK_R_OP_ACC,

COUNT(MAX_MOP_BAL_NBK_R) AS NUM_MAX_MOP_BAL_NBK_R,
MAX(MAX_MOP_BAL_NBK_R)   AS MAX_MAX_MOP_BAL_NBK_R,
SUM(MAX_MOP_BAL_NBK_R)   AS SUM_MAX_MOP_BAL_NBK_R,
SUM(MAX_MOP_BAL_NBK_R)/NULLIF(COUNT(MAX_MOP_BAL_NBK_R),0) AS AVG_MAX_MOP_BAL_NBK_R,

COUNT(MAX_MOP_BAL_NBK_CL_ACC) AS NUM_MAX_MOP_BAL_NBK_CL_ACC,
MAX(MAX_MOP_BAL_NBK_CL_ACC)   AS MAX_MAX_MOP_BAL_NBK_CL_ACC,
SUM(MAX_MOP_BAL_NBK_CL_ACC)   AS SUM_MAX_MOP_BAL_NBK_CL_ACC,
SUM(MAX_MOP_BAL_NBK_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_CL_ACC),0) AS AVG_MAX_MOP_BAL_NBK_CL_ACC,

COUNT(MAX_MOP_BAL_NBK_OP_ACC) AS NUM_MAX_MOP_BAL_NBK_OP_ACC,
MAX(MAX_MOP_BAL_NBK_OP_ACC)   AS MAX_MAX_MOP_BAL_NBK_OP_ACC,
SUM(MAX_MOP_BAL_NBK_OP_ACC)   AS SUM_MAX_MOP_BAL_NBK_OP_ACC,
SUM(MAX_MOP_BAL_NBK_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_OP_ACC),0) AS AVG_MAX_MOP_BAL_NBK_OP_ACC,

COUNT(MAX_MOP_BAL_NBK) AS NUM_MAX_MOP_BAL_NBK,
MAX(MAX_MOP_BAL_NBK)   AS MAX_MAX_MOP_BAL_NBK,
SUM(MAX_MOP_BAL_NBK)   AS SUM_MAX_MOP_BAL_NBK,
SUM(MAX_MOP_BAL_NBK)/NULLIF(COUNT(MAX_MOP_BAL_NBK),0) AS AVG_MAX_MOP_BAL_NBK,

COUNT(MAX_MOP_BAL_AMX_CL_ACC) AS NUM_MAX_MOP_BAL_AMX_CL_ACC,
MAX(MAX_MOP_BAL_AMX_CL_ACC)   AS MAX_MAX_MOP_BAL_AMX_CL_ACC,
SUM(MAX_MOP_BAL_AMX_CL_ACC)   AS SUM_MAX_MOP_BAL_AMX_CL_ACC,
SUM(MAX_MOP_BAL_AMX_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_AMX_CL_ACC),0) AS AVG_MAX_MOP_BAL_AMX_CL_ACC,

COUNT(MAX_MOP_BAL_AMX_OP_ACC) AS NUM_MAX_MOP_BAL_AMX_OP_ACC,
MAX(MAX_MOP_BAL_AMX_OP_ACC)   AS MAX_MAX_MOP_BAL_AMX_OP_ACC,
SUM(MAX_MOP_BAL_AMX_OP_ACC)   AS SUM_MAX_MOP_BAL_AMX_OP_ACC,
SUM(MAX_MOP_BAL_AMX_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_AMX_OP_ACC),0) AS AVG_MAX_MOP_BAL_AMX_OP_ACC,

COUNT(MAX_MOP_BAL_AMX) AS NUM_MAX_MOP_BAL_AMX,
MAX(MAX_MOP_BAL_AMX)   AS MAX_MAX_MOP_BAL_AMX,
SUM(MAX_MOP_BAL_AMX)   AS SUM_MAX_MOP_BAL_AMX,
SUM(MAX_MOP_BAL_AMX)/NULLIF(COUNT(MAX_MOP_BAL_AMX),0) AS AVG_MAX_MOP_BAL_AMX,

COUNT(MAX_MOP_BAL_AU_CL_ACC) AS NUM_MAX_MOP_BAL_AU_CL_ACC,
MAX(MAX_MOP_BAL_AU_CL_ACC)   AS MAX_MAX_MOP_BAL_AU_CL_ACC,
SUM(MAX_MOP_BAL_AU_CL_ACC)   AS SUM_MAX_MOP_BAL_AU_CL_ACC,
SUM(MAX_MOP_BAL_AU_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_AU_CL_ACC),0) AS AVG_MAX_MOP_BAL_AU_CL_ACC,

COUNT(MAX_MOP_BAL_AU_OP_ACC) AS NUM_MAX_MOP_BAL_AU_OP_ACC,
MAX(MAX_MOP_BAL_AU_OP_ACC)   AS MAX_MAX_MOP_BAL_AU_OP_ACC,
SUM(MAX_MOP_BAL_AU_OP_ACC)   AS SUM_MAX_MOP_BAL_AU_OP_ACC,
SUM(MAX_MOP_BAL_AU_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_AU_OP_ACC),0) AS AVG_MAX_MOP_BAL_AU_OP_ACC,

COUNT(MAX_MOP_BAL_AU) AS NUM_MAX_MOP_BAL_AU,
MAX(MAX_MOP_BAL_AU)   AS MAX_MAX_MOP_BAL_AU,
SUM(MAX_MOP_BAL_AU)   AS SUM_MAX_MOP_BAL_AU,
SUM(MAX_MOP_BAL_AU)/NULLIF(COUNT(MAX_MOP_BAL_AU),0) AS AVG_MAX_MOP_BAL_AU,

COUNT(MAX_MOP_BAL_M_CL_ACC) AS NUM_MAX_MOP_BAL_M_CL_ACC,
MAX(MAX_MOP_BAL_M_CL_ACC)   AS MAX_MAX_MOP_BAL_M_CL_ACC,
SUM(MAX_MOP_BAL_M_CL_ACC)   AS SUM_MAX_MOP_BAL_M_CL_ACC,
SUM(MAX_MOP_BAL_M_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_M_CL_ACC),0) AS AVG_MAX_MOP_BAL_M_CL_ACC,

COUNT(MAX_MOP_BAL_M_OP_ACC) AS NUM_MAX_MOP_BAL_M_OP_ACC,
MAX(MAX_MOP_BAL_M_OP_ACC)   AS MAX_MAX_MOP_BAL_M_OP_ACC,
SUM(MAX_MOP_BAL_M_OP_ACC)   AS SUM_MAX_MOP_BAL_M_OP_ACC,
SUM(MAX_MOP_BAL_M_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_M_OP_ACC),0) AS AVG_MAX_MOP_BAL_M_OP_ACC,

COUNT(MAX_MOP_BAL_M) AS NUM_MAX_MOP_BAL_M,
MAX(MAX_MOP_BAL_M)   AS MAX_MAX_MOP_BAL_M,
SUM(MAX_MOP_BAL_M)   AS SUM_MAX_MOP_BAL_M,
SUM(MAX_MOP_BAL_M)/NULLIF(COUNT(MAX_MOP_BAL_M),0) AS AVG_MAX_MOP_BAL_M,

COUNT(MAX_MOP_BAL_PL_CL_ACC) AS NUM_MAX_MOP_BAL_PL_CL_ACC,
MAX(MAX_MOP_BAL_PL_CL_ACC)   AS MAX_MAX_MOP_BAL_PL_CL_ACC,
SUM(MAX_MOP_BAL_PL_CL_ACC)   AS SUM_MAX_MOP_BAL_PL_CL_ACC,
SUM(MAX_MOP_BAL_PL_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_PL_CL_ACC),0) AS AVG_MAX_MOP_BAL_PL_CL_ACC,

COUNT(MAX_MOP_BAL_PL_OP_ACC) AS NUM_MAX_MOP_BAL_PL_OP_ACC,
MAX(MAX_MOP_BAL_PL_OP_ACC)   AS MAX_MAX_MOP_BAL_PL_OP_ACC,
SUM(MAX_MOP_BAL_PL_OP_ACC)   AS SUM_MAX_MOP_BAL_PL_OP_ACC,
SUM(MAX_MOP_BAL_PL_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_PL_OP_ACC),0) AS AVG_MAX_MOP_BAL_PL_OP_ACC,

COUNT(MAX_MOP_BAL_PL) AS NUM_MAX_MOP_BAL_PL,
MAX(MAX_MOP_BAL_PL)   AS MAX_MAX_MOP_BAL_PL,
SUM(MAX_MOP_BAL_PL)   AS SUM_MAX_MOP_BAL_PL,
SUM(MAX_MOP_BAL_PL)/NULLIF(COUNT(MAX_MOP_BAL_PL),0) AS AVG_MAX_MOP_BAL_PL,

COUNT(MAX_MOP_BAL_R_CL_ACC) AS NUM_MAX_MOP_BAL_R_CL_ACC,
MAX(MAX_MOP_BAL_R_CL_ACC)   AS MAX_MAX_MOP_BAL_R_CL_ACC,
SUM(MAX_MOP_BAL_R_CL_ACC)   AS SUM_MAX_MOP_BAL_R_CL_ACC,
SUM(MAX_MOP_BAL_R_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_R_CL_ACC),0) AS AVG_MAX_MOP_BAL_R_CL_ACC,

COUNT(MAX_MOP_BAL_R_OP_ACC) AS NUM_MAX_MOP_BAL_R_OP_ACC,
MAX(MAX_MOP_BAL_R_OP_ACC)   AS MAX_MAX_MOP_BAL_R_OP_ACC,
SUM(MAX_MOP_BAL_R_OP_ACC)   AS SUM_MAX_MOP_BAL_R_OP_ACC,
SUM(MAX_MOP_BAL_R_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_R_OP_ACC),0) AS AVG_MAX_MOP_BAL_R_OP_ACC,

COUNT(MAX_MOP_BAL_R) AS NUM_MAX_MOP_BAL_R,
MAX(MAX_MOP_BAL_R)   AS MAX_MAX_MOP_BAL_R,
SUM(MAX_MOP_BAL_R)   AS SUM_MAX_MOP_BAL_R,
SUM(MAX_MOP_BAL_R)/NULLIF(COUNT(MAX_MOP_BAL_R),0) AS AVG_MAX_MOP_BAL_R,

COUNT(MAX_MOP_BAL_CL_ACC) AS NUM_MAX_MOP_BAL_CL_ACC,
MAX(MAX_MOP_BAL_CL_ACC)   AS MAX_MAX_MOP_BAL_CL_ACC,
SUM(MAX_MOP_BAL_CL_ACC)   AS SUM_MAX_MOP_BAL_CL_ACC,
SUM(MAX_MOP_BAL_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_CL_ACC),0) AS AVG_MAX_MOP_BAL_CL_ACC,

COUNT(MAX_MOP_BAL_OP_ACC) AS NUM_MAX_MOP_BAL_OP_ACC,
MAX(MAX_MOP_BAL_OP_ACC)   AS MAX_MAX_MOP_BAL_OP_ACC,
SUM(MAX_MOP_BAL_OP_ACC)   AS SUM_MAX_MOP_BAL_OP_ACC,
SUM(MAX_MOP_BAL_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_OP_ACC),0) AS AVG_MAX_MOP_BAL_OP_ACC,

COUNT(MAX_MOP_BAL) AS NUM_MAX_MOP_BAL,
MAX(MAX_MOP_BAL)   AS MAX_MAX_MOP_BAL,
SUM(MAX_MOP_BAL)   AS SUM_MAX_MOP_BAL,
SUM(MAX_MOP_BAL)/NULLIF(COUNT(MAX_MOP_BAL),0) AS AVG_MAX_MOP_BAL,

-- COMUNICACIONES Y SERVICIOS
	
COUNT(MAX_MOP_BAL_TU_ALL ) AS NUM_MAX_MOP_BAL_TU_ALL, 
MAX(MAX_MOP_BAL_TU_ALL   ) AS MAX_MAX_MOP_BAL_TU_ALL,
SUM(MAX_MOP_BAL_TU_ALL   ) AS SUM_MAX_MOP_BAL_TU_ALL,
SUM(MAX_MOP_BAL_TU_ALL)/NULLIF(COUNT(MAX_MOP_BAL_TU_ALL),0) AS AVG_MAX_MOP_BAL_TU_ALL,
                        
COUNT(MAX_MOP_BAL_TU) AS NUM_MAX_MOP_BAL_TU,
MAX(MAX_MOP_BAL_TU  ) AS MAX_MAX_MOP_BAL_TU,
SUM(MAX_MOP_BAL_TU  ) AS SUM_MAX_MOP_BAL_TU,
SUM(MAX_MOP_BAL_TU)/NULLIF(COUNT(MAX_MOP_BAL_TU),0) AS AVG_MAX_MOP_BAL_TU,
    
COUNT(MAX_MOP_BAL_TU_ALL_OP_ACC ) AS NUM_MAX_MOP_BAL_TU_ALL_OP_ACC,
MAX(MAX_MOP_BAL_TU_ALL_OP_ACC   ) AS MAX_MAX_MOP_BAL_TU_ALL_OP_ACC,
SUM(MAX_MOP_BAL_TU_ALL_OP_ACC   ) AS SUM_MAX_MOP_BAL_TU_ALL_OP_ACC,
SUM(MAX_MOP_BAL_TU_ALL_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_TU_ALL_OP_ACC),0) AS AVG_MAX_MOP_BAL_TU_ALL_OP_ACC,
    
COUNT(MAX_MOP_BAL_TU_OP_ACC ) AS NUM_MAX_MOP_BAL_TU_OP_ACC,
MAX(MAX_MOP_BAL_TU_OP_ACC   ) AS MAX_MAX_MOP_BAL_TU_OP_ACC,
SUM(MAX_MOP_BAL_TU_OP_ACC   ) AS SUM_MAX_MOP_BAL_TU_OP_ACC,
SUM(MAX_MOP_BAL_TU_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_TU_OP_ACC),0) AS AVG_MAX_MOP_BAL_TU_OP_ACC,
    
COUNT(MAX_MOP_BAL_TU_ALL_CL_ACC ) AS NUM_MAX_MOP_BAL_TU_ALL_CL_ACC,
MAX(MAX_MOP_BAL_TU_ALL_CL_ACC   ) AS MAX_MAX_MOP_BAL_TU_ALL_CL_ACC,
SUM(MAX_MOP_BAL_TU_ALL_CL_ACC   ) AS SUM_MAX_MOP_BAL_TU_ALL_CL_ACC,
SUM(MAX_MOP_BAL_TU_ALL_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_TU_ALL_CL_ACC),0)  AS AVG_MAX_MOP_BAL_TU_ALL_CL_ACC,
    
COUNT(MAX_MOP_BAL_TU_CL_ACC  ) AS NUM_MAX_MOP_BAL_TU_CL_ACC,
MAX(MAX_MOP_BAL_TU_CL_ACC    ) AS MAX_MAX_MOP_BAL_TU_CL_ACC,
SUM(MAX_MOP_BAL_TU_CL_ACC    ) AS SUM_MAX_MOP_BAL_TU_CL_ACC,
SUM(MAX_MOP_BAL_TU_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_TU_CL_ACC),0) AS AVG_MAX_MOP_BAL_TU_CL_ACC,
    
COUNT(MAX_MOP_BAL_NBK_TU  ) AS NUM_MAX_MOP_BAL_NBK_TU,
MAX(MAX_MOP_BAL_NBK_TU    ) AS MAX_MAX_MOP_BAL_NBK_TU,
SUM(MAX_MOP_BAL_NBK_TU    ) AS SUM_MAX_MOP_BAL_NBK_TU,
SUM(MAX_MOP_BAL_NBK_TU)/NULLIF(COUNT(MAX_MOP_BAL_NBK_TU),0)  AS AVG_MAX_MOP_BAL_NBK_TU,
    
COUNT(MAX_MOP_BAL_NBK_TU_OP_ACC  ) AS NUM_MAX_MOP_BAL_NBK_TU_OP_ACC,
MAX(MAX_MOP_BAL_NBK_TU_OP_ACC    ) AS MAX_MAX_MOP_BAL_NBK_TU_OP_ACC,
SUM(MAX_MOP_BAL_NBK_TU_OP_ACC    ) AS SUM_MAX_MOP_BAL_NBK_TU_OP_ACC,
SUM(MAX_MOP_BAL_NBK_TU_OP_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_TU_OP_ACC),0) AS AVG_MAX_MOP_BAL_NBK_TU_OP_ACC,
    
COUNT(MAX_MOP_BAL_NBK_TU_CL_ACC ) AS NUM_MAX_MOP_BAL_NBK_TU_CL_ACC,
MAX(MAX_MOP_BAL_NBK_TU_CL_ACC   ) AS MAX_MAX_MOP_BAL_NBK_TU_CL_ACC,
SUM(MAX_MOP_BAL_NBK_TU_CL_ACC   ) AS SUM_MAX_MOP_BAL_NBK_TU_CL_ACC,
SUM(MAX_MOP_BAL_NBK_TU_CL_ACC)/NULLIF(COUNT(MAX_MOP_BAL_NBK_TU_CL_ACC),0)  AS AVG_MAX_MOP_BAL_NBK_TU_CL_ACC 	       

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_2
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;

SELECT * FROM dbmymwork.BTDC_LGG_VAR_MAX_MOP_BAL LIMIT 100;