%hive

DROP TABLE IF EXISTS dbmymwork.BTDC_LGG_VAR_NUM_PMT;
CREATE TABLE dbmymwork.BTDC_LGG_VAR_NUM_PMT
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'

LOCATION 's3://boi-banregio/datalake/data/InteligenciaRiesgos/M&M/BTDC/VARIABLES/BTDC_LGG_VAR_NUM_PMT' AS

SELECT
CUENTADEREFERENCIA,
FECHA_CARTERA,
COUNT(NUM_PMT_BK_AU_CL_ACC) AS NUM_NUM_PMT_BK_AU_CL_ACC,
MAX(NUM_PMT_BK_AU_CL_ACC)   AS MAX_NUM_PMT_BK_AU_CL_ACC,
SUM(NUM_PMT_BK_AU_CL_ACC)   AS SUM_NUM_PMT_BK_AU_CL_ACC,
MIN(NUM_PMT_BK_AU_CL_ACC)   AS MIN_NUM_PMT_BK_AU_CL_ACC,
SUM(NUM_PMT_BK_AU_CL_ACC)/NULLIF(COUNT(NUM_PMT_BK_AU_CL_ACC),0) AS AVG_NUM_PMT_BK_AU_CL_ACC,

COUNT(NUM_PMT_BK_AU_OP_ACC) AS NUM_NUM_PMT_BK_AU_OP_ACC,
MAX(NUM_PMT_BK_AU_OP_ACC)   AS MAX_NUM_PMT_BK_AU_OP_ACC,
SUM(NUM_PMT_BK_AU_OP_ACC)   AS SUM_NUM_PMT_BK_AU_OP_ACC,
MIN(NUM_PMT_BK_AU_OP_ACC)   AS MIN_NUM_PMT_BK_AU_OP_ACC,
SUM(NUM_PMT_BK_AU_OP_ACC)/NULLIF(COUNT(NUM_PMT_BK_AU_OP_ACC),0) AS AVG_NUM_PMT_BK_AU_OP_ACC,

COUNT(NUM_PMT_BK_AU) AS NUM_NUM_PMT_BK_AU,
MAX(NUM_PMT_BK_AU)   AS MAX_NUM_PMT_BK_AU,
SUM(NUM_PMT_BK_AU)   AS SUM_NUM_PMT_BK_AU,
MIN(NUM_PMT_BK_AU)   AS MIN_NUM_PMT_BK_AU,
SUM(NUM_PMT_BK_AU)/NULLIF(COUNT(NUM_PMT_BK_AU),0) AS AVG_NUM_PMT_BK_AU,

COUNT(NUM_PMT_BK_M_CL_ACC) AS NUM_NUM_PMT_BK_M_CL_ACC,
MAX(NUM_PMT_BK_M_CL_ACC)   AS MAX_NUM_PMT_BK_M_CL_ACC,
SUM(NUM_PMT_BK_M_CL_ACC)   AS SUM_NUM_PMT_BK_M_CL_ACC,
MIN(NUM_PMT_BK_M_CL_ACC)   AS MIN_NUM_PMT_BK_M_CL_ACC,
SUM(NUM_PMT_BK_M_CL_ACC)/NULLIF(COUNT(NUM_PMT_BK_M_CL_ACC),0) AS AVG_NUM_PMT_BK_M_CL_ACC,

COUNT(NUM_PMT_BK_M_OP_ACC) AS NUM_NUM_PMT_BK_M_OP_ACC,
MAX(NUM_PMT_BK_M_OP_ACC)   AS MAX_NUM_PMT_BK_M_OP_ACC,
SUM(NUM_PMT_BK_M_OP_ACC)   AS SUM_NUM_PMT_BK_M_OP_ACC,
MIN(NUM_PMT_BK_M_OP_ACC)   AS MIN_NUM_PMT_BK_M_OP_ACC,
SUM(NUM_PMT_BK_M_OP_ACC)/NULLIF(COUNT(NUM_PMT_BK_M_OP_ACC),0) AS AVG_NUM_PMT_BK_M_OP_ACC,

COUNT(NUM_PMT_BK_M) AS NUM_NUM_PMT_BK_M,
MAX(NUM_PMT_BK_M)   AS MAX_NUM_PMT_BK_M,
SUM(NUM_PMT_BK_M)   AS SUM_NUM_PMT_BK_M,
MIN(NUM_PMT_BK_M)   AS MIN_NUM_PMT_BK_M,
SUM(NUM_PMT_BK_M)/NULLIF(COUNT(NUM_PMT_BK_M),0) AS AVG_NUM_PMT_BK_M,

COUNT(NUM_PMT_BK_PL_CL_ACC) AS NUM_NUM_PMT_BK_PL_CL_ACC,
MAX(NUM_PMT_BK_PL_CL_ACC)   AS MAX_NUM_PMT_BK_PL_CL_ACC,
SUM(NUM_PMT_BK_PL_CL_ACC)   AS SUM_NUM_PMT_BK_PL_CL_ACC,
MIN(NUM_PMT_BK_PL_CL_ACC)   AS MIN_NUM_PMT_BK_PL_CL_ACC,
SUM(NUM_PMT_BK_PL_CL_ACC)/NULLIF(COUNT(NUM_PMT_BK_PL_CL_ACC),0) AS AVG_NUM_PMT_BK_PL_CL_ACC,

COUNT(NUM_PMT_BK_PL_OP_ACC) AS NUM_NUM_PMT_BK_PL_OP_ACC,
MAX(NUM_PMT_BK_PL_OP_ACC)   AS MAX_NUM_PMT_BK_PL_OP_ACC,
SUM(NUM_PMT_BK_PL_OP_ACC)   AS SUM_NUM_PMT_BK_PL_OP_ACC,
MIN(NUM_PMT_BK_PL_OP_ACC)   AS MIN_NUM_PMT_BK_PL_OP_ACC,
SUM(NUM_PMT_BK_PL_OP_ACC)/NULLIF(COUNT(NUM_PMT_BK_PL_OP_ACC),0) AS AVG_NUM_PMT_BK_PL_OP_ACC,

COUNT(NUM_PMT_BK_PL) AS NUM_NUM_PMT_BK_PL,
MAX(NUM_PMT_BK_PL)   AS MAX_NUM_PMT_BK_PL,
SUM(NUM_PMT_BK_PL)   AS SUM_NUM_PMT_BK_PL,
MIN(NUM_PMT_BK_PL)   AS MIN_NUM_PMT_BK_PL,
SUM(NUM_PMT_BK_PL)/NULLIF(COUNT(NUM_PMT_BK_PL),0) AS AVG_NUM_PMT_BK_PL,

COUNT(NUM_PMT_BK_CL_ACC) AS NUM_NUM_PMT_BK_CL_ACC,
MAX(NUM_PMT_BK_CL_ACC)   AS MAX_NUM_PMT_BK_CL_ACC,
SUM(NUM_PMT_BK_CL_ACC)   AS SUM_NUM_PMT_BK_CL_ACC,
MIN(NUM_PMT_BK_CL_ACC)   AS MIN_NUM_PMT_BK_CL_ACC,
SUM(NUM_PMT_BK_CL_ACC)/NULLIF(COUNT(NUM_PMT_BK_CL_ACC),0) AS AVG_NUM_PMT_BK_CL_ACC,

COUNT(NUM_PMT_BK_OP_ACC) AS NUM_NUM_PMT_BK_OP_ACC,
MAX(NUM_PMT_BK_OP_ACC)   AS MAX_NUM_PMT_BK_OP_ACC,
SUM(NUM_PMT_BK_OP_ACC)   AS SUM_NUM_PMT_BK_OP_ACC,
MIN(NUM_PMT_BK_OP_ACC)   AS MIN_NUM_PMT_BK_OP_ACC,
SUM(NUM_PMT_BK_OP_ACC)/NULLIF(COUNT(NUM_PMT_BK_OP_ACC),0) AS AVG_NUM_PMT_BK_OP_ACC,

COUNT(NUM_PMT_BK) AS NUM_NUM_PMT_BK,
MAX(NUM_PMT_BK)   AS MAX_NUM_PMT_BK,
SUM(NUM_PMT_BK)   AS SUM_NUM_PMT_BK,
MIN(NUM_PMT_BK)   AS MIN_NUM_PMT_BK,
SUM(NUM_PMT_BK)/NULLIF(COUNT(NUM_PMT_BK),0) AS AVG_NUM_PMT_BK,

COUNT(NUM_PMT_NBK_AU_CL_ACC) AS NUM_NUM_PMT_NBK_AU_CL_ACC,
MAX(NUM_PMT_NBK_AU_CL_ACC)   AS MAX_NUM_PMT_NBK_AU_CL_ACC,
SUM(NUM_PMT_NBK_AU_CL_ACC)   AS SUM_NUM_PMT_NBK_AU_CL_ACC,
MIN(NUM_PMT_NBK_AU_CL_ACC)   AS MIN_NUM_PMT_NBK_AU_CL_ACC,
SUM(NUM_PMT_NBK_AU_CL_ACC)/NULLIF(COUNT(NUM_PMT_NBK_AU_CL_ACC),0) AS AVG_NUM_PMT_NBK_AU_CL_ACC,

COUNT(NUM_PMT_NBK_AU_OP_ACC) AS NUM_NUM_PMT_NBK_AU_OP_ACC,
MAX(NUM_PMT_NBK_AU_OP_ACC)   AS MAX_NUM_PMT_NBK_AU_OP_ACC,
SUM(NUM_PMT_NBK_AU_OP_ACC)   AS SUM_NUM_PMT_NBK_AU_OP_ACC,
MIN(NUM_PMT_NBK_AU_OP_ACC)   AS MIN_NUM_PMT_NBK_AU_OP_ACC,
SUM(NUM_PMT_NBK_AU_OP_ACC)/NULLIF(COUNT(NUM_PMT_NBK_AU_OP_ACC),0) AS AVG_NUM_PMT_NBK_AU_OP_ACC,

COUNT(NUM_PMT_NBK_AU) AS NUM_NUM_PMT_NBK_AU,
MAX(NUM_PMT_NBK_AU)   AS MAX_NUM_PMT_NBK_AU,
SUM(NUM_PMT_NBK_AU)   AS SUM_NUM_PMT_NBK_AU,
MIN(NUM_PMT_NBK_AU)   AS MIN_NUM_PMT_NBK_AU,
SUM(NUM_PMT_NBK_AU)/NULLIF(COUNT(NUM_PMT_NBK_AU),0) AS AVG_NUM_PMT_NBK_AU,

COUNT(NUM_PMT_NBK_M_CL_ACC) AS NUM_NUM_PMT_NBK_M_CL_ACC,
MAX(NUM_PMT_NBK_M_CL_ACC)   AS MAX_NUM_PMT_NBK_M_CL_ACC,
SUM(NUM_PMT_NBK_M_CL_ACC)   AS SUM_NUM_PMT_NBK_M_CL_ACC,
MIN(NUM_PMT_NBK_M_CL_ACC)   AS MIN_NUM_PMT_NBK_M_CL_ACC,
SUM(NUM_PMT_NBK_M_CL_ACC)/NULLIF(COUNT(NUM_PMT_NBK_M_CL_ACC),0) AS AVG_NUM_PMT_NBK_M_CL_ACC,

COUNT(NUM_PMT_NBK_M_OP_ACC) AS NUM_NUM_PMT_NBK_M_OP_ACC,
MAX(NUM_PMT_NBK_M_OP_ACC)   AS MAX_NUM_PMT_NBK_M_OP_ACC,
SUM(NUM_PMT_NBK_M_OP_ACC)   AS SUM_NUM_PMT_NBK_M_OP_ACC,
MIN(NUM_PMT_NBK_M_OP_ACC)   AS MIN_NUM_PMT_NBK_M_OP_ACC,
SUM(NUM_PMT_NBK_M_OP_ACC)/NULLIF(COUNT(NUM_PMT_NBK_M_OP_ACC),0) AS AVG_NUM_PMT_NBK_M_OP_ACC,

COUNT(NUM_PMT_NBK_M) AS NUM_NUM_PMT_NBK_M,
MAX(NUM_PMT_NBK_M)   AS MAX_NUM_PMT_NBK_M,
SUM(NUM_PMT_NBK_M)   AS SUM_NUM_PMT_NBK_M,
MIN(NUM_PMT_NBK_M)   AS MIN_NUM_PMT_NBK_M,
SUM(NUM_PMT_NBK_M)/NULLIF(COUNT(NUM_PMT_NBK_M),0) AS AVG_NUM_PMT_NBK_M,

COUNT(NUM_PMT_NBK_PL_CL_ACC) AS NUM_NUM_PMT_NBK_PL_CL_ACC,
MAX(NUM_PMT_NBK_PL_CL_ACC)   AS MAX_NUM_PMT_NBK_PL_CL_ACC,
SUM(NUM_PMT_NBK_PL_CL_ACC)   AS SUM_NUM_PMT_NBK_PL_CL_ACC,
MIN(NUM_PMT_NBK_PL_CL_ACC)   AS MIN_NUM_PMT_NBK_PL_CL_ACC,
SUM(NUM_PMT_NBK_PL_CL_ACC)/NULLIF(COUNT(NUM_PMT_NBK_PL_CL_ACC),0) AS AVG_NUM_PMT_NBK_PL_CL_ACC,

COUNT(NUM_PMT_NBK_PL_OP_ACC) AS NUM_NUM_PMT_NBK_PL_OP_ACC,
MAX(NUM_PMT_NBK_PL_OP_ACC)   AS MAX_NUM_PMT_NBK_PL_OP_ACC,
SUM(NUM_PMT_NBK_PL_OP_ACC)   AS SUM_NUM_PMT_NBK_PL_OP_ACC,
MIN(NUM_PMT_NBK_PL_OP_ACC)   AS MIN_NUM_PMT_NBK_PL_OP_ACC,
SUM(NUM_PMT_NBK_PL_OP_ACC)/NULLIF(COUNT(NUM_PMT_NBK_PL_OP_ACC),0) AS AVG_NUM_PMT_NBK_PL_OP_ACC,

COUNT(NUM_PMT_NBK_PL) AS NUM_NUM_PMT_NBK_PL,
MAX(NUM_PMT_NBK_PL)   AS MAX_NUM_PMT_NBK_PL,
SUM(NUM_PMT_NBK_PL)   AS SUM_NUM_PMT_NBK_PL,
MIN(NUM_PMT_NBK_PL)   AS MIN_NUM_PMT_NBK_PL,
SUM(NUM_PMT_NBK_PL)/NULLIF(COUNT(NUM_PMT_NBK_PL),0) AS AVG_NUM_PMT_NBK_PL,

COUNT(NUM_PMT_NBK_CL_ACC) AS NUM_NUM_PMT_NBK_CL_ACC,
MAX(NUM_PMT_NBK_CL_ACC)   AS MAX_NUM_PMT_NBK_CL_ACC,
SUM(NUM_PMT_NBK_CL_ACC)   AS SUM_NUM_PMT_NBK_CL_ACC,
MIN(NUM_PMT_NBK_CL_ACC)   AS MIN_NUM_PMT_NBK_CL_ACC,
SUM(NUM_PMT_NBK_CL_ACC)/NULLIF(COUNT(NUM_PMT_NBK_CL_ACC),0) AS AVG_NUM_PMT_NBK_CL_ACC,

COUNT(NUM_PMT_NBK_OP_ACC) AS NUM_NUM_PMT_NBK_OP_ACC,
MAX(NUM_PMT_NBK_OP_ACC)   AS MAX_NUM_PMT_NBK_OP_ACC,
SUM(NUM_PMT_NBK_OP_ACC)   AS SUM_NUM_PMT_NBK_OP_ACC,
MIN(NUM_PMT_NBK_OP_ACC)   AS MIN_NUM_PMT_NBK_OP_ACC,
SUM(NUM_PMT_NBK_OP_ACC)/NULLIF(COUNT(NUM_PMT_NBK_OP_ACC),0) AS AVG_NUM_PMT_NBK_OP_ACC,

COUNT(NUM_PMT_NBK) AS NUM_NUM_PMT_NBK,
MAX(NUM_PMT_NBK)   AS MAX_NUM_PMT_NBK,
SUM(NUM_PMT_NBK)   AS SUM_NUM_PMT_NBK,
MIN(NUM_PMT_NBK)   AS MIN_NUM_PMT_NBK,
SUM(NUM_PMT_NBK)/NULLIF(COUNT(NUM_PMT_NBK),0) AS AVG_NUM_PMT_NBK,

COUNT(NUM_PMT_AU_CL_ACC) AS NUM_NUM_PMT_AU_CL_ACC,
MAX(NUM_PMT_AU_CL_ACC)   AS MAX_NUM_PMT_AU_CL_ACC,
SUM(NUM_PMT_AU_CL_ACC)   AS SUM_NUM_PMT_AU_CL_ACC,
MIN(NUM_PMT_AU_CL_ACC)   AS MIN_NUM_PMT_AU_CL_ACC,
SUM(NUM_PMT_AU_CL_ACC)/NULLIF(COUNT(NUM_PMT_AU_CL_ACC),0) AS AVG_NUM_PMT_AU_CL_ACC,

COUNT(NUM_PMT_AU_OP_ACC) AS NUM_NUM_PMT_AU_OP_ACC,
MAX(NUM_PMT_AU_OP_ACC)   AS MAX_NUM_PMT_AU_OP_ACC,
SUM(NUM_PMT_AU_OP_ACC)   AS SUM_NUM_PMT_AU_OP_ACC,
MIN(NUM_PMT_AU_OP_ACC)   AS MIN_NUM_PMT_AU_OP_ACC,
SUM(NUM_PMT_AU_OP_ACC)/NULLIF(COUNT(NUM_PMT_AU_OP_ACC),0) AS AVG_NUM_PMT_AU_OP_ACC,

COUNT(NUM_PMT_AU) AS NUM_NUM_PMT_AU,
MAX(NUM_PMT_AU)   AS MAX_NUM_PMT_AU,
SUM(NUM_PMT_AU)   AS SUM_NUM_PMT_AU,
MIN(NUM_PMT_AU)   AS MIN_NUM_PMT_AU,
SUM(NUM_PMT_AU)/NULLIF(COUNT(NUM_PMT_AU),0) AS AVG_NUM_PMT_AU,

COUNT(NUM_PMT_M_CL_ACC) AS NUM_NUM_PMT_M_CL_ACC,
MAX(NUM_PMT_M_CL_ACC)   AS MAX_NUM_PMT_M_CL_ACC,
SUM(NUM_PMT_M_CL_ACC)   AS SUM_NUM_PMT_M_CL_ACC,
MIN(NUM_PMT_M_CL_ACC)   AS MIN_NUM_PMT_M_CL_ACC,
SUM(NUM_PMT_M_CL_ACC)/NULLIF(COUNT(NUM_PMT_M_CL_ACC),0) AS AVG_NUM_PMT_M_CL_ACC,

COUNT(NUM_PMT_M_OP_ACC) AS NUM_NUM_PMT_M_OP_ACC,
MAX(NUM_PMT_M_OP_ACC)   AS MAX_NUM_PMT_M_OP_ACC,
SUM(NUM_PMT_M_OP_ACC)   AS SUM_NUM_PMT_M_OP_ACC,
MIN(NUM_PMT_M_OP_ACC)   AS MIN_NUM_PMT_M_OP_ACC,
SUM(NUM_PMT_M_OP_ACC)/NULLIF(COUNT(NUM_PMT_M_OP_ACC),0) AS AVG_NUM_PMT_M_OP_ACC,

COUNT(NUM_PMT_M) AS NUM_NUM_PMT_M,
MAX(NUM_PMT_M)   AS MAX_NUM_PMT_M,
SUM(NUM_PMT_M)   AS SUM_NUM_PMT_M,
MIN(NUM_PMT_M)   AS MIN_NUM_PMT_M,
SUM(NUM_PMT_M)/NULLIF(COUNT(NUM_PMT_M),0) AS AVG_NUM_PMT_M,

COUNT(NUM_PMT_PL_CL_ACC) AS NUM_NUM_PMT_PL_CL_ACC,
MAX(NUM_PMT_PL_CL_ACC)   AS MAX_NUM_PMT_PL_CL_ACC,
SUM(NUM_PMT_PL_CL_ACC)   AS SUM_NUM_PMT_PL_CL_ACC,
MIN(NUM_PMT_PL_CL_ACC)   AS MIN_NUM_PMT_PL_CL_ACC,
SUM(NUM_PMT_PL_CL_ACC)/NULLIF(COUNT(NUM_PMT_PL_CL_ACC),0) AS AVG_NUM_PMT_PL_CL_ACC,

COUNT(NUM_PMT_PL_OP_ACC) AS NUM_NUM_PMT_PL_OP_ACC,
MAX(NUM_PMT_PL_OP_ACC)   AS MAX_NUM_PMT_PL_OP_ACC,
SUM(NUM_PMT_PL_OP_ACC)   AS SUM_NUM_PMT_PL_OP_ACC,
MIN(NUM_PMT_PL_OP_ACC)   AS MIN_NUM_PMT_PL_OP_ACC,
SUM(NUM_PMT_PL_OP_ACC)/NULLIF(COUNT(NUM_PMT_PL_OP_ACC),0) AS AVG_NUM_PMT_PL_OP_ACC,

COUNT(NUM_PMT_PL) AS NUM_NUM_PMT_PL,
MAX(NUM_PMT_PL)   AS MAX_NUM_PMT_PL,
SUM(NUM_PMT_PL)   AS SUM_NUM_PMT_PL,
MIN(NUM_PMT_PL)   AS MIN_NUM_PMT_PL,
SUM(NUM_PMT_PL)/NULLIF(COUNT(NUM_PMT_PL),0) AS AVG_NUM_PMT_PL,

COUNT(NUM_PMT_CL_ACC) AS NUM_NUM_PMT_CL_ACC,
MAX(NUM_PMT_CL_ACC)   AS MAX_NUM_PMT_CL_ACC,
SUM(NUM_PMT_CL_ACC)   AS SUM_NUM_PMT_CL_ACC,
MIN(NUM_PMT_CL_ACC)   AS MIN_NUM_PMT_CL_ACC,
SUM(NUM_PMT_CL_ACC)/NULLIF(COUNT(NUM_PMT_CL_ACC),0) AS AVG_NUM_PMT_CL_ACC,

COUNT(NUM_PMT_OP_ACC) AS NUM_NUM_PMT_OP_ACC,
MAX(NUM_PMT_OP_ACC)   AS MAX_NUM_PMT_OP_ACC,
SUM(NUM_PMT_OP_ACC)   AS SUM_NUM_PMT_OP_ACC,
MIN(NUM_PMT_OP_ACC)   AS MIN_NUM_PMT_OP_ACC,
SUM(NUM_PMT_OP_ACC)/NULLIF(COUNT(NUM_PMT_OP_ACC),0) AS AVG_NUM_PMT_OP_ACC,

COUNT(NUM_PMT) AS NUM_NUM_PMT,
MAX(NUM_PMT)   AS MAX_NUM_PMT,
SUM(NUM_PMT)   AS SUM_NUM_PMT,
MIN(NUM_PMT)   AS MIN_NUM_PMT,
SUM(NUM_PMT)/NULLIF(COUNT(NUM_PMT),0) AS AVG_NUM_PMT,


COUNT(NUM_PMT_TU_ALL) AS NUM_NUM_PMT_TU_ALL,
MAX(NUM_PMT_TU_ALL)   AS MAX_NUM_PMT_TU_ALL,
SUM(NUM_PMT_TU_ALL)   AS SUM_NUM_PMT_TU_ALL,
MIN(NUM_PMT_TU_ALL)   AS MIN_NUM_PMT_TU_ALL,
SUM(NUM_PMT_TU_ALL)/NULLIF(COUNT(NUM_PMT_TU_ALL),0) AS AVG_NUM_PMT_TU_ALL,

COUNT(NUM_PMT_TU) AS NUM_NUM_PMT_TU,
MAX(NUM_PMT_TU)   AS MAX_NUM_PMT_TU,
SUM(NUM_PMT_TU)   AS SUM_NUM_PMT_TU,
MIN(NUM_PMT_TU)   AS MIN_NUM_PMT_TU,
SUM(NUM_PMT_TU)/NULLIF(COUNT(NUM_PMT_TU),0) AS AVG_NUM_PMT_TU,

COUNT(NUM_PMT_TU_ALL_OP_ACC) AS NUM_NUM_PMT_TU_ALL_OP_ACC,
MAX(NUM_PMT_TU_ALL_OP_ACC)   AS MAX_NUM_PMT_TU_ALL_OP_ACC,
SUM(NUM_PMT_TU_ALL_OP_ACC)   AS SUM_NUM_PMT_TU_ALL_OP_ACC,
MIN(NUM_PMT_TU_ALL_OP_ACC)   AS MIN_NUM_PMT_TU_ALL_OP_ACC,
SUM(NUM_PMT_TU_ALL_OP_ACC)/NULLIF(COUNT(NUM_PMT_TU_ALL_OP_ACC),0) AS AVG_NUM_PMT_TU_ALL_OP_ACC,

COUNT(NUM_PMT_TU_OP_ACC) AS NUM_NUM_PMT_TU_OP_ACC,
MAX(NUM_PMT_TU_OP_ACC)   AS MAX_NUM_PMT_TU_OP_ACC,
SUM(NUM_PMT_TU_OP_ACC)   AS SUM_NUM_PMT_TU_OP_ACC,
MIN(NUM_PMT_TU_OP_ACC)   AS MIN_NUM_PMT_TU_OP_ACC,
SUM(NUM_PMT_TU_OP_ACC)/NULLIF(COUNT(NUM_PMT_TU_OP_ACC),0) AS AVG_NUM_PMT_TU_OP_ACC,

COUNT(NUM_PMT_TU_ALL_CL_ACC) AS NUM_NUM_PMT_TU_ALL_CL_ACC,
MAX(NUM_PMT_TU_ALL_CL_ACC)   AS MAX_NUM_PMT_TU_ALL_CL_ACC,
SUM(NUM_PMT_TU_ALL_CL_ACC)   AS SUM_NUM_PMT_TU_ALL_CL_ACC,
MIN(NUM_PMT_TU_ALL_CL_ACC)   AS MIN_NUM_PMT_TU_ALL_CL_ACC,
SUM(NUM_PMT_TU_ALL_CL_ACC)/NULLIF(COUNT(NUM_PMT_TU_ALL_CL_ACC),0) AS AVG_NUM_PMT_TU_ALL_CL_ACC,

COUNT(NUM_PMT_TU_CL_ACC) AS NUM_NUM_PMT_TU_CL_ACC,
MAX(NUM_PMT_TU_CL_ACC)   AS MAX_NUM_PMT_TU_CL_ACC,
SUM(NUM_PMT_TU_CL_ACC)   AS SUM_NUM_PMT_TU_CL_ACC,
MIN(NUM_PMT_TU_CL_ACC)   AS MIN_NUM_PMT_TU_CL_ACC,
SUM(NUM_PMT_TU_CL_ACC)/NULLIF(COUNT(NUM_PMT_TU_CL_ACC),0) AS AVG_NUM_PMT_TU_CL_ACC,

COUNT(NUM_PMT_NBK_TU) AS NUM_NUM_PMT_NBK_TU,
MAX(NUM_PMT_NBK_TU)   AS MAX_NUM_PMT_NBK_TU,
SUM(NUM_PMT_NBK_TU)   AS SUM_NUM_PMT_NBK_TU,
MIN(NUM_PMT_NBK_TU)   AS MIN_NUM_PMT_NBK_TU,
SUM(NUM_PMT_NBK_TU)/NULLIF(COUNT(NUM_PMT_NBK_TU),0) AS AVG_NUM_PMT_NBK_TU,

COUNT(NUM_PMT_NBK_TU_OP_ACC) AS NUM_NUM_PMT_NBK_TU_OP_ACC,
MAX(NUM_PMT_NBK_TU_OP_ACC)   AS MAX_NUM_PMT_NBK_TU_OP_ACC,
SUM(NUM_PMT_NBK_TU_OP_ACC)   AS SUM_NUM_PMT_NBK_TU_OP_ACC,
MIN(NUM_PMT_NBK_TU_OP_ACC)   AS MIN_NUM_PMT_NBK_TU_OP_ACC,
SUM(NUM_PMT_NBK_TU_OP_ACC)/NULLIF(COUNT(NUM_PMT_NBK_TU_OP_ACC),0) AS AVG_NUM_PMT_NBK_TU_OP_ACC,

COUNT(NUM_PMT_NBK_TU_CL_ACC) AS NUM_NUM_PMT_NBK_TU_CL_ACC,
MAX(NUM_PMT_NBK_TU_CL_ACC)   AS MAX_NUM_PMT_NBK_TU_CL_ACC,
SUM(NUM_PMT_NBK_TU_CL_ACC)   AS SUM_NUM_PMT_NBK_TU_CL_ACC,
MIN(NUM_PMT_NBK_TU_CL_ACC)   AS MIN_NUM_PMT_NBK_TU_CL_ACC,
SUM(NUM_PMT_NBK_TU_CL_ACC)/NULLIF(COUNT(NUM_PMT_NBK_TU_CL_ACC),0) AS AVG_NUM_PMT_NBK_TU_CL_ACC

FROM dbmymwork.BTDC_LGG_VAR_SEGMENTADAS_1
GROUP BY CUENTADEREFERENCIA,
FECHA_CARTERA
;

SELECT * FROM  dbmymwork.BTDC_LGG_VAR_NUM_PMT LIMIT 100;